### PR TITLE
Adding Random Video Screensaver/Attract Mode, plus controls

### PR DESCRIPTION
**Pull request by pjft**
- Adding random video screensaver option (by @fieldofcows, I just squashed the commits). Videos change after 35s. ES will try to load a random video that the gamelist references, and will retry up to 200 times (i.e. 200 consecutive random videos) in case it can't find a particular video file. If after 200 tries none of the random paths from the gamelist pointed to any valid file, it will default to the black screensaver.
- Added option to control the random video screensaver: if enabled, you can launch the game that's being shown at the time (press start or X during the screensaver), skip to another video before the 35s are elapsed by pushing "right" on your joystick, and launch the screensaver by pressing "Select" on the system view. If disabled, it works as normal.
- You can also choose to show the current game name on the screensaver by enabling an option on the menu. It's not ON by default because in some screen resolutions and frequencies (particularly 60Hz), with overscan turned on, the video card will fail to render things. 
- Screensaver is rendered via OMXPlayer on the Pi, regardless of the users using OMX Player or VLC for the gamelist view. It makes no sense otherwise, and VLC performs somewhat sub-optimally rendering the video at full screen. On the PC it's done via VLC.

This is pretty much the equivalent to the rebased OMX build I have been using and running for a few months now, as well as a few others in the forums. Testing is definitely appreciated and welcome, but it should be solid on the Pi.

What would be really helpful, is for people to test it on Windows and on other systems, just to make sure that the screensaver works well with VLC at the moment, in particular the video game name as well, as I don't have a system to test that on and while I briefly tested it on the Pi, the performance isn't there so I can't tell whether it's working or not.

Note 1: The "random video" screensaver only works with videos. If you have no videos, or it has trouble finding random games for which you have videos for, it will default to the "black" screensaver.
Note 2: currently the video zoom in transition using "slide" is broken. It is not related with this commit, and will be dealt separately.

Thanks!

### CODE REVIEW

**Comment by TMNTturtleguy** [comment]
I have tested this build for several hours and it appears to be working as expected.  I have been running the omx-screensaver build by @pjft for several months as my main ES and this performs exactly as expected.

**Comment by hex007** [comment]
This currently has some problems on Linux PC and we are working to get it fixed

**Comment by hex007** [comment]
Works well on Linux now

**Comment by joolswills** [comment]
Is this read to go ?

I'm afraid it will need rebasing - probably because I just merged the audio mixer config PR.

**Comment by pjft** [comment]
Just waiting on a few confirmations from Linux and then I'll rebase. Would
also love to get some confirmation from any Windows users, just to run the
gamut of common systems, but given the Pi and Linux seem to be going well,
it's desirable though not necessarily required.

@zigurana and @jdrassa - I believe you run a Windows system? Would you have
the chance to just compile and sanity check this? In particular that the
VLC performance on the screensaver works well?

**Comment by hex007** [comment]
@joolswills @pjft Can I suggest making the Settings bit more optimized

**Comment by pjft** [comment]
Sure! What do you have in mind? Also, let me know your answer on my last
comments on the forum, would love to reduce or remove the resolution option
for the screensaver captions if it works well on high resolution.

**Comment by hex007** [comment]
@pjft  For video Screensavers options for resolution how about low/video/screen/max

Low -> For Pi zero and 1
Video and Screen for Pi 2,3
Max for PCs (ie. max(video,screen))

**Comment by pjft** [comment]
That's the thing: the resolution thing is only valid for VLC. OMX Player
will run well (hopefully) at current resolution on the Pi - at least
guaranteed better than VLC :)

There's no option for VLC screensaver on the Pi, regardless of the video
player one chooses for the gamelist.

That option only shows on Linux/Windows/non-pi systems.

**Comment by hex007** [comment]
I dont see the point of throttling resolution on PC. They are more than capable of running well at high settings
 
Changing Random Video to Video/Snaps should suffice. (preferably snaps as it indicates origin of videos)

**Comment by hex007** [comment]
Is the `stretch` parameter configurable for screensaver? My Snaps are 4:3 and my aspect s 16:9

**Comment by pjft** [comment]
Only for OMX Player. VLC is by default full screen, though I may take one
last look at that and see how to do that.

As such, you shouldn't be seeing the stretch parameter outside of the Pi.

I'll remove the option for resolution then, it's fairly pointless and it's
really only useful for the captions. I may actually make it so that if you
don't choose captions you'll just use the native resolution upscaled, which
helps with performance and has no meaningful impact on the quality.

**Comment by hex007** [comment]
I was hoping for a short word that would convey the meaning rather than more words.

**Comment by pjft** [comment]
Oh. "Video" then?

**Comment by hex007** [comment]
I am comfortable with Videos/Snaps/Video Snaps.

@joolswills Any suggestions?

**Comment by TMNTturtleguy** [comment]
I know i am not part of the conversation, but i want to add my own two thoughts.  I think it should be "Random Video"

Reasons:  
1. Many people who have used this over the last few months have asked about using their own custom videos, by just naming it video it conveys that you could select a video to play as a screensaver, which you cannot do.
2. as @pjft suggests, "random images" would be a nice future addition.
3. This leaves it open for a future development of "Video" or "Selected Video" which could be implemented to always run a user specified video, like the startup splashscreen.
4. I have never liked the term snaps.....did it originate from hyperspin? Snaps means nothing to a newbie with no previous knowledge.

Sorry for adding thoughts, take them or leave them, i love the screensaver either way!

**Comment by Darknior** [comment]
I'm agree with you @TMNTturtleguy 
I'm a PI user, but for PC users i have a good feature to add one day ... maybe on PI too if one day the ffmpeg video support comme :P 
- Adding the game LOGO in front of the video (with VLC and in a top corner). Like that you know what you are watching and it is beautiful :)
- It can works too with "Random images" if we use Screenshot images ;)
Not fine for Title Shot, Logo, Covers ...

**Comment by pjft** [comment]
@TMNTturtleguy @Darknior Everybody's part of the conversation - that's part of the goal of doing things here on GitHub in an open environment. It doesn't mean the decision ends up being democratic, but everybody's opinions are more than welcome, as well as encouraged!

**Comment by hex007** [comment]
@TMNTturtleguy Your reasoning makes sense

**Comment by pjft** [comment]
Ok, so a final update.

I've just updated the rebased branch with:
- Only two options for VLC screensaver quality (only visible in non-Pi devices): "high" and "fast". Default is "high".
- Added "stretch" option to VLC screensaver as well (so it can keep video proportions). It's "off" by default.
- Option name stays "Random Video" at the moment.

Would appreciate one final round of testing on Linux and the Pi, just to confirm I'm not missing anything.

Thank you all.

**Comment by TMNTturtleguy** [comment]
I will test later on in my evening and report back!  Thanks for the hard work.

**Comment by pjft** [comment]
Not at all, thank you for being with this from the literal beginning a few
months ago! :)


- Paulo Tavares

**Comment by TMNTturtleguy** [comment]
installed the update on pi 3 and used for a good amount of time with no issues.  everything seems to be working as expected. Thank you for all the hard work and for letting me test out all of your impressive updates.

**Comment by pjft** [comment]
Ok, so a final tidying up update.

- Removed VLC option for Pi's screensaver from the menu. Performance was terrible anyway.
- Added a "info/warning" box when enabling captions for the screensaver on the Pi, letting people know that if the screen signal fails during the screensaver with captions they should disable them, or disable overscan on the Raspberry Pi system config. I give them the steps as well.
- Moved OMX Player setting inside the Other Settings menu.
- The remaining screensaver options now belong in a menu named "Video Screensaver Settings".

Hopefully this is it for now. Good fun.

**Comment by TMNTturtleguy** [comment]
I cannot comment on @hex007 build, but i have thoroughly tested the latest update on 2 separate builds, 4:3 display and 16:9 display and everything works really well.  The menus work and look nicely and performance is great.  Thanks for all the hard work.

**Comment by hex007** [comment]
Running on 720p on TV with OMX player, I just get a blank screen. The HDMI is not lost as i am able to see the low power icon sometimes

**Comment by pjft** [comment]
Low power probably means just that. Do you have a different power adapter
to test?

If you run "top" is the process even started? If not, could you try
changing the audio option back to both and see if it starts then?

What are your settings file's content at this stage, given the several
iterations of the builds?

Maybe we can troubleshoot this in the forums as quite a few people get
emails here:)

Thanks!

**Comment by pjft** [comment]
Ok, updated the PR. Re-added the VLC option for screensaver on the Pi, in case for some reason OMXPlayer doesn't work. It will have the same performance as it currently does on the gamelist.

Other relevant changes:

- Moved OMX Player setting inside the Other Settings menu.
- The remaining screensaver options now belong in a menu named "Video Screensaver Settings". It's now inside the "UI Settings" menu, after the Screensaver Type selection.
- Added an info popup when selecting "Random Video" screensaver as well, stating that these are random videos from the gamelists (rather than, I don't know, youtube game videos, or from a specific folder on the Pi).

I have no further additions at this stage, happy to have it merged if/when it suits, unless there are any objections.

**Comment by joolswills** [comment]
Thanks for all your work on this and to everyone for testing.

**Comment by Darknior** [comment]
I have all test today on my PI 3
Thanks for added a "info/warning" box when enabling captions for the screensaver ... it help :p 
But it miss something, the sound control : Sound Settings/Systeme Volume : If possible ...
It works for emulators but not OMX, and it has a high volume !
If we can't low the OMX volume we must push all emulators volume higher to have same every where :(

**Comment by pjft** [comment]
Oh. You mean the actual video volume?

I may have a look at it in the coming weeks, sure. At least try to make the
volume slider also control the video volume as well. No need to file a bug
for that - but if you don't hear anything in this in the next few weeks
feel free to gently remind me here or in the forums. :)

Out of curiosity, did you experience any problems with the screensaver
captions, and how did you fix them?

Glad it's working for you! Good to have confirmation.

**Comment by Darknior** [comment]
Thanks a lot, i will gently remind you here if you forgot it :p
The problem here and on the forum was we can't have private discutions ... No PM possible to exchange idées and projects we don't want to make public at the beginning ... :(
It's why i let here, my email in my profile.

For the screensaver it work perfectly on my old Plasma HD TV with HDMI adapter. I try on my other TV and Video projector for the moment.
I love the START and SELECT idea :D
I have the Glitch at the bottom of the screen if i activate the title of the screen ... 
I must try on an other TV and with Over scan, on the Plasma i can't use the Over scan.

**Comment by pjft** [comment]
Let's move this to the forums then. Way too many emails to too many people
if we do it here :)

https://retropie.org.uk/forum/topic/8734/please-test-random-game-selection-launch-via-video-screensaver/

Would love to know more and potentially test out a few different builds to
see if we can at least mitigate it.

Thanks.


- Paulo Tavares

**Pull request merged**
