### PR TITLE
Update FileSystemUtil.cpp - Allow for multilevel absolute paths in gamelist.xml

### PR DESCRIPTION
**Pull request by johnodon**
Allow for multilevel absolute paths in gamelist.xml.

See discussion here: https://retropie.org.uk/forum/topic/30984/multi-level-absolute-paths-in-gamelist-xml-not-working?_=1631445878380

### CODE REVIEW

**Comment by pjft** [comment]
Thanks. I'd like @Gemba 's inputs here if possible, as I believe he was involved in the thread, and clarification on the testing performed here.

Specifically:
- Paths starting with "." (as these were working so far, but now seem to be concatenated?);
- Paths starting with a file or folder name (ace.daphne, for instance);
- Paths starting with "~" (I believe that the code path shouldn't go through it);
- Paths with "..", of course - I expect those to work now at least on Linux.

And last but not least, Linux vs Windows (if possible), as I am not sure how Windows will deal with those relative paths being prepended by a full path.

Just to make sure that this change addresses all the nuances without breaking anything that was currently working, or that we identify what edge cases need further special treatment.

Thanks for sending this over!

**Comment by tomaz82** [comment]
I don't think that's gonna work since it now assumes that a path starting with '/' is absolute, and anything else wil gett relativeTo appended to it. The current behavior is not broken, it's by design. "./" appends relativeTo and "~/" appends homePath.

If anything it should do.

```
			// append relativeTo if "../"
			if((path[0] == '.') && (path[1] == '.') && (path[2] == '/'))
				return (relativeTo + '/' + path);
```

But even then I still doubt it's gonna work because nothing actually resolves those ../

**Comment by Gemba** [comment]
Took me a while. Can not follow here linear all the time.
But right @pjft I was involved in this forum topic.
Replying to your questions:

> Specifically:
> 
>     * Paths starting with "." (as these were working so far, but now seem to be concatenated?);

Logic untouched, only the current comment is confusing (./ will be treated as relative indicator, not . as the source comment states)

> 
>     * Paths starting with a file or folder name (ace.daphne, for instance);

Two cases (both Windows and Linux): 
a) path consisting _only_ of file: will be prefixed with `_relativeTo` with this change, before this change returned unchanged (I assume path input never consisted of a single file in the past) .
b) path starting with folder: will be prefixed with `_relativeTo` with this change (what the reporter is requesting), before this change returned unchanged.

> 
>     * Paths starting with "~" (I believe that the code path shouldn't go through it);
> 

Untouched logic. However, not robust if some input contains Windows specific aliases for paths (e.g. `%USERHOME%`) at Windows (e.g. a Scraper produces or done by manual edit). The `resolveRelativePath()` method in  general is used atm only for processing Theme-XML and Gamelist-XML files. Thus the enduser is either shooting in its own feet or the scraper author should eliminate any Windows variables before writing a gamelist.xml.

>     * Paths with "..", of course - I expect those to work now at least on Linux.

With this change will be prefixed with `_relativeTo` (Linux and Windows)

> 
> And last but not least, Linux vs Windows (if possible), as I am not sure how Windows will deal with those relative paths being prepended by a full path.

If the prepended absolute ("full") path does not contain a drive letter it is absolute to the drive ES was started from on Windows. If there is a drive letter (see below) it is absolute to the designated drive and path at that drive.

Windows absolute paths are more complex to deal with (cf. https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#example-ways-to-refer-to-the-same-file) but luckily `resolveRelativePath()` uses `getGenericPath()` beforehand which reduces the cases to test for.

As `getGenericPath()` returns `c:/foo/bar` for `\\?\c:\foo\bar` and `//<host>/<share>/folder` for input  `\\<host>\<share>\folder` the only not supported prefix is `\\.\` (but again this is also not covered in the current implementation). Thus the only catch I have found is that the test for absolute path should also be check for a colon on Windows.

So make:
```
                        // absolute path
                        if(path[0] == '/')
                                return path;
```
read in this change:
```
                        // absolute path
                        if(path[0] == '/' || path[1] == ':')
                                return path;
```

**Comment by Gemba** [comment]
While your comments are right and change is also right @tomaz82 it misses `path/to/something` input, thus the enduser must enter/provide `./path/to/something` to get an absolute path returned.

**Pull request merged**
