### PR TITLE
Fix pugixml include paths and make submodule optional

### PR DESCRIPTION
**Pull request by tfc**
This PR corrects the pugixml include paths to the paths that pugixml is ought to be included from when installed as a package.
These also work when pugixml is built locally from source.

In addition to that, i added a conditional that builds pugixml from source if it is not available as a system-wide installation.

### CODE REVIEW

**Comment by cmitu** [comment]
I don't think the PR is correct:

1. If the system `pugixml` library is not found, `cmake` will not complete, due to the package being `REQUIRED`. So building with the locally included `pugixml` will not work.
2. Even if 1. is resolved, the path changes for the `#include` statements cannot work with both a system installed and the local source at the same time.

**Comment by tfc** [comment]
@cmitu you're right.

I forgot to commit that i updated pugixml to the latest release where they also got their include path propagation corrected.
I also removed the `required` clause now. This works with a local build.

**Comment by cmitu** [comment]
Thanks, it seems fixed now.

**Comment by pjft** [comment]
@cmitu  are you ok with this PR in its current state? Do the paths work with both system install and local source?

**Comment by cmitu** [comment]
@pjft yes, should be ok to merge.

**Comment by pjft** [comment]
Thanks both. 

@tfc  could you squash the commits and then I can merge? Thank you!

**Comment by tfc** [comment]
@pjft they are squashed now

**Comment by pjft** [comment]
Thank you for sending this over!

**Pull request merged**
