### PR TITLE
screensaver bug fixes - don't ignore the UI mode and skip empty video/image entries.

### PR DESCRIPTION
**Pull request by cmitu**
Currently, when configured to use a random image/video, the screensaver looks into the gamelist files directly. Fix a few bugs reported in the forum:
* screensaver ignoring the game tag and showing videos from an entry which is out of view (reported in https://retropie.org.uk/forum/topic/21278/)
* screensaver counting nodes with empty `video` tages when building the list available videos. Ignoring them skips the path check and the black screen shown until the next valid video is found (reported in https://retropie.org.uk/forum/topic/21258/just-updated-retropie-now-screensaver-doesn-t-work/8).

### CODE REVIEW

**Comment by pjft** [comment]
Thanks for putting this together.

No concerns from my side, everything seems to add up.

A question, though:

Those checks for 

```
if (!isKidGame && UIModeController::getInstance()->isUIModeKid())
						continue;
					if (isHidden && UIModeController::getInstance()->isUIModeKiosk())
						continue;
```

could probably be centralized, as I imagine they're used elsewhere as well and if the logic changes one day (or if there's a but in one of those checks) it's harder to track down and fix.

Maybe a simple method for "isVisible(game)" could solve that? Unsure if it'd be part of ViewController, UIModeController or the actual FileData class - it's been a while since I looked into those in a more in-depth manner in order to make an informed recommendation.

**Comment by cmitu** [comment]
> if the logic changes one day (or if there's a but in one of those checks) it's harder to track down and fix.

You're right, they're better extracted to be a separate check (isUiVisible/enabled). I'll take a look.

**Comment by pjft** [comment]
By all means, thanks for looking into it. To be fair, I am under the impression that something similar had been discussed with @zigurana back in the day when he implemented the UI modes, so I would not be surprised if something similar (or to that effect) already exists.

Also, to be double fair, from reading the screensaver code, in that scope you're handling XML directly and not the FileData objects, so you might be better off creating a generic method that receives the UI mode and the file parameters (is kid mode, is visible) and returns something.

Just a thought, didn't mean to make this harder than it needs to be - thank you for addressing this!

**Comment by cmitu** [comment]
> Also, to be double fair, from reading the screensaver code, in that scope you're handling XML directly and not the FileData objects, so you might be better off creating a generic method that receives the UI mode and the file parameters (is kid mode, is visible) and returns something.

Yes, but in this case we tie the intend with the data itself - assuming that only `kidmode` and `hidden` are affecting the visibility :) and not some other flag - like filters. Come to think of it, filters are also not factored in in the screensaver source(s).

Now, the correct way -IMHO - would be to leave the gamelist aside and only operate on the current working list of games within ES (which already has the filters applied - including UI mode restrictions). That would hard break a lot of setups though (see the 2nd forum post) which used a fake game hack to attach videos as screensavers :), but could be easily remedied by implementing a video-from-folder screensaver (similar to how images are used for screensaver).

**Comment by pjft** [comment]
That, in concept, would be the best approach. However, it is my understanding/recollection that performance reasons make it so that navigating the XML turns out to be a lot more performant than navigating and accessing the actual SystemData -> FileData hierarchy.

I'd be wary of making that change, as it can have a meaningful impact on performance as collections grow larger.

I won't object to trying it out and actually measuring the time it takes to both count the nodes and select a new node, logging it to the es_log.txt file using SDL_GetTicks() for before and after, and counting those. I'm happy to run a test build on my 3.8k games collection. 

But, for the sake of simplicity, I would not object to keeping the code as is as well. Your call, really :)

**Comment by cmitu** [comment]
> I'd be wary of making that change, as it can have a meaningful impact on performance as collections grow larger.

That is not my intent for this PR, really, but more of an idea I had. As I said, this would have a broader impact.

> However, it is my understanding/recollection that performance reasons make it so that navigating the XML turns out to be a lot more performant than navigating and accessing the actual SystemData -> FileData hierarchy

That's interesting - do you think this was discussed here in the issue tracker ? I could dig up some old PRs and take look to see if anything was discussed along this line.

**Comment by pjft** [comment]
I don't think I can point you to anything extremely factual (i.e. with tests that specifically answer this question) which to be honest is already a our showing on my part.

There's 
https://github.com/RetroPie/EmulationStation/pull/247

Which downgraded the performance a fair bit when in testing, but it's been almost two years since most of these developments  (video, screensaver, random game selection, filters) were done so to be honest I may just be misremembering things from back then or conflating memories. 

In fairness, if we could initialize the count when loading the gamelists in the first place, that'd probably make it so that the impact would be minimal. But if you'd be keen on exploring it it's probably both easy to test and a better approach all around if it performs well. 

Thanks for asking the right questions though: I also wouldn't have been happy without facts here, and I fail to provide them. 

Thanks for all the work you've been putting into both the forums and ES development!

**Comment by pjft** [comment]
@cmitu as this had been nagging me, I put together a small mock test and actually my recollection was clearly unfounded (in hindsight, as expected).

```
lvl0: 	Counting Videos XML: Start: 252316 - End: 252429 - Total: 113 - Count: 4534

lvl0: 	Counting Videos FileData: Start: 252429 - End: 252439 - Total: 10 - Count: 3798
lvl0: 	Picking Videos: Start Time: 252439 - End: 252488 - Total: 49

lvl0: 	Counting Videos FileData: Start: 261601 - End: 261621 - Total: 20 - Count: 3798
lvl0: 	Picking Videos: Start Time: 261622 - End: 261709 - Total: 87
```

The test branch is here:
https://github.com/pjft/EmulationStation/commit/0adc36f336fa31b2acb98762f45238f7e1c09e7e

The count from FileData is, of course, exact whereas the other is based on what's in the gamelists. In fact, I'm not sure what happens when the random index is higher than the actual number of videos.

As such, I'm more than supportive of changing the "count" method to use FileData rather than XML - happy to do so today before you submit this patch and then you can jus use a method that relies on FileData to check whether it should be visible or not (which probably already exists?).

It will break some of the hacky workarounds for screensavers. I'm not one to be especially keen on supporting unintended behaviors, but I'm aware that that is not ideal, so I'll leave it to your consideration.

Thanks.

**Comment by pjft** [comment]
@cmitu pushed #535 to address these shortcomings.

I did not include your changes though, but happy to discuss if you'd rather have them be done there.

Thank you for raising this and flagging this.

**Comment by cmitu** [comment]
@pjft I'm ok with closing this and adding the small test for empty tag in your PR.

**Comment by cmitu** [comment]
Closing in favor or #535.

**Pull request closed without merging**
