### PR TITLE
gamelists: remove scraped files when removing game

### PR DESCRIPTION
**Pull request by cmitu**
Remove thumbnail, video, image and marquee files for a game when the game file is removed.

### CODE REVIEW

**Comment by cmitu** [comment]
> The challenge with this is that we would benefit from checking if the same resource (video/image/thumbnail) isn't used by any other (loaded?) game

Yes, I can see this check being necessary, when the artwork files are re-used between gamelists. Let's see if we can add such check.

**Comment by cmitu** [comment]
@pjft I added some checks on deletion, to look for duplicate/shared resources in the gamelists loaded. I haven't touched this part of EmulationStation so would appreciate any corrections.

**Comment by pjft** [comment]
Nice - thank you! 

The code looks good, it seems to do what it sets out to do. Wondering if we could just break the cycle the moment all of them are to be kept - honestly unsure if there's much of a performance impact.

Other than that, feel free to squash it and I'll merge it.

Thank you for submitting this!

**Comment by pjft** [comment]
Thank you!

**Pull request merged**
