### PR TITLE
[GRID 8] Enable the grid view for everyone

### PR DESCRIPTION
**Pull request by Koerty**
Beside step 7, all the base features are now included in the grid view.

Once step 7 will be done, the grid will be considered stable, reliable and mature enough, to release a  V1, and so to open the door to everyone using emulationstation-dev, by merging this.

This doesn't mean the development is over, I have big plans for the future of the grid view, but those are just embellishments, all the base features are here.

You can check the wiki to see what may come after the first grid view release.

### CODE REVIEW

**Comment by jrassa** [comment]
@Koerty the only other thing I think is needed before V1 is theme support for `<backgroundColorCenter>` and `<backgroundColorEdge>`.  These were listed in your proposed theme syntax and would be good to have.

**Comment by Koerty** [comment]
@jrassa You are right, I forgot about that.

The "edge" correspond to the NinePatchComponent padding.

I need to take a deep look into the code of the NinePatchComponent to see if it's possible to change its natural padding without breaking it. Right now it have a padding of 32 32, which is way too big, from what I saw on the forum, theme makers would be more likely to use a padding of 16 16 or smaller.

**Comment by Koerty** [comment]
Note for future me : it would also be nice to reimplement a cleaner version of onFocusGained and onFocusLost before the V1 is out, so we only load/update/render the grid of the selected system, because the grid code consume a lot of memory and processing power.

**Comment by jrassa** [comment]
@Koerty Thanks for all the hard work on this and putting up with all my notes and suggestions.  I am going to make an annoucement post on the forums (unless you would prefer to do it) so that we can get a wider base of users testing this out.

**Comment by hex007** [comment]
Will you be doing this only in dev for now? I would suggest not having a release till passes through emulation-dev package.

**Comment by jrassa** [comment]
@hex007 Yes, for now this is only available through the dev package.  I would guess that it will be some time before it makes it to the main ES package.

**Pull request merged**
