### PR TITLE
Utils::FileSystem

### PR DESCRIPTION
**Pull request by tomaz82**
This PR basically does 2 things, but mainly, it doesn't actually do anything to ES, yet... it just prepares ES for a heart, brain and spine transplant.

* it adds everything needed to exterminate the last traces of boost in ES, which is boost::filesystem
* it removes all namespace fs = boost::filesystem, which isn't really needed but helps with the next step in my master plan

The coming pieces after this will be split into multiple PR's due to the shear amount of code that will be touched

### CODE REVIEW

**Comment by joolswills** [comment]
Unless anyone has any objections, I'm going to merge.

**Comment by hex007** [comment]
I am sure @tomaz82  knows what he is doing. Is there any change in compile time by dropping boost as a dependency?

**Comment by error454** [comment]
Is the goal to completely eliminate boost from the project? I ask because during my profiling I noticed that `MetaDataList::get` was next on the list, it looked like an area where `boost:string_ref` might make sense instead of incurring the string create/destroy overhead on every call. Pretty new to this project so am a little out of the loop but would like to come up to speed.

**Comment by tomaz82** [comment]
@error454 My goal is to eliminate boost yes, and whenever something from boost would be useful, I look into making the same functionality available without resorting to actually using boost, like I have with all the existing boost usage so far. This PR doesn't eliminate any boost usage, it only provides all the functions needed to replace what is left of boost.

@hex007 I'm hoping there will be a significant change in compile time, but to be honest, I don't know yet, I have yet to update my own build with everything replaced, mainly due to the sheer amount of code involved to get rid of boost:filesystem::path, since it's nested into everything, everywhere. But It's high on my priority list for the coming days.

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
