### PR TITLE
Improved TextEditComponent

### PR DESCRIPTION
**Pull request by dirk-de-bugger**
This fixes the initial text position (eventually by keeping mScrollOffset.x() at 0 after constructor) and makes it understand more keyboard keys: cursor left/right, home, end, delete.

Don't like the implementation for delete but it works...

Hope this is of some use.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks.

**Comment by joolswills** [comment]
Once the change above is done, please squash it (keep the .gitignore commit separate), and I will merge. thanks.

**Comment by dirk-de-bugger** [comment]
Learned some new git commands.

**Comment by joolswills** [comment]
Thanks. Sorry for delay. Will test / merge asap.

**Comment by joolswills** [comment]
Looking through this code, I wonder if there may be issues with hardcoding keyboard keys - for example for joystick controls that map to keyboard keys. If any of the controls map to cursor left or return it could possibly be problematic.

**Comment by joolswills** [comment]
It may not be an issue, but I'm just wondering for example if say button B is mapped to Return on a keyboard, how this would affect this.

**Comment by dirk-de-bugger** [comment]
My intention is:
A keyboard (and everything pretending to be one) should behave as a keyboard while one is editing. So W, A, S, D stays W, A, S, D. You can exit with ESC, ENTER or 'B' button (this doesn't change).

If not in edit mode, work as mapped. Since you can only start editing as the single action I'd say that ENTER (mapped or not) is a reasonable key to do so. This is so you don't have to reach for the controller/joysick to press 'A' if you want to correct a type or so.

**Comment by joolswills** [comment]
OK. Makes sense. Controllers mapped to keyboards are no use for editing without an OSK anyway, so this seems fine.

**Pull request merged**
