### PR TITLE
Cleaning up a lot of math functions

### PR DESCRIPTION
**Pull request by tomaz82**
Moved some functions from their headers to their respective cpp files, this should improve compile times. ( But so far not really noticeable. )

Moved the lerp stuff from Animation.h to math/Misc.h

Expanded upon math/Misc.h with a couple more standard functions

### CODE REVIEW

**Comment by joolswills** [comment]
Any feedback on this ? I am wondering if it's worth waiting on getting some other commits in first (eg for example from @zigurara) to avoid people having to rebase their changes etc.

**Comment by zigurana** [comment]
I don't mind rebasing, so don't worry about that.
I do have a question though: am I understanding this correctly and is this a way to hide most of the <math> header by only including it in misc.cpp and exposing only a limited selection of its methods in misc.h? 
If so, in future developments, should we only use other (additional) math functions via this mechanism?

**Comment by tomaz82** [comment]
@zigurana Preferably yes :)

**Comment by joolswills** [comment]
thanks.

**Comment by jrassa** [comment]
@tomaz82 It looks like something in this change is breaking my automated windows builds. 

https://ci.appveyor.com/project/jrassa/emulationstation/build/353

**Comment by tomaz82** [comment]
@jrassa Okay, I know what's up with that, I have that fixed in my Visual Studio project, I'll add the same fix to the cmake project, basically it needs to define NOMINMAX since we use our own min and max functions, but I'm at the office right now so I'll fix it once I'm back home.

**Comment by zigurana** [comment]
ok, so what do I need to do to fix this now? Adding a preprocessor definition NOMINMAX to project es-core does not do it. Do I need to add it somewhere else?

**Comment by tomaz82** [comment]
@jrassa @zigurana I'm back home now, gonna investigate what's going on.

**Comment by zigurana** [comment]
Sure no hurries for me, kids are back home, so my play-time is over ;-) I'll continue tonight.

**Comment by tomaz82** [comment]
@jrassa @zigurana 

https://github.com/RetroPie/EmulationStation/pull/309

**Pull request merged**
