### PR TITLE
Skip hidden *nix files & folders when populating gamelists.

### LINKED ISSUE #68: Do not show *nix hidden files (. prefix)
It seems ES will display hidden files in the gamelist, causing confusion for at least one user: https://retropie.org.uk/forum/topic/4863/noob-looking-for-help-change-emulators-graphics-and-get-things-working/14. i've seen it on my system also.

it looks like it only cares that the extension is correct. eg, `._Aladdin.smc` would be displayed in the SNES gamelist.

i think the only reason you would have hidden files in your rom folders would be a failed transfer (i believe i encountered it when a transfer via OSX/samba failed), which wouldn't be a valid file, so safe to hide I think.

### PR DESCRIPTION
**Pull request by dankcushions**
Fixes #68, which has come up various times on the forum and reddit.

This is the first time I have touched C++ so please review my code/style :) I adapted a function I found from stack-overflow. I have tested at my end and it seems to compile and work fine.

### CODE REVIEW

**Comment by dankcushions** [comment]
Conflict.. will fix and retest.

**Comment by joolswills** [comment]
btw - rather than merging from master to get a merge commit, you can `git rebase` over master, which is cleaner. You should be able to rebase and squash it though to clean up the branch.

Please see https://github.com/RetroPie/EmulationStation/pull/103#issuecomment-286188407 as I don't want to implement the feature without having it optional. thanks.

**Comment by joolswills** [comment]
Also if using someone else's function, need to be careful of the licence. We may not be able just to include it, if the licence is is under is incompatible with the ES licence.

**Comment by dankcushions** [comment]
squashed everything :)

[all stackoverflow snippets are covered under CC](https://stackoverflow.com/help/licensing). i technically should attribute one line, though.

> I don't want to implement the feature without having it optional

i can't imagine the use case, but in any case someone else will have to do it as I have no development environment in OSX to add anything more sophisticated.

**Comment by joolswills** [comment]
I don't believe that licence is compatible - as it would mean we have to distribute the code with the same licence.

> If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original. 

I would like it optional as that is the current behaviour. There may not be a use case, but I know from previous experience when we change default behaviour on RetroPie things, people have a problem with it. Most tools that show file/directory contents have options to show/hide hidden files so I think it makes sense to include it.

Cheers.

**Comment by dankcushions** [comment]
there is another PR so I leave it to them.

**Pull request closed without merging**
