### PR TITLE
Jump to letter moves to first occurrence of the letter

### PR DESCRIPTION
**Pull request by Viitis**
Jump to letter no longer moves to a random match.

### CODE REVIEW

**Comment by jrassa** [comment]
I think this is great idea, but it could be done more efficiently by extending the existing binary search instead of adding on a sequential search.

Something like the following:
<pre>
while(max >= min)
{
	mid = ((max - min) / 2) + min;

	// game somehow has no first character to check
	if(files.at(mid)->getName().empty())
		continue;

	char checkLetter = toupper(files.at(mid)->getName()[0]);

	if(checkLetter < letter)
		min = mid + 1;
	else if((checkLetter > letter) <b>|| (letter == toupper(files.at(mid - 1)->getName()[0])))</b>
		max = mid - 1;
	else
		break; //exact match found
}
</pre>

**Comment by Viitis** [comment]
Yes, binary search is better. I updated the code use that.

**Comment by joolswills** [comment]
I will test / merge as soon as I can. Thanks.

**Comment by joolswills** [comment]
Just fyi, there is a whitespace fix and some new whitespace errors in the PR. Please can you fix those (whitespace can be fixed in separate commit if needed), and squash and I will merge.

**Comment by joolswills** [comment]
I manually rebased this without the whitespace changes.

**Comment by joolswills** [comment]
actually, I thought i did but I must have accidentally reset my changes. Oh well. It's merged now anyway (with the whitespace fixes).

**Pull request closed without merging**
