### PR TITLE
Add ability to specify sound when scrolling systems on the system view

### PR DESCRIPTION
**Pull request by robertybob**
All credit to @fieldofcows , this is his commit https://github.com/fieldofcows/EmulationStation/commit/3c5bd864c07e45ab4cc2c43fc5b0c3a851492197 which has been tested as working in the Windows environment and so needs testing on a Raspi. 

I am still new to (shit at) Github and I don't know how to pull the commit directly from @fieldofcows branch to here, so apologies if that's what I am meant to do (i.e. that is the done thing). Will close this PR if that is the case.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks - but I would prefer if he submits his own changes, not only for the correct attribution in the code, but also in case there are additional details needed. He may well be waiting on this one for a reason etc.

**Comment by robertybob** [comment]
Fair enough, I know he's not been very active lately; hopefully he'll be in a position soon to submit it himself.

**Comment by fieldofcows** [comment]
Hi, yes. I am still around - just taking a forced ES break because I've got so many other things to work on. I need to catch up with some of my ES tasks and I'll go back, tidy up and submit PRs for anything is deemed worthy (including this one). 

Thanks for your patience :)

**Comment by robertybob** [comment]
@fieldofcows Still waiting patiently ;)

**Comment by robertybob** [comment]
Hey @fieldofcows , are you looking to come back to ES development soon?

**Pull request closed without merging**
