### PR TITLE
CEC Support

### PR DESCRIPTION
**Pull request by tomaz82**
Implemented optional CEC support.
If CMake can't find libcec.so then it will just build without CEC support.
It's configured the same way as a keyboard.
The FindlibCEC.cmake might be wrong, first time I've written one of those, I based it on the one for FreeImage ( I think ).

Have tested this on my rpi3 with my Sharp TV and it worked just fine for me.

I'm happy to answer any questions.

### CODE REVIEW

**Comment by pjft** [comment]
Thanks. What exactly does this consist of? Allowing a remote control to control ES? Turning the TV on and off via HDMI? There's quite a few things that CEC can allow for, I believe, hence the question. 

If it's the controller bit, how does this work with emulators? I take it that the controller after its defined will trigger the emulator controller configuration script. Can this lead to an emulator launching but then not controlling it with this remote? Can someone be locked inside an emulator because further controllers only register as #2, #3 and above, and so hotkey+start won't work as the majority of TV remote controls don't really support simultaneous presses?

Just a few questions:)

Thanks!

**Comment by tomaz82** [comment]
Good questions, I should have explained that, this turns the TV remote into a controller, but only for ES, once an emulator launches you're back to using keyboard /gamepad / monkey wrench / whatever.

Not tested how this affects gamepads, I'm gonna assume that it will work since the TV remote wont even work in the emulator, like, at all.

**Comment by PokeEngineer** [comment]
Huh, cool!

**Comment by joolswills** [comment]
Nice one. Quite a few have asked for this. I shall merge tomorrow, in case anyone has comments. Cheers

**Comment by pjft** [comment]
@joolswills Do we need to do anything on the RetroPie-Setup front in regards to the controller configuration not to try to set up the RetroArch controls to the libCEC configured device? 

[You can tell I have no idea about how this is meant to work by the way I'm phrasing things, but I hope it still helps].

**Comment by joolswills** [comment]
@pjft we might do. I've not checked yet.

**Comment by psyke83** [comment]
I was going to suggest adding new deps to the emulationstation-dev script, but I notice that stretch will have issues with building this:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcec-dev : Depends: libcec4 (= 4.0.1+dfsg1-1+rpi1) but 4.0.2.3~stretch is to be installed
E: Unable to correct problems, you have held broken packages.
```

Ignoring libcec-dev, I tried installing libcec4-dev and libp8-platform-dev, but:

```
[  5%] Building CXX object es-core/CMakeFiles/es-core.dir/src/GuiComponent.cpp.o
/home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/CECInput.cpp: In constructor ‘CECInput::CECInput()’:
/home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/CECInput.cpp:73:12: error: ‘CEC::ICECCallbacks {aka struct CEC::ICECCallbacks}’ has no member named ‘CBCecAlert’
  callbacks.CBCecAlert      = &onAlert;
            ^~~~~~~~~~
/home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/CECInput.cpp:74:12: error: ‘CEC::ICECCallbacks {aka struct CEC::ICECCallbacks}’ has no member named ‘CBCecCommand’
  callbacks.CBCecCommand    = &onCommand;
            ^~~~~~~~~~~~
/home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/CECInput.cpp:75:12: error: ‘CEC::ICECCallbacks {aka struct CEC::ICECCallbacks}’ has no member named ‘CBCecKeyPress’; did you mean ‘keyPress’?
  callbacks.CBCecKeyPress   = &onKeyPress;
            ^~~~~~~~~~~~~
/home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/CECInput.cpp:76:12: error: ‘CEC::ICECCallbacks {aka struct CEC::ICECCallbacks}’ has no member named ‘CBCecLogMessage’; did you mean ‘logMessage’?
  callbacks.CBCecLogMessage = &onLogMessage;
            ^~~~~~~~~~~~~~~
/home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/CECInput.cpp:87:32: error: ‘class CEC::ICECAdapter’ has no member named ‘FindAdapters’; did you mean ‘PingAdapter’?
  int8_t numAdapters = mlibCEC->FindAdapters(adapters, 10, nullptr);
                                ^~~~~~~~~~~~
es-core/CMakeFiles/es-core.dir/build.make:86: recipe for target 'es-core/CMakeFiles/es-core.dir/src/CECInput.cpp.o' failed
make[2]: *** [es-core/CMakeFiles/es-core.dir/src/CECInput.cpp.o] Error 1
```

**Pull request merged**
