### PR TITLE
Add pragma once and ifndef header guards to all headers

### PR DESCRIPTION
**Pull request by tomaz82**
Went through all headers in es-app and es-core and made sure each and everyone has both #pragma once and #ifndef XXXX.

There was a big mixture between these two, and even quite a few that had neither, so this cleans up all that.

This should not conflict with any waiting PRs since it only touches all headers on the first 3 lines, and the very last line.

This is PR one in a series of two, if this is accepted and merged then the next one will be a huge include cleanup, I've done a few minor tests and with proper cleanup of header includes we can potentially cut compile time in half, if not even more, this is an estimate on my computer, need to do further testing on the PI.

### CODE REVIEW

**Comment by zigurana** [comment]
Man, you really are on a roll! This is good work, not flashy or exciting, but useful and needed!

**Comment by joolswills** [comment]
Isn't the pragma once enough for all modern compilers without the ifndef preprocessor guards?

**Comment by tomaz82** [comment]
@joolswills Yes and no, there is never gonna be an end result of the debate regarding pragma once or ifndef, both sides has valid points on why too choose either one, bottom line is, using both makes you 99.9% safe. And ES as it was used both, what appeared to be randomly, now it's consistent through the entire source.

**Comment by joolswills** [comment]
Thanks. Sounds reasonable then.

**Pull request merged**
