### PR TITLE
Adding metadata to folders

### PR DESCRIPTION
**Pull request by pjft**
Hi. It's my second attempt at my first PR. I believe I squashed the commits.

I have no idea why the commit is signed by two authors with my username.

For people who use subfolders in their gamelist, we currently provided a sub-optimal experience:

Allowed to show images, but not videos;
Allowed for editing, but the GUI would show up incomplete;
Did not show some of the metadata, if it existed on the gamelist (i.e. number of players, stars, etc), especially useful for multi-disc games under the same folder, or even for category groupings.
This small change enables video playback for folders, when selected, and also opens up a lot more of the metadata to the folders (in fact, all but the "Last Played" date, and "Play Count").

Hope it suits.

Thanks.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks - Does anyone have time to do some testing on this ?

**Comment by Darknior** [comment]
It is a great stuff i dream to use for my project :)
If i can help to try it, tell it to me @joolswills ;)

**Comment by pjft** [comment]
Hi all,

Thanks for the interest in this.

Just two comments:
- There were some tests done by TMNTurtlguy in the forums: https://retropie.org.uk/forum/topic/8942/video-preview-for-roms-in-folders/13 . I specced out the tests, themes and variants, in case you want to read up on them. I also tested a bit myself afterwards, but obviously I am biased :)
- I noticed recently that we have always shown the "Delete" option for games and folders in the Metadata Editor, but it obviously crashes ES for folders. As I'm not keen on allowing someone by mistake to delete a folder and all its content, I have hidden that button when it's a folder, and will squash that change into the PR's commits, unless there's any significant objection, just so folders are handled properly now.

Let me know your thoughts on squashing that change. I'll add a second commit now, and if you want me to squash it, I'm more than happy to.

**Comment by joolswills** [comment]
Thanks

you can leave the disable delete button commit separate if you like but either way.

**Comment by pjft** [comment]
Huh. Apparently this updates the PR with all the commits in the branch.

It's a small change, happy to squash it if helps, no big deal. Just let me know.

Thanks.

**Comment by joolswills** [comment]
>Huh. Apparently this updates the PR with all the commits in the branch.

Not sure what you mean ?

The reason the first commit looks like two people is you have a different commit email address in there. You might want to rebase and fix that.

Note the last commit has a bit of trailing whitespace in it also.

**Comment by joolswills** [comment]
Seems to work fine from my testing. thanks.

**Comment by pjft** [comment]
Sorry - the note about this updating the PR with all the commits in the branch is because I wasn't aware to GitHub. I sort of had the expectation that a PR was static, and any new changes I'd need to explicitly add to PR. I was surprised that it had updated the PR automatically the moment I committed something new.

Now I (think I?) understand that a PR is actually just an intent to merge changes between two branches in general, and not specific to a point in time. Just that.

I *think* I fixed the trailing whitespace in the commit now.

As for the two people, I hope I've tackled it now. Thanks for the pointer!

**Comment by zigurana** [comment]
@pjft: The main development philosophy for Git is to create many branches often, and let each branch be dedicated to introduce a singe feature only. So now if you file a PR, and update the branch afterwards, it will update the PR automatically. 
This is fine if you are still working on the same thing, not so much if you have starting something new.

Note, I just realized this myself, so I thought to let you know as well.

**Comment by joolswills** [comment]
Thanks.

**Pull request merged**
