### PR TITLE
Send a suspend state to HDMI for Rpi if screensaver is set to 'black'

### PR DESCRIPTION
**Pull request by bb2k**
this will shut the backlight of lcd to off when the screensaver starts and then back to on after the screensaver exit.

### CODE REVIEW

**Comment by pjft** [comment]
Thanks!

A question on what this actually does: some screen's "blank/no signal" state is a blue screen. Will this, in those cases, make the screen turn blue?

**Comment by bb2k** [comment]
the screen goes to suspend mode 
for me my screen displais a no signal -> then turns off (orange led for me)

**Comment by bb2k** [comment]
argl ! The screen does not seems to get back to life if the screensaver has been activated with the 'select' button. Seems OK if the screensaver is started automatically

**Comment by hex007** [comment]
Does this affect composite signal?

**Comment by bb2k** [comment]
i don't think so

**Comment by bb2k** [comment]
i close the pull request. It 's really too late. pushing the 'select' button make the emulationstation in unstablestate

**Comment by pjft** [comment]
Oh. Well, you can keep it open if you're working on it, and then update
when it's ready. I think it is a good addition, as long as it doesn't turn
things blue in some types of TV (which, if it would be the case, we'd
probably need to explore how to address it - either not pursue it or making
it an option).

Thanks!

**Comment by bb2k** [comment]
i'll work on it and reopen the pull request

**Comment by bb2k** [comment]
After some work i can reopen this PR.
The screen now is back to live is the screensaver is forced =)

**Comment by pjft** [comment]
Great! 

A question: is this using CEC to turn off and on the display? 

Would that be something you'd consider?

**Comment by hex007** [comment]
There are indentation mistakes in the code btw

**Comment by bb2k** [comment]
Sorry for that hex007, this is fixed (hope did not missed any)

**Comment by bb2k** [comment]
@pjft I'll have a look at this but as you can see in the following link the documentation in incomplete :-(
http://elinux.org/Raspberry_Pi_VideoCore_APIs#vc_cec_.2A

**Comment by pjft** [comment]
Ah, of course. Well, if it isn't, it isn't, not a problem. No need to add scope creep to this feature then - I was just asking out of curiosity. :)

I'd like to test this for the blue screen behavior on some monitors. I know it might be a pain but would you be able to provide a compiled binary as I have no access to a development environment at the moment and sshing through a phone for compiling on the pi is sub optimal? :)

If not I'll try to get something sorted in the coming days. Thanks.

**Comment by bb2k** [comment]
here is a link to a rasberrypi3 compiled binary : https://bb2k.org/emulationstation/emulationstation

**Comment by pjft** [comment]
Thanks.

I tried it out and it works as intended. It does show a blue screen on my
LCD rather than black, but in my case I have an option to turn that off.
Some Dell LCD screens I used to have seemed to just pop up a box with "no
signal detected", so I'm not sure what to expect there. There was also a
noticeable delay resuming from the screensaver state which was the LCD
screen getting the signal and starting to render the image, unlike in the
past where it was instantaneous. Just a note on that.

Still, I'm more than supportive that this becomes either an option or a new
screensaver type (screen off), though I'm not sure about it being the
default behavior for black because of what I mentioned.

Would certainly love to hear everybody else's thoughts on this.

Thanks for putting this together!

**Comment by bb2k** [comment]
You re right, setting it as an option is the best way. It can avoid some problems with some hardware settings. I'll work on that.

**Comment by pjft** [comment]
Either that or just make it a different screensaver option. I think it might be more elegant than two levels of indirection (need to set black, and then an option that only works when black is set). 

But either way will certainly be helpful. I might look into libCEC at a later stage then to completely shut down the LCD :)

**Comment by hex007** [comment]
I agree. Another screensaver would work.

**Comment by bb2k** [comment]
I close this PR since the code will be différent

**Pull request closed without merging**
