### PR TITLE
Remove all resources from the code

### PR DESCRIPTION
**Pull request by tomaz82**
This removes all the builtin res2h resources from the source code. The default resource files will be in /etc/emulationstation/resources ( added by a coming PR in RetroPie-Setup ) and can be overridden by placing resources in /%home%/.emulationstation/resources

### CODE REVIEW

**Comment by jrassa** [comment]
@tomaz82 I understand the desire to no longer has the resources be converted via res2h and compiled, but shouldn't the actually resource files still be part of the code base?  Where are they going to live now?  If someone was to just checkout the code and build it, the required resources wouldn't be available.

**Comment by pjft** [comment]
I tend to agree. Decoupling those means that this project is no longer standalone.

**Comment by zigurana** [comment]
Is there an performance consequence of this proposed change?

**Comment by HerbFargus** [comment]
One appeal to it may be a simpler method of gamepad localisation (eg having options for Xbox, PlayStation controllers etc) though I can understand the concern with breakage

**Comment by pjft** [comment]
I imagine we can achieve that without decoupling the resources and just allowing for a specific folder to override the default ones. I think the use case for overriding is there, I'm not fully sure why decoupling is a must have. I kind of enjoy the portability of the single binary myself.

**Comment by tomaz82** [comment]
We could keep the resources with the source code, but not res2h them, or we could keep them res2h and allow overriding them. There are many possibilities.

**Comment by tomaz82** [comment]
After discussing with @jrassa, how does everyone feel about having the resource folder in the root folder of es source, and have es check for currentWorkDir/resources as a final fallback, if it fails to find them in etc and %home%?

**Comment by joolswills** [comment]
May have been a miscommunication from me. 

I am up for the graphics being removed from the code, but want to keep them part of this repository.

Ideally we should sort out the cmake install so they automatically get installed.

/etc/ is not the ideal location, but as themes were already there it seemed ok. Probably themes should not be stored in /etc/ really, but I don't have the will to move everything around in RetroPie.

**Comment by joolswills** [comment]
regarding resources locations, having the current directory checked is a good idea.

**Comment by tomaz82** [comment]
I think etc is the perfect place for the default ones, and let %home% override, imho

**Comment by tomaz82** [comment]
Order would be, %home%, etc, cwd

**Comment by joolswills** [comment]
sounds good - thanks!

**Comment by tomaz82** [comment]
I think I addressed the concerns, if not then let me know.

It now still has the resource in this repo
It first looks for the files in these folders:
/etc/emulationstation/resources/
/home/%user%/.emulationstation/resources/
/%current_working_directory%/resources/

**Comment by Koerty** [comment]
As zigurana asked, what is the impact on performances ? Is it noticeable ?

**Comment by joolswills** [comment]
There won't be any noticeable overhead vs the rom scanning etc.

Please do not merge as I will merge when I have tested/sorted out the RetroPie-Setup part.

**Comment by joolswills** [comment]
I'm now thinking the default resources would be best kept in the `/opt/retropie/supplementary/emulationstation` folder. Since they need to be installed there anyway initially (due to the way we package stuff on retropie), there doesn't seem any point to copy them to /etc/

**Comment by tomaz82** [comment]
@joolswills sounds good to me, let me know when you have decided, and I'll change the code accordingly, just out of curiosity, why is there even anything in etc/es? wouldnt the es_systems.cfg and themes live much more happily in opt?

**Comment by hex007** [comment]
Would this make it difficult for non retropie setups like desktop distros?

**Comment by tomaz82** [comment]
@hex007 No, you just drop the resources folder into %home%/emulationstation, I run a portable Win64 setup myself for all my testings ( before I even test anything on the Pi )

**Comment by joolswills** [comment]
tomas - I would like to keep resources in the same folder as the executable. However the code would need to be changed to look for the location of the exe, rather than using the current directory as we don't `cd` to the ES folder before launching.

If this is not possible (There is no crossplatform way afaik, but its possible to do a separate bit of code for windows/linux), then I will just use /etc/

thanks.

**Comment by tomaz82** [comment]
Updated to check in homepath, then executable path, and last current working directory.
On Pi the defaults ones will be in executable path ( one RetroPie-Setup is updated ) and can be overruled with custom ones in %home%/.emulationstation/
On most other systems the same approach can be used.

**Comment by joolswills** [comment]
tested and working great - thanks.

**Pull request merged**
