### PR TITLE
Fix jagged font in games list

### LINKED ISSUE #538: Jagged Font in Gamelist Basic View
This relates to the jagged font bug that has been in EmulationStation since ES 2.0 was released in July 2014. There remains an [open ticket](https://github.com/Aloshi/EmulationStation/issues/176) at Aloshi's Github page. The issue was discussed recently at the [forum](https://retropie.org.uk/forum/topic/21426/distorted-font-font-not-rendering-correctly-in-certain-es-theme).

The bug is straightforward to replicate:- Select the vanilla Carbon theme that comes, by default, in the RetroPie image and change the Gamelist View Style to `Basic` in UI Settings.

I noticed it again recently when I was developing a custom theme for my Picade build. I believe the bug occurs when the `<alignment>` tag in the `<gamelist>` section of the theme XML is set to `center`, as it is in the [Carbon](https://github.com/RetroPie/es-theme-carbon/blob/master/carbon.xml#L79) theme as well as others.

Here are my findings using the CRT Centered theme by editing [these lines](https://github.com/anthonycaccese/es-theme-crt-centered/blob/master/_inc/templates/4x3.xml#L64) in the theme XML:

**Alignment `center`**
Theme XML excerpt
```
     <textlist name="gamelist">
         <pos>0.05 0.575</pos>
         <size>0.9 0.3277777777777778</size>
         <alignment>center</alignment>
      </textlist>
```
centered

**Alignment `left` and gamelist moved towards middle with `<pos>`**
Theme XML excerpt
```
      <textlist name="gamelist">
         <pos>0.425 0.575</pos>
         <size>0.9 0.3277777777777778</size>
         <alignment>left</alignment>
      </textlist>
```
left

Setting the `<alignment>` tag to `left` instead of `center`, the text can occupy a similar central position without jagged edges.

### PR DESCRIPTION
**Pull request by pjft**
This should fix #538 .

### CODE REVIEW

**Comment by cmitu** [comment]
@pjft looks better with the fix.

Gamelist

**Comment by tomaz82** [comment]
This got me thinking, should probably make a special version of Renderer::setMatrix that forces the translation part to integer, that would fix all text, in every case. And would allow all calculations to always be done as floats, so only the very final end result is clamped

**Comment by pjft** [comment]
Thanks, I'll try that out.

In that case, why not call it inside setMatrix? I'm not especially familiar with that pipeline, so just checking.

**Comment by tomaz82** [comment]
Because setMatrix is used by more than just text rendering, also, even with all these fixes, it can still break if the matrix has scaling...

**Pull request merged**
