### PR TITLE
Modernise SDL2 CMake find module

### PR DESCRIPTION
**Pull request by hhromic**
* imported from: https://gitlab.com/aminosbh/sdl2-cmake-modules
* has support for imported targets (not currently used by ES but it should!)
* also use correct includes/libraries variable names for SDL2

@cmitu already tested this newer module on a setup with a `/usr/include/<triplet>` layout and I also just tested a full build of EmulationStation on Raspbian Buster (RetroPie weekly). I also have tested it in another project (Solarus) in both Windows and Linux (Raspbian and other distros). So I'm confident it should be able to find SDL2 in all of our supported environments.

EDIT: Forgot to mention that I also included my [one-line fix](https://gitlab.com/aminosbh/sdl2-cmake-modules/-/merge_requests/2) for a name-mismatch warning in CMake >= 3.17.

Follow up on #651

### CODE REVIEW

**Comment by cmitu** [comment]
Seems to work fine on Raspbian Stretch.

**Comment by joolswills** [comment]
Although it's ok without this now due to upstream packaging sdl2 changes, it's probably a good idea to include it anyway. I don't particularly like the implementation, but it's better than our existing one. 

Let me know if anyone has an issue with this or I will merge in the next day or two. Thanks.

**Comment by joolswills** [comment]
Sorry for the 1+ year wait.

**Comment by hhromic** [comment]
> Sorry for the 1+ year wait.

Was not really _waiting_ :D I also kind of forgot until recently about this PR hehe.
Better late than never anyway! And hope it is useful. Cheers!

**Pull request merged**
