### PR TITLE
WIP Game list views metadata refactoring

### PR DESCRIPTION
**Pull request by Koerty**
EDIT : Never mind all of this, the proposed architecture in this message is way too much complicated for what we are trying to do here.

### CODE REVIEW

**Comment by Koerty** [comment]
@pjft @jrassa This is why I closed #410

**Comment by jrassa** [comment]
My first quick impression is that this is going to add a lot of code and complexity.  You have already taken on a large task in implementing grid view and I would caution against tying these 2 tasks together (as you seem to want to do by closing #410 in lieu of this).

So there are 2 separate problems that this is trying to solve.  The first is the duplication of code between GamelistViews and the second is the hacky way of allowing themes to hide unwanted metadata elements.

The later could potentially solved with a much simpler solution of having the components having a visibility option that would be used to determine if the component should be rendered.  This could be be set either explicitly in themes or `<visibility>false</visibility>` or we could infer visibility based on if the any of other theme options are specified for the component.

As for the former, I have been thinking about this lately.  One thought I had was to flip around the inheritance structure of the GameListViews.

Current class hierarchy:
* ISimpleGameListView (adds extras, background, header image)
  * BasicGameListView (adds TextListComponent)
    * DetailedGameListView (adds additional metadata) 
    * VideoGameListView (adds video and marquee)
    * GridGameListView (swaps TextListComponent for ImageGridComponent)

Possible new hierarchy:
* ISimpleGameListView
  * BasicGameListView
  * IDetailedGameListView (mList is not defined, added by subclasses)
    * DetailedGameListView (mList == ImageGridComponent)
      * VideoGameListView 
    * GridGameListView (mList == ImageGridComponent)

Possible new hierarchy:
* ISimpleGameListView
  * BasicGameListView
  * DetailedGameListView (mList is themable)
    * VideoGameListView (mList is themable)

One possible downside to the the last option is that it would require grid specific themes.  You couldn't have a theme that supports a traditional text list and an grid.

The upside is that if someone ever creates an additional IList implementation (like a wheel style image list, that has been discussed some on the the forums) it wouldn't require creating additional views.

**Comment by pjft** [comment]
I tend to agree with this view as well. Not that refactoring these isn't worthwhile, but mixing the two efforts will mostly only add difficulties in moving forward with the feature delivery and reviews. 

In specific, a refactoring effort usually carries a degree of risk in terms of affecting current working parts of the code. I'd rather isolate their impact for the sake of ease of review and tracing any issues.

**Comment by Koerty** [comment]
In current implementation, GridGameListView inherit directly from ISimpleGameListView, not from BasicGameListView.

In your first proposition, all the code related to the TextList will be both implemented in the Basic and in the Detailed view. All the code related to base metadata and to the video will be duplicated, from the detailed view to the grid view, and from the video view to the grid view, respectively.

In your second proposition, if the List can be either an grid or a textlist, why not push it further ?

My bad I didn't wrote it here, but the goal would be to have this class hierarchy for the game list view : 
- IGameListView
  - GameListView

That way we would create one unique game list view, the theme will be able to completely customize it, by adding one way of taking user input (either a TextList or Grid) and then all the metadata stuff he want, and only what he want. The theme then won't have to provide support for 3 or 4 different views like it is the case now. If the theme maker still want to, he can still provide 3 different theme with a suffix "grid-" "video-" or "basic-" if he want to.

The goal in this PR, is to do a first step, by moving all the metadata stuff out of the game list view. Sure, this may complexify a bit the code related to metadata, depending on how it is done, but it will **greatly** reduce the complexity of the code of game list views at the end.

Maybe I pushed it too far by using templates and stuff like that. Actually we should be able to have **only one** class "GameListViewExtra" containing only this : 
```
std::string mName;
GuiComponent mComponent;

GameListViewExtra(Window* window, GuiComponent component, std::string name);
void update(int deltaTime);
void updateInfo(FileData* file);
GuiComponent getComponent();
```
**If** we move all the theming stuff to the factory. By that I mean the factory will, for the rating element for example : Instantiate the RatingComponent, give it default values, apply the theme on it, and then create the GameListViewExtra by passing the RatingComponent to its constructor.

**Comment by pjft** [comment]
Just to make it clear, I'm all up for refactoring and re-architecting these, but I'd strongly recommend that it's done after the Grid View is finished.

**Comment by Koerty** [comment]
What do you call finished ? Because the V1 of the grid view add just one extra metadata, the game name, but next versions of the grid view will also include the metadata stuff from the video view.

If it's just a matter of time, once this first step is done, the next one will be pretty straight forward.

If it's so they are not "linked" together, as @jrassa said, then that mean this won't come anytime soon, as I have many ideas of improvements for the grid view after the V1 is released. The main problem for me is many of this improvements will require me to duplicate code between the views, so I wanted to make it clean first.

**Comment by pjft** [comment]
I'll leave the more specific recommendation for @jrassa as he has more informed opinions on this specific part of the code. 

If the grid view code is "finished" for now - meaning it's feature complete as you wanted it to be - then I don't oppose starting this at this stage, though being a more critical change it may certainly take some more time to see the light of the day. Others will have some thoughts on it as well, so it's a good, meaty endeavor. See some other refactoring work in current PRs and their age. 

That being said, I'd probably not merge this until v1 is fully stable - meaning it has been put through a fair bit of themes and users in the forums to iron out potential bugs that may affect the end architecture decisions you're going for. Just not to conflate potential issues that may arise, just that. 

Well done!

**Comment by Koerty** [comment]
Just a note for you, while waiting @jrassa point of view : The grid view V1 isn't finished, it miss 4 features (3 really small ones, 1 big).

You can see it here : https://github.com/RetroPie/EmulationStation/wiki/Gridview-Roadmap-and-FAQ#roadmap

You can see what's missing for the V1 in the roadmap, and what I badly named "unordered extra feature" for future improvements (after the V1), although that list isn't complete, I need to update it but I'm not at home atm so I don't have my todo list under the eyes.

**Comment by jrassa** [comment]
@Koerty per the roadmap, one of the features listed is
>Add a new metadata label and value for the grid view : game title

You originally implemented that via #410.  You then closed it in lieu of this PR.  If this PR is how you intend to address that feature, that how is this PR not typed to the completion of V1 of the grid view.  Obviously you are free to work on things as you wish, but I just want you to understand that the changes you are suggesting here probably going to take a lot of time and receive a lot more scrutiny then the grid view has so far.

I was simply suggesting to focus on one major effort at a time.

As for my other comments, you said that you created this PR to open up discussion.  I was simply sharing my thoughts on alternative approaches that I have been considering to address some of the same issues.  While duplicate code is not great, I am not sure that replacing it with a whole bunch of new code to essentially do the same thing is really any better.

**Comment by Koerty** [comment]
@jrassa Sure, I just wanted to know if both of you suggested to hold this until the "md_name" is added for the V1, or until all the other elements are added in the future. I don't know if it look so, but I'm carefully listening to your advices, that's why I will reopen #410 and consider doing the same for the others metadata.

I don't think that reorganizing the game list views hierarchy is a good strategy, if we do this big refactoring, then we better do it completely by merging all the views into a single one.

I feel like the way different type of views are handled is wrong. A theme should only define one system view and one game view, because that's **one** theme so it provide **one** way to display the informations.

If then, the theme want to provide alternative, the theme maker is free to distribute alternate versions of his theme.

But forcing a theme to always support the 4 different game list view types, even if it doesn't want to, this is just wrong.

**Comment by jrassa** [comment]
> @jrassa Sure, I just wanted to know if both of you suggested to hold this until the "md_name" is added for the V1, or until all the other elements are added in the future.

My suggestion would be to hold this until V1 is complete.

> I feel like the way different type of views are handled is wrong. A theme should only define one system view and one game view, because that's one theme so it provide one way to display the informations to the user.

This would be a big change to how ES works and I am not sure if it would be accepted.  I certainly wouldn't feel comfortable accepting it without running getting input from jools and the rest of the RetroPie devs.  A change that would break all existing themes would be a tough sell.

> If then, the theme want to provide alternative, the theme maker is free to distribute alternate versions of his theme.

Interestingly, the [previous effort](https://retropie.org.uk/forum/topic/11122/testers-wanted-gamelistview-theming-refactoring/) to implement something like this, went in the complete opposite direction.  Zigurana intended to allow a single theme to define unlimited different views.  Part of the intention behind that was to prevent theme makers from having to create and maintain alternate versions.

**Comment by Koerty** [comment]
> My suggestion would be to hold this until V1 is complete.

I understood your concern and will reopen PR 410. I'm just waiting for my 3 others PR to get reviewed, idk if you noticed but I'm trying not to open more than 3~4 PR at a time, so I don't have to rebase too much and also so I don't feel like I'm overwhelming you with all that change requests ;)

I already said it a couple time now, but thanks for your dedication to reviewing my PR and for all your relevant comments, I'm carefully listening to them, even if I don't know if I look like I do tho.

> This would be a big change to how ES works and I am not sure if it would be accepted. I certainly wouldn't feel comfortable accepting it without running getting input from jools and the rest of the RetroPie devs. A change that would break all existing themes would be a tough sell.

Sure, I understand that, that's part of why I wanted to reopen this discussion.

> Interestingly, the previous effort to implement something like this, went in the complete opposite direction. Zigurana intended to allow a single theme to define unlimited different views. Part of the intention behind that was to prevent theme makers from having to create and maintain alternate versions.

I completely forgot about this thread on the forum despite having answered to it. This sound like a fair point. Basically, once I will have my single modular game list view, which dynamically instantiate metadata elements, I "just" need to also add the possibility to dynamically instantiate new game list views to the ViewController. Like if the theme don't support grid view yet, then the "grid" option will not show up in "game list view style" setting, that sound good to me. That would also mean the "dynamic" option would disappear from "game list view style". I think dynamically instantiating new game list views in the ViewController shouldn't be that hard, the most annoying part will be to dynamically fill the "game list view style" option in the menu, that would mean either pre-parsing the theme as soon as the user select it, or pre-parsing all the theme when the user open this menu. I will take a deeper look into this in the following days.

Should we do like for the grid view ? I update this branch until I have a complete solution, so you and others can try it out and give first inputs, and then when it will be stable and everyone agreed with current implementation, I split it in smaller pieces and ship them to you one by one ?

Note that this is a second and parallel task, finishing the grid view is of course my priority (at least until we have the V1 + maybe some extra features). This 2 tasks shouldn't conflict too much with each others anyway, as most of the grid view modifications are done in the ImageGridComponent and GridTileComponent classes, the GridGameListView class itself isn't going to change much over the time.

**Comment by Koerty** [comment]
I'm closing this PR as I have other priorities and don't want to keep this PR open without any update.

**Pull request closed without merging**
