### PR TITLE
macOS and Clang support

### PR DESCRIPTION
**Pull request by korreckj328**
Added features needed to compile for macOS, made changes to allow compilation with Clang instead of GCC or MSVC.

### CODE REVIEW

**Comment by tomaz82** [comment]
This needs to be cleaned up due to the mixture of tabs and/or spaces for indenting ( should be tabs ). After that I'll look at this PR again.

**Comment by jrassa** [comment]
It would also be helpful to update [README.md](https://github.com/RetroPie/EmulationStation#building) to add some basic instructions for building for macOS

**Comment by korreckj328** [comment]
Thanks guys, I’ll fix up the spaces / tabs issue when I get a chance and add a bit to the readme.  Let me know any other suggestions as this is the first time I’ve tried adding to or porting a project.

**Comment by tomaz82** [comment]
This will not be merged in it's current state, this seems to be 99% just code formatting for no reason.

**Comment by joolswills** [comment]
Agreed. I'm going to close I think.

**Pull request closed without merging**
