### PR TITLE
[Suggestion] Replace boost::locale with std::locale

### PR DESCRIPTION
**Pull request by tomaz82**
This mimics pretty close what boost::locale does, set everything to use the hosts locale, except for numerics which need to always handle dot as decimal point and not comma, else the xml parser fails. And this is close to what boost::locale does.

The benefits? Faster compile times, smaller executable and one less dependency.

### CODE REVIEW

**Comment by hex007** [comment]
@tomaz82 Is that all that Boost is being used for?

**Comment by tomaz82** [comment]
@hex007 no, but that is the only line of code that requires boost::locale, which is one of few parts of boost that isn't header only and thus needs a compiled library.

**Comment by joolswills** [comment]
If we ever need to switch to multi language, would this have any impact? Is it possible we may need to use more of the boost library functionality for example.

**Comment by tomaz82** [comment]
@joolswills I personally would not use boost::locale for such a thing, I personally would probably look into GNU gettext ( https://www.gnu.org/software/gettext ) if I were to code multi-langual support.

**Comment by joolswills** [comment]
Yep. We would use gettext - but as I am unfamiliar with boost, I was wondering if there might be something else we might need. NP. Will merge.

**Pull request merged**
