### PR TITLE
Fix for image resize flicker when using MaxSize

### PR DESCRIPTION
**Pull request by pjft**
This should fix for the most part an annoying image resize flicker that had been discussed in the forums in the past and seemed to have cropped up several versions back.

I added some safety code for minSize as well, which should also at least mitigate the issue there if present.

### CODE REVIEW

**Comment by jrassa** [comment]
Thanks

**Comment by Koerty** [comment]
Hi @pjft 

May I ask why you changed the code of the max size function but not of the min size function ? They share very similar code with only small differences, so if the old max size function had bugs then they may still be here in the min size function.

**Comment by pjft** [comment]
Hi @Koerty , great to hear from you!

I'll be honest, it was a while ago, so the details are fuzzy, but I'm very much under the impression that I considered applying the change to the minSize code but ended up not doing it after thinking it through. I did make a small change to it though, hoping to prevent the issue on that code path, but I imagine that if the behavior comes up it'll be easy to fix. 

Since I was unable to replicate the issue in the minSize codepath, I chose not to risk breaking it further. Sorry about that.

How are you keeping?

**Comment by EctoOne** [comment]
Just a quick question? is `<minSize>`actually a thing? Because it is not mentioned in the themes.md and I heard about it here for the first time.

**Comment by jrassa** [comment]
@EctoOne if I remember correctly, minSize was added internally as part of the grid work.  It isn't exposed as a theme option currently.

**Pull request merged**
