### PR TITLE
allow configuring the "hotkey enable" button

### PR DESCRIPTION
**Pull request by joolswills**
RetroPie-Setup input configuration scripts will also need an update to support this, but the idea is that you can choose a button other than "select" for the hotkey enable button.

If left empty it would still default to select.

Will need an svg for this also

### CODE REVIEW

**Comment by joolswills** [comment]
I updated this PR. Now includes a graphic and a requester which pops up if no hotkey is set, and asks if you want to use the select button.

One problem though - it doesn't work - primarily because I have no idea what I am doing ;-)

in GuiInputConfig.cpp I have

```
		Input input;
		if (!mTargetConfig->getInputByName("HotKeyEnable", &input)) {
			mWindow->pushGui(new GuiMsgBox(mWindow,
				"YOU DIDN'T CHOOSE A HOTKEY ENABLE BUTTON - DO YOU WANT TO USE THE SELECT BUTTON DEFAULT ? ANSWER YES TO USE SELECT OR NO TO NOT SET A HOTKEY ENABLE BUTTON.",
				"YES", [this] {
					Input input;
					mTargetConfig->getInputByName("Select", &input);
					mTargetConfig->mapInput("HotKeyEnable", input);
					},
				"NO", nullptr
			));
		}
		InputManager::getInstance()->writeDeviceConfig(mTargetConfig); // save
```

The lines 

```
					mTargetConfig->getInputByName("Select", &input);
					mTargetConfig->mapInput("HotKeyEnable", input);
```

don't seem to do anything in new GuiMsgBox, but if I put them just before `InputManager::getInstance()->writeDeviceConfig(mTargetConfig); // save` they work (the hotkey button gets set to the select button). I'm obviously missing something obvious.

Happy to get some C++ tips from anyone :)

**Comment by joolswills** [comment]
When I say they don't work - the code gets called, but no hotkey enable button gets saved - but it does if I move those lines outside of the new GuiMsgBox.

**Comment by pjft** [comment]
I see :)

Let me take a look at this when I have the chance and happy to point you in
the right direction if I can!

I may ask some questions if anything isn't fully clear.

Thanks for updating this.

**Comment by joolswills** [comment]
Cheers!

**Comment by pjft** [comment]
So, my advanced c++ knowledge is a bit rusty, so I'd love to actually test this out and see what's happening in runtime. And/or someone else who's a lot more proficient with it this day and age to comment here :)

My only hypothesis at the moment from reading the code, for that to be happening is that the `mTargetConfig` object you're accessing there may not be the one you thing it is, but rather a copy in memory. The fact that you're using a lambda inside another lambda may compound these references-or-copies challenges.

Read: [Lambda](http://en.cppreference.com/w/cpp/language/lambda)

One hypothesis, if that is the case: try to replace `[this]` with `[&mInputConfig]` only, and see if that way you actually edit the expected object instead of a copy, at least for that scope which - according to what you mentioned - contains the expected Input Config data. It _shouldn't_ be the case (i.e. I'd expect `[this]` to work, but since we only use that particular object, might as well just pass it directly and see if that's the problem or not), but I don't have any other ideas at the moment.

If that doesn't help, I'll see if I can actually test the code during the weekend and see what's actually happening! Hope I'm not sending you on too much of a wild goose chase.

No money-back guarantee :)

**Comment by hex007** [comment]
What does the hotkey enable do. Can someone elaborate on the current and expected behavior.

**Comment by pjft** [comment]
Oh, apologies. Obviously my comment was only focused on the issue @joolswills had described - not whether the overall code solves the desired problem! 

From what I gathered, if you currently do not have a select key assigned to something, you won't be notified that you'll not have a hotkey for the emulators, I take it. Also, implicitly, the hotkey is hardcoded to the select button. 

This change would:
- add an explicit hotkey entry in the controller setup dialog; 
- warn the user if they haven't chosen a hotkey, and if that's the case offers to set select as the default hotkey. 

I believe that's the gist, from what I gather.

**Comment by joolswills** [comment]
Pretty much. The overall idea is to allow configuration of the hotkey enable button if someone wants. For controllers with extra buttons    its useful to not use select to avoid conflicts with game buttons.

Thanks @pjft for your analysis. I think you may be right. I was thinking it's a pointer / wrong object issue but my c++ is rather rusty. Will give your suggestion a go. And have a good read on your link :-) Cheers.

**Comment by joolswills** [comment]
unfortunately your suggestion didn't work as you can't reference class members. I tried a few other things, but need to do some more reading. Maybe I can pass an `input` struct by reference, and then use that after the lamda function.

**Comment by pjft** [comment]
Oh, that's unfortunate. I can certainly take a deeper hands on look at the
code during the weekend if it'd help - just say so. There's a point where
it just gets frustrating to run into the same problem for long, so let me
know if that's the case :)

**Comment by joolswills** [comment]
Any help is welcome thanks :-) (but no pressure!)

**Comment by pjft** [comment]
No pressure whatsoever. I'll see what I can find.

I always like an new opportunity to fail miserably :)

**Comment by pjft** [comment]
It's actually simple, after adding some logging to all paths. It doesn't
run sequentially, so in the current structure, in fact the writing will
take place before you even exit the prompt :)

You'll likely need to add a set of ifs, with all branches writing the
config - or maybe just adding the command to write the config there will
work, though when I tried to access that object there I god a segmentation
fault, so I wonder if it's also being correctly initialized or if it's
actually empty. I might have done something wrong with it, though :)

Hope these nudge you in the right direction for now.

Have a great weekend!


- Paulo Tavares

**Comment by joolswills** [comment]
Aha. Thanks for the pointers.

**Comment by pjft** [comment]
Not at all. This is a weird one for me.

I've been looking into this quite a bit, and the results are far too
erratic for me to be comfortable with it, but might have been because of my
changes to them.

I got some segmentation faults quite often, as well as some erratic
behavior when running that function.

However, if inside that function I accessed things with the "this->" prefix,

```
this->mTargetConfig->getInputByName("Select", &input);
this->mTargetConfig->mapInput("HotKeyEnable", input);
InputManager::getInstance()->writeDeviceConfig(this->mTargetConfig);
```

it seemed to work more reliably, though I fail to see why that would be the
case.

I am not an expert here, but hopefully after some testing you may be able
to best understand what works and what doesn't :)

Best. Have a great weekend.




- Paulo Tavares

**Comment by pjft** [comment]
Ok.

I think I kind of know why this works "better".

From https://blog.feabhas.com/2014/03/demystifying-c-lambdas/ ,

"Be very careful when capturing local objects by reference because a
lambda’s lifetime may exceed the lifetime of its capture list. In other
words, the lambda may have a reference to an object no longer in scope!"

and, if the code effectively runs in the sequence we mentioned earlier,
when we do `delete this` at the end of that code path, we are telling the
application that it can remove "this" from memory, so the instances of
mTargetConfig we were using inside the Lambda were likely no longer valid,
if the garbage collector would have gotten to them. By explicitly
referencing "this", I *hope* we are forcing the garbage collector not to
get rid of the object, as I had a higher (still not 100%) degree of success
with that, but it still is too flaky for my liking as I can't promise
whether that is effectively done by design or by chance, but might help
explain why I do get the random segmentation fault when saving the select
hotkey.

My preference would be to have 3 clearly defined code branches, that will
inevitably repeat code, but will run in the expected sequence:
- Has defined HotKey: saves input, deletes object
- Hasn't defined hotkey and wants to use select: adds select, saves input,
deletes object
- Hasn't defined hotkey and doesn't want to use select: saves input,
deletes object

Sub-optimal, yes, but hopefully reliable.

Would love to hear other people's thoughts, as I'm clearly not as
proficient in this as I would have been in the past.

Anyway, hope these help!


- Paulo Tavares

**Comment by joolswills** [comment]
I have updated the PR with a solution that seems to work based on your suggestions - by putting 

```
		InputManager::getInstance()->writeDeviceConfig(mTargetConfig); // save
		if(okCallback)
			okCallback();
		delete this; 
```

in another lambda and re-using it in each situation. Does it look sensible to you or would you do it differently ?

**Comment by pjft** [comment]
Thanks. 

This sounds quite sensible indeed. Just confirming, as I'm only reading the code, there's no other way to exit that form other than pushing the OK button, otherwise we'd need to make sure to delete it in that code path as well. 

If that's correct and your tests suggest it works as intended, it should be good to go!

**Comment by joolswills** [comment]
I have changed the code slightly - now when "no hotkey is set" the hotkey enable button in the xml will be set to a key with id 0. Reason for this is so the input configuration script which uses the xml to generate the retroarch configuration can be backwards compatible -

* no xml entry for hotkeyenable - use select as before
* key set to 0 - disable hotkey enable button
* anything else - use that for hotkey enable button.

These changes rely on - https://github.com/RetroPie/RetroPie-Setup/pull/1988 which is not yet merged.

**Comment by pjft** [comment]
Looks good to me from reading the code. 

This will be helpful for people to choose something other than select, as I've found some games do use select+something for specific actions! 

Looking forward to it. Thanks for persevering through this!

**Comment by joolswills** [comment]
This is still a global controller setting, but useful for people who have an extra button on their controller or prefer to use something other than select.

It does add another level of complexity doing an initial configuration for new users, but hopefully with it being well documented it should be fine. I could add "RECOMMENDED" to the yes option perhaps if the hotkey enable button is left blank.

**Comment by pjft** [comment]
Oh, I get that it'll be a global setting - but this way I can assign it to
the "PS" button on the controller (at least until I make my own cabinet -
then I'm out of buttons :) ).

It doesn't add a lot of complexity for new users, I take it, though if I'm
honest I don't really know what a hotkey is or why it's needed. If I'm told
I need it to exit games among other things, then that may be more helpful?

Just a thought.


- Paulo Tavares

**Comment by joolswills** [comment]
Yeah, I think you make a good point. I can probably be more verbose in the requester - will adjust that.

**Comment by joolswills** [comment]
I changed the text to 

`YOU DIDN'T CHOOSE A HOTKEY ENABLE BUTTON. THIS IS REQUIRED FOR EXITING GAMES WITH A CONTROLLER. DO YOU WANT TO USE THE SELECT BUTTON DEFAULT ? PLEASE ANSWER YES TO USE SELECT OR NO TO NOT SET A HOTKEY ENABLE BUTTON.",`

**Comment by pjft** [comment]
Thanks!


- Paulo Tavares

**Pull request merged**
