### PR TITLE
Replace external pugixml by packaged one

### PR DESCRIPTION
**Pull request by raelgc**
`libpugixml-dev` is available on `apt` (for `arm` and `amd64`) as for `vcpkg`

### CODE REVIEW

**Comment by pjft** [comment]
Thanks. How does this affect non-Linux systems, particularly the include paths? Did we test any?

**Comment by raelgc** [comment]
@pjft I've included the configuration for the `vcpkg` related package (and I double checked it exists), but I didn't test the build on Windows yet.

I can try spin my Windows vm and try it.

**Comment by pjft** [comment]
Thank you. We made some recent updates to support compiling on Windows, Ubuntu and MacOS if I'm not mistaken. Just want to make sure this plays well.

**Comment by raelgc** [comment]
It appears that PR #821 have the same goal.

**Comment by pjft** [comment]
Thanks for sending this over. We merged the previous PR that should accomplish the same. Thanks for the heads up.

**Comment by raelgc** [comment]
No problem, thanks for the feedback and the hard work, @pjft!

**Pull request closed without merging**
