### PR TITLE
Improving kids mode

### LINKED ISSUE #431: Hide more features on Kiosk mode
Hi guys,

I've configured some boxes to work in the Kiosk mode, but still kids are messing with them. Then, when the next kid will start to play, a lot of the configurations are changed.

Basically my idea is to hide more options/features in Kiosk mode:

1 - hide the entire main menu (the one fired with <kbd>start</kbd>): some kids will put sound volume to `0` or will shutdown the system;

2 - on game list view, disable `Favorites` (to avoid add/remove items to favorites) and `Options` (keep the game list display settings untouched);

3 - on system list view, hide `Launch Screensaver` entry. My ScreenSaver is the black one. Some kids start it and then came to ask why "nothing is displayed".

I can work on this if you all approve the idea.

### PR DESCRIPTION
**Pull request by raelgc**
Fixes #431

### CODE REVIEW

**Comment by pjft** [comment]
Thanks. From reading through the code things look good.

To confirm, we're removing a "hideQuitMenuOnKidUI" from the Kids mode, and always adding the Quit menu? I thought you wanted to do it the other way around?

**Comment by raelgc** [comment]
@pjft I removed `hideQuitMenuOnKidUI` because Kids mode will now hide the entire Main Menu, so `hideQuitMenuOnKidUI` is no more used.

**Comment by pjft** [comment]
Thanks for clarifying - LGTM.

**Comment by raelgc** [comment]
@pjft Sure, I can squash. But, just our or curiosity, why is not "Squash and Merge" option during the PR merge from GitHub enough?

image

**Comment by raelgc** [comment]
Hi @pjft and thanks for the feedback!

No sorry for the delay: I can realize it's an open/free software and everyone here is contributing in free time. As a contributor, I'm just anxious, because I love ES and want to contribute!

I'll work on requested changes.

**Comment by pjft** [comment]
Thanks for the enthusiasm and the contributions - very much appreciated!

Let me know when it's ready for testing.

Thanks!

**Comment by raelgc** [comment]
@pjft I just made and squashed the requested changes (reload only when required after apply toggle the filters disabler and hiding Favorites on Kiosk/Kids modes).

**Comment by pjft** [comment]
Tested, looks good to me. Thanks!

@jrassa if nobody else wants to test it, I'm fine with merging.

**Comment by jrassa** [comment]
Thanks.

**Pull request merged**
