### PR TITLE
Change grid creation flow

### PR DESCRIPTION
**Pull request by Koerty**
This is part of my work in making the ImageGridComponent and its parent the IList more reliables. This make sure the functions "buildTiles" and "calcGridDimension" are only called one time and only when needed (after a theme changed).

**Changes**
- This changes make sure the buildTiles function is called only one time, at the end of the applyTheme function.
- The buildTiles function now call calcGridDimension as both are linked to the same events

### CODE REVIEW

**Comment by Koerty** [comment]
@pjft @jrassa I'm not sure it's a good thing to remove the onSizeChanged function override, but I'm sure it is a bad thing to leave it that way. I think it is a good example of the "spaghetti code" of this part of the ES.

The problem is the first thing we do in ImageGridComponent::applyTheme is calling GuiComponent::applyTheme, if the theme changed the grid size, the GuiComponent will call it setSize function, which will trigger the onSizeChanged event, which will call buildTiles and updateTiles, but we don't want to, because after that we get back to the rest of the ImageGridComponent::applyTheme function, which will set the margin and the tile size, and then, and only then, we will have the proper dimensions to call the buildTiles function.

**Comment by jrassa** [comment]
@Koerty 

Did you try moving GuiComponent::applyTheme to the end of ImageGridComponent::applyTheme?  I don't think it has to be the first thing we do.  It is just general convention.  As long as nothing else is dependent on the properties set in GuiComponent it should be safe.  If that works, I would just add a comment about why it is at the end.

One approach I have seen used in gui libraries is to have the ability to suspend/resume events.  The idea being that if you are going to perform multiple operations that would result an expensive operation triggering multiple times, you can suspend the events, perform all the work, then resume events.  It is not really the most elegant approach, but it could be a worst case scenario option.

**Comment by Koerty** [comment]
@jrassa Moving the GuiComponent::applyTheme to the end should work, not sure this is the correct solution either. It doesn't depend on the other properties set in the GuiComponent for now, but if we enable the support of the "rotation" or "origin" property for example, then it won't work anymore.

Same with suspend/resume events, it look like another way to get around the problem, not resolve it.

For the solution I proposed in this PR, it work as long as we don't call the setSize function externally after the theme is loaded, which isn't a proper solution either but this is the cleaner way I thought of.

**Comment by jrassa** [comment]
> @jrassa Moving the GuiComponent::applyTheme to the end should work, not sure this is the correct solution either. It doesn't depend on the other properties set in the GuiComponent for now, but if we enable the support of the "rotation" or "origin" property for example, then it won't work anymore.

I think origin is definately something we would want to support.  Roation doesn't work well with the clipRects.  Another option would be to split the call to GuiComponent::applyTheme into 2 calls.  You can specify which properties you want to apply so you could do the following:

```
GuiComponent::applyTheme(theme, view, element, properties ^ ThemeFlags.SIZE);

// Do everything specific to ImageGridComponent

GuiComponent::applyTheme(theme, view, element, properties ^ (properties ^ ThemeFlags.SIZE) );
```

You could also just not call GuiComponent::applyTheme.  ImageComponent takes that approach, assumedly due to the need to handle size/maxSize.  I am not really a fan of that approach and would like to clean it up since it involves code duplication.

**Comment by Koerty** [comment]
Hello @jrassa , #426 can wait, but can we move ahead on this, then #418 and then #419 ?

Not that I want to make you feel on a rush, I know you also do that on your free time. But I would like to finish this before the end of the next 2 weeks, or at least go forward as much as possible on this, as I may have less free time to dedicate to this project after that.

**Comment by jrassa** [comment]
Thanks.  Hoping to take a look at the latest on #418 tonight.

**Pull request merged**
