### PR TITLE
Add more metadata to folders, allowing proper editing in GUI

### PR DESCRIPTION
**Pull request by pjft**
Hi. It's my first PR, so apologies if I'm missing some of the process.

For people who use subfolders in their gamelist, we currently provided a sub-optimal experience:
- Allowed to show images, but not videos;
- Allowed for editing, but the GUI would show up incomplete;
- Did not show some of the metadata, if it existed on the gamelist (i.e. number of players, stars, etc), especially useful for multi-disc games under the same folder, or even for category groupings.

This small change enables video playback for folders, when selected, and also opens up a lot more of the metadata to the folders (in fact, all but the "Last Played" date, and "Play Count").

Hope it suits. 

Thanks.

### CODE REVIEW

**Comment by joolswills** [comment]
Please squash your commits and I will test/review. Please see https://github.com/RetroPie/EmulationStation/pull/101 for some more information regarding this.

**Comment by pjft** [comment]
Thanks for the feedback. Just to confirm, you'd rather have a single commit in the PR, with only the changes vs Master, is that it? I'll do my best.

**Comment by joolswills** [comment]
A single commit if that makes sense, or multiple commits, if that makes sense (grouped changes_. But not multiple commits with one commit fixing an error with another.

**Comment by pjft** [comment]
Got it, thanks. I'll look into that in the coming days - used to be a CVS guy ages ago, first time using GitHub.

If I have any trouble I may come back with questions, but hopefully that won't be the case.

Have a great weekend.

**Comment by pjft** [comment]
I think I've messed this up beyond any repair. :|

I'm going to likely delete this and create a new PR.

**Comment by joolswills** [comment]
You can reuse the branch. No need to close.

**Comment by pjft** [comment]
I created a new one now, after reusing the branch. 

I didn't know I could re-use this PR as well, but (likely) lesson learned for the future. :)

Sorry for the trouble.

**Pull request closed without merging**
