### PR TITLE
Fix vsync off

### PR DESCRIPTION
**Pull request by tomaz82**
Fix vsync off, SDL_GL_SetSwapInterval(0) is not always default

### CODE REVIEW

**Comment by zigurana** [comment]
Can you please elaborate? What does this do? Does it fix a bug? How did it manifest?

**Comment by tomaz82** [comment]
This fixes vsync off ( using the command line option ).
In the current code, it only calls SDL_GL_SetSwapInterval(-1) or SDL_GL_SetSwapInterval(1) if vsync is on, and if vsync is off it does nothing, which is the wrong behaviour, the comment even wrongfully claims that SDL_GL_SetSwapInterval(0) would be the default which it most often is not. So this fix simply makes sure to set SDL_GL_SetSwapInterval(0) if vsync is requested to be off.

**Comment by psyke83** [comment]
I don't dispute that this is a genuine bugfix, I'm not a fan of the new behaviour of ES. It may be rendering more FPS, but the program looks far more choppy/ugly due to the tearing effect on my Pi 3. Additionally, it's rendering @140fps, which is causing higher CPU usage due to there being no effective framerate cap.

@joolswills, would you accept a PR to RetroPie-Setup that allows configuring EmulationStation to start with "--vsync on"? I can keep it off by default, of course, if that's what you want.

**Comment by psyke83** [comment]
BTW, VSync defaults to off on Pi, and isn't configurable in the interface.
https://github.com/RetroPie/EmulationStation/blob/master/es-core/src/Settings.cpp#L55

**Comment by tomaz82** [comment]
That was not the intention of this PR.
As you said, this was a genuine bugfix.

Looking at it now it's obvious that vsync has always been on, eventho the wanted behavior ( which I disagree with ) was that vsync should have been off on the Pi, but never has been.
So eventho this did fix the bug that vsync was never turned off, I think the default on the Pi should be to have it on.

**Comment by psyke83** [comment]
@tomaz82,

I didn't mean to sound accusatory; your patch fixed a bug but exposed two others:
1. Pi has vsync off by default, so your patch is now causing SDL_GL_SetSwapInterval(0). Before your patch, it was using the driver/SDL default.
2. The "vsync on" now sets SDL_GL_SetSwapInterval(-1) first, which actually enables late swap tearing, which is choppy and runs at a ridiculous framerate.

This restores "vsync --on" to the intended behaviour:
```
diff --git a/es-core/src/Renderer_init_sdlgl.cpp b/es-core/src/Renderer_init_sdlgl.cpp
index f064223..580d82d 100644
--- a/es-core/src/Renderer_init_sdlgl.cpp
+++ b/es-core/src/Renderer_init_sdlgl.cpp
@@ -107,7 +107,7 @@ namespace Renderer
                        // SDL_GL_SetSwapInterval returns 0 on success, -1 on error.
                        // if vsync is requested, try late swap tearing; if that doesn't work, try normal vsync
                        // if that doesn't work, report an error
-                       if(SDL_GL_SetSwapInterval(-1) != 0 && SDL_GL_SetSwapInterval(1) != 0)
+                       if(SDL_GL_SetSwapInterval(1) != 0 && SDL_GL_SetSwapInterval(-1) != 0)
                                LOG(LogWarning) << "Tried to enable vsync, but failed! (" << SDL_GetError() << ")";
                }
                else
```

I would also petition to also remove the vsync default off setting for Pi entirely. It makes sense constrain the framerate, and I suspect that even sub-60fps vsync will look better than any higher framerate with visible tear.

**Comment by psyke83** [comment]
Might as well send the PR: https://github.com/RetroPie/EmulationStation/pull/270

**Pull request merged**
