### PR TITLE
implemented feature element to allow themes to support new features w…

### PR DESCRIPTION
**Pull request by jrassa**
…ithout breaking older versions of ES

### CODE REVIEW

**Comment by zigurana** [comment]
To be sure, this is done nicely. However, I still do not understand why we need this in the first place. Are we expecting to have a situation with multiple main/master ES branches, with varying support for different view types?
Or is this PR meant to facilitate people using their themes from experimental branches on the master branch, while specific theming elements are not yet supported by the master ES?

**Comment by zigurana** [comment]
I am also unsure about the strategy chosen here, as this only covers the viewtypes, correct?
Alternatively, we could have the parseElement() and parseView() methods be a bit more forgiving, basically skipping unknown element types, rather than failing hard as they currently do.
That way, when someone comes with a newer theme (with previously unknown element types) and tries it on an older version of ES, it will just ignore those. It will still break the theme, but at least it will fail a bit more gracefully.

**Comment by jrassa** [comment]
The main problem that this is trying to fix is themes breaking for users who have not updated EmulationStation.  As a prime example, I submitted a PR a while back to add video support to carbon.  It has understandably not yet been accepted because it will break the theme for users who have not yet updated EmulationStation, but choose to update or add the theme.

The problem with skipping unknown element types is that it won't help users who do not update EmulationStation.  This method takes advantage of the way the theme parser works in that older versions of EmulationStation will ignore the feature element.  This allow theme makers to support new features without having to worry about breaking the theme for users.

It works at the view level, but it doesn't just cover view types.

Here is a sample of how it would work for video theming:
```
<feature supported="carousel">
    <view name="video">
        <video name="md_video">
        ...
        </video>
    </view>
</feature>
```

Here is a sample of how it would work for carousel theming.  It can guard off not only the new `carousel` element, but the `backgroundColor` element that you added for text components:
```
<feature supported="carousel">
    <view name="system">
        <carousel name="systemcarousel">
        ...
        </carousel>
        <text name="systemInfo">
            <backgroundColor>000000FF</backgroundColor>
        </text>
    </view>
</feature>
```

**Comment by zigurana** [comment]
Ah, so if I understand correctly, the feature type is unknown by older
versions of ES, but because it's not within a view, it gets ignored, and
does not break theme parsing on older ES-es?

Op ma 27 feb. 2017 15:31 schreef John Rassa <notifications@github.com>:

The main problem that this is trying to fix is themes breaking for users
who have not updated EmulationStation. As a prime example, I submitted a PR
a while back to add video support to carbon. It has understandably not yet
been accepted because it will break the theme for users who have not yet
updated EmulationStation, but choose to update or add the theme.

The problem with skipping unknown element types is that it won't help users
who do not update EmulationStation. This method takes advantage of the way
the theme parser works in that older versions of EmulationStation will
ignore the feature element. This allow theme makers to support new features
without having to worry about breaking the theme for users.

It works at the view level, but it doesn't just cover view types.

Here is a sample of how it would work for video theming:

<feature supported="carousel">
    <view name="video">
        <video name="md_video">
        ...
        </video>
    </view>
</feature>

Here is a sample of how it would work for carousel theming. It can guard
off not only the new carousel element, but the backgroundColor element that
you added for text components:

<feature supported="carousel">
    <view name="system">
        <carousel name="systemcarousel">
        ...
        </carousel>
        <text name="systemInfo">
            <backgroundColor>000000FF</backgroundColor>
        </text>
    </view>
</feature>

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/RetroPie/EmulationStation/pull/96#issuecomment-282735886>,
or mute the thread

**Comment by jrassa** [comment]
Yes, older versions of EmulationStation will ignore the feature element.  At the root of the xml, the parser is looking for specific elements (`include` and `view`).  Any other elements at this level are ignored.

**Comment by joolswills** [comment]
Thanks. Will test.

**Comment by jrassa** [comment]
I made a small change.  I realized that the parseFeatures method would allow more than one value in the supported attribute similar to how view works.  In this case, however we only want to support a single value.

**Comment by joolswills** [comment]
Will this require changes to existing themes with video support ?

**Comment by jrassa** [comment]
It does not require any changes to existing themes with video support.  Existing themes may choose to adopt this so that they do not break for users who are still running EmulationStation without video support.

**Comment by joolswills** [comment]
thanks.

**Pull request merged**
