### PR TITLE
Fixed a quirk in the Clion PR

### PR DESCRIPTION
**Pull request by PokeEngineer**
@Koerty accidentally excluded all .cmake files instead of the specific files that Clion generated, and was getting in my way of developing a new feature... So, I fixed it. BTW, no offence, @Koerty.

### CODE REVIEW

**Comment by jrassa** [comment]
Thanks

**Comment by Koerty** [comment]
@PokeEngineer Oops, sorry for this small mistake. Thank you for fixing it.

**Comment by PokeEngineer** [comment]
@Koerty 

You are welcome.

**Comment by Koerty** [comment]
I just received a mail notification because @tomaz82 fetched his ES fork about 1h30 ago and I'm mentioned in the comment of your commit message. Jesus Christ, there is 555 forks of this repository at the moment.

**Pull request merged**
