### PR TITLE
Add image slideshow screensaver mode

### PR DESCRIPTION
**Pull request by csonsino**
This change adds an image slideshow screensaver mode with optional
background audio.  The existing menu and video screensaver have been
refactored to include this new mode.

By default, the slideshow screensaver will show images from the
game list, but it can be configured in the menu to use a custom
directory instead.

### CODE REVIEW

**Comment by csonsino** [comment]
Sorry about resubmitting this.  I made a mess of the rebase on the original pull request, but this version should be correct.  For the original comment thread, please see https://github.com/RetroPie/EmulationStation/pull/179

**Comment by csonsino** [comment]
Looks like this feature is broken after merging in some of the recent changes.  The images do not seem to be changing properly.

**Comment by hex007** [comment]
@csonsino Would you like some help debugging this?

**Comment by pjft** [comment]
You may either need to set power saver to false, or we'll have to add the
swap condition to the timeout bit.

Hex: this is probably broken because of the same reason the screensaver is.

Csonsino: hex has a PR to fix this. Wait for it to be merged and then it's
easier. In this case, disable the power savings in the menu, and then I'd
check if it works. If it does, that's good.

Hex: I'd probably suggest keeping the default power saver settings to
disabled. As more and more features arise, I fear this kind of conflicts
will become more and more prevalent.

**Comment by hex007** [comment]
@pjft  If a user has already updated then they have been set to default. So its better to leave at that and get the bugs out. I am also asking a few of the Youtube guys featuring Retropie stuff if they might be interested in demoing PS once it reaches stable.

@csonsino I would highly recommend waiting a few days. Also, I am unable to access the repository you are submitting PR from. If you could make it public then I can test it out for conflicts.

**Comment by pjft** [comment]
Sure - but in the future a lot of users will update or be new users
altogether, so changing the default still seems like a valid option.
Whatever number may have updated so far will always be small in the grand
scheme of things.

You'll still get the bugs out one way or the other, but hopefully they
won't affect everyone when they arise.

**Comment by csonsino** [comment]
Thanks for the comments.  I'll spend some time on this over the weekend and will try to get a functioning PR.

**Comment by hex007** [comment]
@pjft Do you think the current state of Sceensaver is easily extendible? I do not like how complex it already is for a mere 3 types.

**Comment by pjft** [comment]
I think that the ScreenSaver could probably use a good refactoring - if you
look back 6 months ago, there was no Screensaver class, it was all
contained within the main while(running) loop.

Only when video was introduced, namely the video screensaver, that
@fieldofcows took a first stab at extracting it into a new class,
thankfully.

That being said, with new screensaver types emerging, I think that probably
is worth looking into - not necessarily in this specific PR, but
separately. Agreed.


- Paulo Tavares

**Comment by csonsino** [comment]
My PR will also include a refactor of the screensaver classes, but honestly it was pretty easy to add a new mode.  I had zero knowledge of the codebase, and I was able to add the slideshow mode in a couple of days.  I probably spent more time figuring out the menu system to add/modify menu entries than I did messing with the screensaver code.

**Pull request closed without merging**
