### PR TITLE
Update artwork & add visual help to make button configuration easier to understand

### PR DESCRIPTION
**Pull request by hzulla**
(This is an updated description after some changes to #438, hence the new pull request.)

This patch updates many of the SVG artwork files with cleaned up versions. E.g. some of the original svg files had elements that were partly outside of the svg viewBox. As an example, the upper and lower borders of the d-pad outline were smudged because of that.

Before / after:

old-icons  new_icons

This patch adds four new images of the buttons that quickly explain the button layout expected by Retropie. Also, the button names during button config have the [button compass directions](https://www.kernel.org/doc/Documentation/input/gamepad.txt) added.

I assume that a common mistake while configuring a gamepad is mixing up the controller's [button positions](https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration), e.g. because the XBox gamepad uses a different ABXY-button layout than the one expected by Retropie.

I fell into that trap multiple times myself. My first Retropie setup had the buttons mixed up because I didn't google the proper layout for my unlabeled SNES-style controller. One year later, a new fresh Retropie install and I did the very same mistake *again* when using an XBox controller with different button labels.

compass

New artwork was added for the left/right trigger buttons to distinguish them from the shoulder buttons.

Also, there's new, yet unused artwork, adding four PSX-style buttons and four number buttons. These might be useful once a feature is added to make gamepad labels configurable by the user, see #442.

Finally, there is a minor code change to `GuiInputConfig.cpp` to make the list of configurable input controls easier to read.

### CODE REVIEW

**Comment by hzulla** [comment]
I wanted to provide these here since users are being told to replace graphics on their own if they want to customize the button labels. So it seems to make sense to offer common button labels using the same style.

**Comment by hzulla** [comment]
@jrassa Do you have an opinion on the patch? I tried not to change the look, at least not too much. These SVGs are just cleaner versions of the originals and should scale with fewer artifacts on all screen sizes.  The font is Open Sans Hebrew Ultra-Bold Condensed. The only real change to the look are the compass direction buttons shown in the screenshot, those are only shown in the gamepad setup screen.

**Comment by pjft** [comment]
From reading the code and testing, it seems to work as advertised.

I didn't end up testing actually saving the controller inputs as I only have my "production" Pi with me at the moment and don't want to risk messing any of the RetroArch or emulator configs up, but checking the ES logs for the button mappings being generated and all that, it seems to work fine.

Thanks!

**Comment by jrassa** [comment]
@hzulla I haven't had a chance to test it out yet, but I looked it over and it looks good to me.  I'm good with the inclusion of the additional images.  I am going to be traveling for the next few days.  When I get back I will test it out and get it merged.

**Comment by jrassa** [comment]
@hzulla Looks good to me.  Can you squash it down to one commit?

**Comment by hzulla** [comment]
Can do. On monday.

**Comment by hzulla** [comment]
@jrassa Ok, done.

**Comment by jrassa** [comment]
Thanks.

**Pull request merged**
