### PR TITLE
Added Daphne emulator to PlatformId enum and GamesDBJSONScraper list to mimic Arcade for TheGamesDB API calls

### PR DESCRIPTION
**Pull request by PhilaPhan80**
This adds Daphne to the emulator list with the same id (23) as Arcade.  This allows Daphne games to be scraped from their standalone directory by tricking the API into thinking it's looking up an arcade game (which it technically is).

### CODE REVIEW

**Comment by pjft** [comment]
Thank you. Can you squash the commits in a single one?

**Comment by PhilaPhan80** [comment]
Sure, I'd be happy to.  However, I'm not sure how to do that within the Github.com interface I'm looking at.  The only options available are to edit the title, comment, and close.  Do I need to cancel this pull request and submit another in order to squash the commits?

**Comment by pjft** [comment]
I wouldn't know how to do it on the GitHub.com interface, alas. I usually follow a variation of this:

https://github.com/wprig/wprig/wiki/How-to-squash-commits

But it might just be easier in this case to submit a new PR if it helps with a single commit with these two changes. What works best for you - thank you.

**Comment by joolswills** [comment]
Thanks for the contribution.

**Comment by PhilaPhan80** [comment]
Thanks, I'll remember that for next time.  Glad to assist where I can!

**Comment by joolswills** [comment]
Just to note this broke the scraper - see https://github.com/RetroPie/EmulationStation/pull/699

**Comment by PhilaPhan80** [comment]
Oh, no!  Sorry about that.  I must've not realized at the time that there was another file to modify.
It's weird, though, because the scraper has been working just fine for me.
Thanks for letting me know.  I'll watch out for that in the future!


    On Wednesday, November 4, 2020, 09:43:42 AM EST, Jools Wills <notifications@github.com> wrote:  
 
 


Just to note this broke the scraper - see #699

**Pull request merged**
