### PR TITLE
Implement libcec4 compatibility

### PR DESCRIPTION
**Pull request by psyke83**
Needed for Raspbian stretch.

So far, only compile-tested, no build warnings. Unfortunately, when I try to hold a remote button to configure input, "CEC" appears grayed and disappears; it seems that my TV's CEC implementation doesn't support long-press, so the code may need changing to work for me.

pinging @tomaz82

### CODE REVIEW

**Comment by tomaz82** [comment]
@psyke83 Was the duplication of the actual callback functions needed? Them look identical to me, and it seems that the older libcec also had support for the cec_adapter_descriptor, currently testing it, if that's the case then it's only the 4 lines that sets the callbacks the needs to be inside an ifdef.

**Comment by psyke83** [comment]
Yes, it was necessary. Look more closely - the duplicated functions are now void type and one of the arguments are now pointers.

**Comment by tomaz82** [comment]
@psyke83 Oh yeah, I see it now, but at least the cec_adapter_descriptor should work on both libcec versions, testing it as we speak but my TV also has dodgy cec, it works sometimes, and sometimes not, and it's not es, even cec-client fails to read any input when this happends.

**Comment by psyke83** [comment]
I'll switch over to jessie and confirm that for you (re: cec_adapter_descriptor) & update the PR once I'm confirmed it still builds ok.

**Comment by tomaz82** [comment]
I just confirmed that your change to using cec_adpater_descript and DetectAdapters works on jessie, I also figured out why my cec was dodgy, it doesn't read input if I launch ES remotely from putty, only if I launch it on the actual Pi.

So, only the callbacks, and the setting of the callbacks needs to be inside ifdef

**Comment by psyke83** [comment]
Good, will update. I assume you won't mind if I update your debug logging to use "DetectAdapters" and "strComName" too.

**Comment by tomaz82** [comment]
Yeah, that's what I tried to say, keep your code, no need to have the old code in ifdef ( the descripter, DetectAdapters and DebugLog calls ) your new code work fine on jessie as well, it's only the callback and the setup of them that needs both old a new inside ifdef since

**Comment by psyke83** [comment]
I understood, don't worry. I deliberately didn't change the function names in the debug logging, even in the ">=4" part (which I'll now remove) to keep the logs consistent, but it's better to update the debugging to use the accurate names, since it'll be the same for all versions.

**Comment by tomaz82** [comment]
Oh, I broke it tho, the path debug is wrong, it's using strComName for both, wth.., give me 1 sec

**Comment by psyke83** [comment]
It should be .strComPath?

**Comment by tomaz82** [comment]
Yeah, just found the correct header, damn that took way too long time :P

**Comment by tomaz82** [comment]
And change the log to write out "name: " ? and not strComName ?

**Comment by psyke83** [comment]
OK. Will you be happy with this?
````
                LOG(LogDebug) << "adapter: " << i << " path: " << adapters[i].strComPath << " name: " << adapters[i].strComName;
```

**Comment by tomaz82** [comment]
Yeah, exactly!

**Comment by psyke83** [comment]
Should be ready now.

OT: I tried reducing the HOLD_TIME in es-core/src/guis/GuiDetectDevice.cpp to help enter the input configuration, but I still can't skip entries, hah. I guess I won't be using CEC in ES without manually editing a controller configuration.

**Comment by joolswills** [comment]
Thanks.

**Comment by psyke83** [comment]
Thanks.

@tomaz82 I've tested CEC now... it works well upon first look, and when returning from launching an emulator, but Kodi seems to cause major issues:

* Kodi will freeze when loading its CEC plugin, or else Kodi will run but CEC will not function.
* Exiting Kodi either causes Kodi itself to stay stuck indefinitely on the shutdown menu, or it will close, but EmulationStation segfaults.

On Jessie, Kodi uses libcec4, so I tried removing libcec3, libcec-dev and rebuilt ES with libcec4, so that the same library version is used for both programs. CEC still works OK in ES but doesn't improve the interaction with Kodi.

I noticed that when ES launches an item, "lsof" still shows libcec loaded into ES. I removed libcec from the common libraries (https://github.com/RetroPie/EmulationStation/blob/master/CMakeLists.txt#L183), but it doesn't help. I suspect that the library may not be not closing CEC/unloading correctly.

**Comment by pjft** [comment]
That behavior seems to happen when Kodi detects some types of devices plugged in on start or exit. Are you unloading CEC when launching Kodi and an emulator, and reloading it when coming back to ES? Could that be an option?

**Comment by psyke83** [comment]
Looking at Tomas' patch, CECInput::deinit() gets called in InputManager::deinit(), which is called before an item is launched through Window::deinit(), so theoretically, ES in its suspended state shouldn't be interfering with Kodi.

Even when I manually disable the Kodi's CEC plugin, it doesn't resolve the freezing and/or segfault issue.

When ES is running, I see:
```
pi@retropie:~/RetroPie-Setup $ lsof | grep cec
emulation 25235                pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
emulation 25235 25236          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
VCHIQ     25235 25237          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
HDispmanx 25235 25238          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
HTV       25235 25239          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
HCEC      25235 25240          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
emulation 25235 25241          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
emulation 25235 25242          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
emulation 25235 25243          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
```

When I launch an emulator, some, but not all references are gone:
```
pi@retropie:~/RetroPie-Setup $ lsof | grep cec
emulation 25235                pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
emulation 25235 25236          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
VCHIQ     25235 25237          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
HDispmanx 25235 25238          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
HTV       25235 25239          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
HCEC      25235 25240          pi  mem       REG      179,2   593832       1929 /usr/lib/arm-linux-gnueabihf/libcec.so.4.0.2
```

This is output from a build where libcec is removed from common libraries. This does make a difference, as if I comment out CECInput::init(), libcec won't appear in ES maps (but will if it's part of the common libraries).

**Pull request merged**
