### PR TITLE
Fixes compiling when Renderer_GLES10 is used

### LINKED ISSUE #602: Commit 726d7e6a4fd293ec26509d75f10102ebe820d7cc breaks compilation
After commit 726d7e6a4fd293ec26509d75f10102ebe820d7cc I get this error
```
../es-core/src/renderers/Renderer_GLES10.cpp: In function 'void Renderer::setMatrix(const Transform4x4f&)':
../es-core/src/renderers/Renderer_GLES10.cpp:196:17: error: variable 'Transform4x4f matrix' has initializer but incomplete type
   Transform4x4f matrix = _matrix;
                 ^~~~~~
```
Once I revert that commit it compiles without a problem

### PR DESCRIPTION
**Pull request by shantigilbert**
Fixes #602

### CODE REVIEW

**Comment by hex007** [comment]
Thanks, was having the same issue

**Comment by hex007** [comment]
@tomaz82 can you take a look.

**Comment by tomaz82** [comment]
Yepp, my mistake, and this is the proper fix for it

> Thanks, was having the same issue
> 
> Edit: you should remove the class declaration below too

Which declaration?

**Comment by shantigilbert** [comment]
@hex007 not sure which class declaration?

**Comment by hex007** [comment]
There is a class definition in one of the header files included.

image

**Comment by shantigilbert** [comment]
That declaration is needed, compilation fails without it

**Comment by hex007** [comment]
Move the `#include "math/Transform4x4f.h"` to the header and remove the class declaration. That way it should work as expected.

**Comment by shantigilbert** [comment]
Then also `Renderer.cpp` and `Renderer_GL21.cpp`  in the renderer directory would need to be changed as well, this is just based on Renderer_GL21.cpp which has the include `#include "math/Transform4x4f.h"` and I figured it was the problem with GLES10

**Comment by hex007** [comment]
@tomaz82 Can you share your opinion on this ?

**Comment by joolswills** [comment]
Merging

**Comment by tomaz82** [comment]
@hex007 @shantigilbert This was done correctly, one should always avoid header inclusion in headers as far as possible, since header includes in headers adds A LOT to compile times.

Due to the simple fact that isntead of just Renderer_G21/GLES10.cpp including Transform4x4f.h, if added to the hader, then all files including Renderer.h would also include Transform4x4f.h, which most of them probably don't need, so yeah.

General rule, avoid header in header as far as possible, if a forward declaration in header is enough, then always go with that.

**Pull request merged**
