### PR TITLE
Fixes for issues #503 and #505.

### PR DESCRIPTION
**Pull request by c0d3h4x0r**
This should resolve [https://github.com/RetroPie/EmulationStation/issues/503](https://github.com/RetroPie/EmulationStation/issues/503) and [https://github.com/RetroPie/EmulationStation/issues/505](https://github.com/RetroPie/EmulationStation/issues/505).

### CODE REVIEW

**Comment by pjft** [comment]
Looks good to me, at least the Delete button text one.
The scraper one looks good in principle though I can’t test it myself.
You might want to submit two separate PRs, apologies - one for each - as that is usually the case for PRs for the project.

Thanks!

**Comment by c0d3h4x0r** [comment]
I've already tested the scraper one on my own RetroPie installation.  It works, as long as you've edited your es_systems.config to split out TG16 CD-ROMs to their own system using 'pcenginecd' as the platform.

**Comment by c0d3h4x0r** [comment]
@pjft Afaict, the only way to split them into separate pull requests would be to create my own branch to contain each change, and then create separate pull requests (one from each branch).  Sorry, I'm still a relative n00b when it comes to git, so just be thankful I've figured it out this much :)

**Comment by pjft** [comment]
Sure, no worries. We’ll pick that battle if the time comes - I am not a repo owner. :)

I think that you are right - it’d need to be two branches - but I’m not a Git expert either.

**Pull request merged**
