### PR TITLE
This should fix scraper getting stuck when screen dim kicks in...

### PR DESCRIPTION
**Pull request by verybadsoldier**
... by denying sleep mode when scraper is running.

### CODE REVIEW

**Comment by joolswills** [comment]
Will this still dim if the scraper is running (but avoid the code that stops the gui updating etc) ?

**Comment by verybadsoldier** [comment]
No, sleep mode and dimming always go together. Internally they call it "sleeping" and the screen dimming is just the visual indication of that state. No processing takes place in that state. It will only ask for input device events to wake up again.

**Comment by joolswills** [comment]
that's what I thought from looking at the code - I wonder if this should be changed. eg dim anyway, but only sleep when not doing anything. I think if we disable the dimming when scraping some people may complain about it (and I don't want to be blamed for plasma screen burn)

**Comment by verybadsoldier** [comment]
Ok, changed it to be like this: After the configured time without input the screensaver will be rendered (no matter if scraping or not) even if scraping takes place.
Sleep mode behaves as before: Only kicks in if no scraping takes place.

**Comment by verybadsoldier** [comment]
No hurry, but may I ask what your stance on this is?

**Comment by joolswills** [comment]
I had missed it. Will review thanks.

**Comment by joolswills** [comment]
Sorry for the delay - still on my todo list :)

**Comment by joolswills** [comment]
Thanks for being patient - seems to work well from my testing - cheers!

**Comment by verybadsoldier** [comment]
No problem, thanks, thats great!

**Pull request merged**
