### PR TITLE
Fix WSOD by loading textures on demand in a separate thread when a us…

### PR DESCRIPTION
**Pull request by fieldofcows**
…er configurable texture memory threshold is reached.

See thread: https://retropie.org.uk/forum/topic/2389/solution-for-white-screen-of-death. The fix went through a few iterations and ended up being non-trivial due to having to rework the texture and SVG code to work in a multithreaded way.

I've tested as much as I can on RPi1 and RPi3 with both small and large themes where the small themes can be fully loaded into VRAM and large themes cannot and need to be swapped. There has also been testing by other members of the forum as can be evidenced by posts in the WSOD topic.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks very much for all your work on this.

**Comment by joolswills** [comment]
I admit I didn't test this before merging (as it had a lot of testing on the forum by others).

I have an issue unfortunately  - on carbon on ES on my linux machine - the red gradient on the bar seems to be wrong on some systems when scrolling. It looks like it has lost some colour depth. on my current machine it only seems to display correctly on one system (infocom). 

see attached pics (it's more noticeable at 1080p - these pics are in windowed mode at 640x480 but you can see the difference)

es1

es2

reverting your changes makes all of them look like the first screenshot.

**Comment by joolswills** [comment]
Here's some 1080p screenshots which show the difference more clearly.

Note it seems to be different each time

es1

es2

**Comment by joolswills** [comment]
I'm getting a segfault on my rpi after this changeset too - I've not had a chance to build with debugging - I can tomorrow, but I'm going to have to revert this for now sorry. Another user on the forum is also reporting a segfault after updating ES.

**Comment by joolswills** [comment]
I think I know what the issue may be with the segfault (as it only happened on my rpi)  - I bet it's this:

https://github.com/hrydgard/ppsspp/pull/8117

Happens when building threaded apps for armv7 on the armv6 userland (ABI compatibility issue).

I'll check/confirm this tomorrow (darkplaces quake in retropie has a similar workaround).

**Comment by fieldofcows** [comment]
Is the segfault on a rpi2? It's the only platform I don't own.

**Comment by fieldofcows** [comment]
I'm not sure what's happening with the gradient. I'll reproduce it later and take a look. Does it only go wrong on Linux?

**Comment by joolswills** [comment]
the segfault affects armv7 or above if building on Raspbian for armv7+ target (eg `export CXXFLAGS="-mcpu=cortex-a7"`

I have confirmed that building with `-U__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2` resolves it.

So there is just the texture issue which is minor. Sorry for any inconvenience regarding the above issue. I have actually added that globally to RetroPie-Setup now (as at least 4 programs required it), so nothing needs to be done directly to Emulation Station.

**Comment by joolswills** [comment]
I can confirm the gradient is wrong on the RPI also.

**Comment by MWGemini** [comment]
Is the issue only on the Carbon theme? I was one of the few people who tested the WSOD fix prior to this PR, and tested with several themes, but Carbon was not among them. I didn't notice any graphical glitches on the other themes I tested, but I spend most of my time on my customized tronkyfran theme, so I might not notice when other themes have minor things wrong.

**Comment by joolswills** [comment]
I've only tested with the carbon theme.

**Comment by joolswills** [comment]
If I alter the carbon theme opacity for that texture it becomes consistent - eg

```diff
diff --git a/carbon.xml b/carbon.xml
index c94d85e..257923a 100644
--- a/carbon.xml
+++ b/carbon.xml
@@ -39,7 +39,7 @@ Element color: Search and replace colors. Do not use spaces!
                        <pos>0.5 0.5</pos>
                        <origin>0.5 0.5</origin>
                        <path>./art/centerfade.png</path>
-                       <color>8b000050</color>
+                       <color>8b0000ff</color>
                </image>
 
                <image name="BottomBar" extra="true">
```

but the gradient is "rough" - it's a small texture scaled up btw

To fix that I had to change the GL magnification filter to LINEAR

```
diff --git a/es-core/src/resources/TextureData.cpp b/es-core/src/resources/TextureData.cpp
index 15a3da1..e614464 100644
--- a/es-core/src/resources/TextureData.cpp
+++ b/es-core/src/resources/TextureData.cpp
@@ -182,7 +182,7 @@ bool TextureData::uploadAndBind()
                glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, mWidth, mHeight, 0, GL_RGBA, GL_UNSIGNED_BYTE, mDataRGBA);
 
                glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
-               glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
+               glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
 
                const GLint wrapMode = mTile ? GL_REPEAT : GL_CLAMP_TO_EDGE;
                glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, wrapMode);
```

**Comment by fieldofcows** [comment]
That's unusual because the previous revision never used GL_LINEAR for GL_TEXTURE_MAG_FILTER as far as I can see.

I'm currently taking a look to see why you need to change the opacity for it to work. I'm guessing I'm missing an enable/disable of alpha blending or something like that.

**Comment by joolswills** [comment]
@fieldofcows It's actually the same previously, I just couldn't tell it wasn't smooth as it had less opacity. If I set the alpha to FF in carbon, it looks as it does with your changes.

**Comment by fieldofcows** [comment]
It turned out to be quite an easy fix. I had a feeling it was due to the fade-in of late loaded textures so I took this out and it fixed the issue, giving me a clue as to where the problem was.

Traced to two different problems. Firstly there were a couple of uninitialised member variables. I don't know how they slipped through the net. Secondly, the fade-in (which was only happening due to an uninitialised variable) faded to the wrong opacity because there are two ways to set it in the image component.

The diff below fixes the issue.

```diff
diff --git a/es-core/src/components/ImageComponent.cpp b/es-core/src/components/ImageComponent.cpp
index 1ae6231..0705e0c 100644
--- a/es-core/src/components/ImageComponent.cpp
+++ b/es-core/src/components/ImageComponent.cpp
@@ -23,7 +23,7 @@ Eigen::Vector2f ImageComponent::getCenter() const
 
 ImageComponent::ImageComponent(Window* window, bool forceLoad, bool dynamic) : GuiComponent(window),
        mTargetIsMax(false), mFlipX(false), mFlipY(false), mOrigin(0.0, 0.0), mTargetSize(0, 0), mColorShift(0xFFFFFFFF),
-       mForceLoad(forceLoad), mDynamic(dynamic)
+       mForceLoad(forceLoad), mDynamic(dynamic), mFadeOpacity(0.0f), mFading(false)
 {
        updateColors();
 }
@@ -160,6 +160,9 @@ void ImageComponent::setFlipY(bool flip)
 void ImageComponent::setColorShift(unsigned int color)
 {
        mColorShift = color;
+       // Grab the opacity from the color shift because we may need to apply it if
+       // fading textures in
+       mOpacity = color & 0xff;
        updateColors();
 }
```

**Comment by joolswills** [comment]
Awesome thanks :)

**Comment by joolswills** [comment]
Are you ok to submit a new PR including the fix ? (If you are short on time I can do it).

**Comment by fieldofcows** [comment]
Do I need to squash it into the previous changes? I can do it.

**Comment by fieldofcows** [comment]
Done

**Pull request merged**
