### PR TITLE
[WIP] Replace xml gamelistdb with sqlite.

### PR DESCRIPTION
**Pull request by MisterTea**
This is a merge from Aloshi's gamelistdb branch back into RetroPie.  This replaces the xml-based gamelist with sqlite.  The big reason for this is the following:

- When EmulationStation starts, the entire xml is read.  This is very slow

- Every time a single game is audited, the entire xml is read and written back.  This is VERY slow, and happens during an audit once per game, making audits of large rom sets impractical.  After this merge, scanning a rom went from ~180000ms to less than 500ms.

The merge fixes both of the above issues, but it's a work-in-progress (i.e. do not merge yet) because I noticed a new "directLaunch" property in SystemData.cpp.  I'm not sure what this does, and I'm pretty sure I didn't merge all of the changes required to support it.  Can you explain what directLaunch is?  thanks!

### CODE REVIEW

**Comment by HerbFargus** [comment]
See more info on directlaunch here:

https://github.com/RetroPie/EmulationStation/pull/1

Video showing how it works:

http://www.youtube.com/watch?v=C2tIy3n6fJ0&t=6m40s

There needs to be some extensive testing before we make any large changes with something like this, if I remember correctly from the last time we ran tests the loading times weren't exceptionally different, perhaps it may have been more so on systems with gratuitous amounts of roms.

**Comment by joolswills** [comment]
We already have the branch here and have tested it - but we have chosen to stick with the xml branch for now - I found a few issues with the sqlite branch, and in fact there were performance issues with it also. There is no need for a pull request though.

**Comment by joolswills** [comment]
(but thanks anyway)

**Comment by joolswills** [comment]
Some additional info - you can just checkout the unstable branch on this repository - https://github.com/RetroPie/EmulationStation/tree/unstable which contains the sqlite support + our controller stuff on top.

**Comment by MisterTea** [comment]
Cool, I'll check it out.  I also have a fork of EmulationStation that is
designed to work well with MAME.  It turns the ES config into a ctrlr file
so MAME can accept your ES mappings automatically:
https://github.com/MisterTea/EmulationStation/blob/esmame/es-core/src/InputManager.cpp#L370

**Pull request closed without merging**
