### PR TITLE
Grid updates

### PR DESCRIPTION
**Pull request by jrassa**
Animate scrolling/selection, autoLayout option, center selection option, scroll loop option.

### CODE REVIEW

**Comment by fabricecaruso** [comment]
Hi, there are some problems in what you took from me :
- You removed my String::Split method to use delimitedStringToVector for paddings. I didn't use this one because  delimitedStringToVector results are sorted (used for custom collection names) so padding values are in the wrong order. Disable sorting or use a Split method like I did ;-)
- You set mAutoLayout to Vector2f(4, 3) -> Doing that you remove backward compatibility with existing themes -> They all are going to be sized 4x3. You should set it to Vector2f::Zero() 
- mScrollLoop : Interesting idea especially for one row view, but buggy if if mEntries.size() < mGridDimension.y() * mGridDimension.x() -> Verify it. Also have problems with fast scroll because IList.mLoopType is by defaut on LIST_PAUSE_AT_END -> Maybe change to LIST_ALWAYS_LOOP using ImageGridComponent<T>::ImageGridComponent(Window* window) : IList<ImageGridData, T>(window, LIST_SCROLL_STYLE_QUICK, LIST_ALWAYS_LOOP)

**Comment by jrassa** [comment]
@fabricecaruso Thanks for the feedback. 

> Hi, there are some problems in what you took from me :
> 
>     * You removed my String::Split method to use delimitedStringToVector for paddings. I didn't use this one because  delimitedStringToVector results are sorted (used for custom collection names) so padding values are in the wrong order. Disable sorting or use a Split method like I did ;-)
It seemed unnecessary to have 2 methods that did essentially the same thing, which is why I didn't bring over String::Split.  I didn't notice that the existing method was sorting the results.  I have updated it to make the sort optional.

>     * You set mAutoLayout to Vector2f(4, 3) -> Doing that you remove backward compatibility with existing themes -> They all are going to be sized 4x3. You should set it to Vector2f::Zero()
This was a hold over from my testing that didn't get cleaned up.

>     * mScrollLoop : Interesting idea especially for one row view, but buggy if if mEntries.size() < mGridDimension.y() * mGridDimension.x() -> Verify it.
That's what happens when I try to rush things.  I meant to test this, but missed it.  I have added a check that will disable the scroll loop in this scenario.

>Also have problems with fast scroll because IList.mLoopType is by defaut on LIST_PAUSE_AT_END -> Maybe change to LIST_ALWAYS_LOOP using ImageGridComponent::ImageGridComponent(Window* window) : IList<ImageGridData, T>(window, LIST_SCROLL_STYLE_QUICK, LIST_ALWAYS_LOOP)
I didn't think about this scenario, but I can still see some utility in having the scroll pause at the beginning/end of the list.

**Comment by jrassa** [comment]
Added theme option to enabe/disable animation and theme option to specify which image (thumbnail, image, marquee) should be displayed in the grid tiles.

**Comment by fabricecaruso** [comment]
Hi, 

Why do U change theme property names I added without telling me ? 

I can understand the "refactoring" between scrollDirection/centerSelection... Right... or even "colorEnd" instead of "colorGradient"... But why "animateSelection" ? I called "animateSelection", because it was intented only for the selection animation, not the zoom one...

You may have reason to change names, I can understand it...
But I have to discover myself things in the code you modify... 

So : to stay compatible with Retropie, I have to change my code...

A little more communication and/or discussion would be appreciable when it's about that kind of changes... 

By way of my good will : you forgot to declare "animate" (or animateSelection..) in ThemeData... So it does not load + on my version I have made corrections to handle scrollLoop correctly.

**Comment by jrassa** [comment]
> Why do U change theme property names I added without telling me ?

@fabricecaruso Just for clarity, since you mentioned at one point on the forums that you didn't have much experience with github, this is just a pull request.  It is not finalized.  It is not yet a part of the RetroPie ES repository.  It is here so other contributors can review the changes and and provide feedback.  Things could change more based on that feedback.  Although, in this case, I don't expect it to change much.  I had every intention of posting a message on the forums to let you know about the changes once they were merged.

Also, you must understand my process.  I am not going to submit a PR and have my name on a change that I do not understand.  I am taking the time to learn how you implemented it and how it works.  Once I understand it, I may decide to change some things (i.e. theme property names), or come up with some ideas for improvement (i.e. the scrollLoop property).  In addition, this PR isn't intended to include all the changes you have made to the GridView, it includes an initial subset that I thought was most important.  I plan to add more, but may not add everything.

> But why "animateSelection" ? I called "animateSelection", because it was intented only for the selection animation, not the zoom one...

What I implemented with the `animate` theme property was not intended as a replacement for your `animateSelection` property.  It also doesn't prevent it from being included in the future (I still need to evaluate exactly what it is doing and how it works.)

The `animate` property is intended to serve a similar purpose as the `GuiComponent::ALLOWANIMATIONS` variable that you added that is set based on the TransitionStyle setting.  We have the issue now with the System View carousel that there are themes that are designed with a specific transition in mind and just include text in the README or a forum post stating the recommended transition.  I was trying to get ahead of this with the GridView by giving themes the option to control this.  I would like to extend this idea to the System View (and possibly other places) as well.

> A little more communication and/or discussion would be appreciable when it's about that kind of changes...

Hopefully you understand now how the PR process is indended to communicate changes and faciltate discussion.  I am not really sure that I can communicate the changes any sooner.  If I were to inform you before submitting a PR, then there is a chance that things could change based on feedback from others.

> By way of my good will : you forgot to declare "animate" (or animateSelection..) in ThemeData... So it does not load + on my version I have made corrections to handle scrollLoop correctly.

I appreciate this and the previous feedback you left as well.  That is why we have PRs.  So others can see review the changes we have made and provide feedback.  Nobody is perfect and some times we make dumb mistakes.

> But I have to discover myself things in the code you modify...
> 
> So : to stay compatible with Retropie, I have to change my code...

Please don't take this the wrong way, it is not meant to offend, but text is hard and intent and tone can be misinterpreted.  How is that any different than the situation you have put us in?  You are making changes on your own fork and publishing them and I am digging through your commit history to see what has changed.  We suggested that it would be better to create PRs for your changes and work with us to get them merged here, but you pushed back and said it would be too much work.  I even warned that it could be difficult over time to keep things in sync, especially as conflicting changes are made.  I appreciate the work you have done and see the value in it, which is why I am taking the effort to integrate some of it.

**Comment by fabricecaruso** [comment]
Hi, 

I didn't mean to offent too...

I know I've put you in a delicate situation. At first I only wanted to change small things for my Windows version (just for myself) like simplfy the quit menu for win32 only, but... 
I saw so many things, I had so many ideas that I couldn't stop tryin to make it better... So I posted on the forum soon trying to talk about my work & get in touch.
Now we are here... 

I'm still discovering how git & opensource project work, I'm willing to learn ;-) As I already said, I don't know precisely how to help... I didn't really pushed back when I said it was too much work : the problem is, if I did the grid PR myself, I would have also imported the whole indirect package (meaning texture async loading & rescalings & video component corrections & texts enhancements & reloadable corrections ) and I was sure you would have refused it, this is why I let you do that part.
I know I don't have you xp in git & opensourcing & retropie needs & I'm just an "unknow" guy for the Team. 
Even if you do the job for the grid ( which is great ) I still can help on that part. 
Concerning the other parts, I can still help propose PR's for maybe smaller impacting things. I just don't know what to begin with, what should be accepter or refused - someone has to tell me - we can share the work. (maybe start with menu themings?)

Trust me, my message was really with good intentions and I want to help, but I think we should communicate more about things you integrate or things you would like me to integrate. 

I'm absolutely not saying "don't change my code", what I did is certainly not perfect and I know your experience is a real benefit to make things even better, and future feedback may introduce code changes too.

You introduced scrollLoop and I found it was a real good idea. ( About that, It works now in my version with entries < gridsize & I solved the problem of entries % colOpposite != 0 adding empty tiles where required ).  You also changed GL_QUADS to GL_TRIANGLE_STRIP for gradient : this is the good way to do...

I was just saying : I can help understand my (good or bad) choices, and you can always ask me why I made some choices and tell me why we should change things, or that you found a better way to do something.

I was just asking for a little bit more communication, in order to help each other.

Now to help you understand my (discutable) choices about grid animations.

I added GuidComponent::ALLOWANIMATION to avoid animations when powersave mode is set to instant : It deactivates selection animation & zoom animation - this is a "static shortcut" to avoid testing settings directly.

Also, about "animateSelection" : The first anim I added was the selection animation. When you change selection, the selection rectangles moves smoothly to the new selected item. 
It is fun on classic grids (with maxSize images or box3d), but I didn't like this effect for 2d-boxes or images with minSize ( to make tiles like Windows10 / androidtv ).
Plus, I added the gridtile.selectionMode (empty or "image") flag.
When it is empty, selection is extern -> Text is inside the selection, content use padding to display -> animateSelection is pretty.
When gridtile.selectionMode is image -> Text is outside, selection applies only on the image -> In this case, animateSelection is annoying.
So animateSelection was designed to disable this particular animation.

**Pull request merged**
