### PR TITLE
standard style applied

### PR DESCRIPTION
**Pull request by dissolve**
applied rules
`astyle --style=1tbss -n --recursive '*.cpp' '*.h'`
this will make it a lot nicer if we can get all forks on to the same
styling

### CODE REVIEW

**Comment by jacobfk20** [comment]
Thank you.  I also want to note that I am currently working on this fork https://github.com/jacobfk20/EmulationStation

I'll slowly add features to it over time.

**Comment by joolswills** [comment]
I don't see reindenting the entire code to a completely different indent as a solution to anything. ES using tabs to indent by default.

**Comment by joolswills** [comment]
it will make incorporating patches worse - eg if I want to pull in some stuff from the DB branch etc.

**Comment by dissolve** [comment]
not if you run the same script against them all.  Don't really care what the standard is, so long as there is one.

**Comment by joolswills** [comment]
there is already a standard - tabs. Check the code.

**Comment by dissolve** [comment]
thats one piece of a standard, thats just tabbing

**Comment by joolswills** [comment]
there are a few bits here and there with wrong indent, but it's not a big issue currently. and changing it will break stuff. I only fixed up wrong indent of things that were added by us earlier.

**Comment by joolswills** [comment]
It is wrong to restyle the entier ES codebase at this time. Not interested.

**Comment by dissolve** [comment]
I'll see if I can find a style that uses tabs.  There is a lot of unbraced
if statements, etc, i wanted  to fix and have at least some script to be
able to point people to for auto formatting code.

**Comment by joolswills** [comment]
I still won't want to restyle every line of code (eg respacing logic etc). I'm not going to restyle existing old code unless I am going to actively improve it and it needs it and I won't require any changes from other sources. Fixing up some additions that have the wrong indentation - sure. But not everything.

**Pull request closed without merging**
