### PR TITLE
Required changes to build for Windows

### PR DESCRIPTION
**Pull request by aarononeal**
I had to add these to build for Windows. Anyone else find that these are required?

### CODE REVIEW

**Comment by cmitu** [comment]
What is your build environment ? The current source works fine with VS 2017/2015.

**Comment by aarononeal** [comment]
- VS2019
- SDL 2.0.12
- LibVLC 3.0.11

**Comment by cmitu** [comment]
I re-build using VS 2019 (Community) and there's no error during compilation. Linking fails because of `SAFESEH` being enabled, but after disabling it in the linker options, the build succeeds.
Are you using `clang` for compilation ?

**Comment by retroNUC** [comment]
An update from someone who's recently been building Win32 via VS2019 recently - The only required change for compilation is adding `#include <string>` to ResourceManager.h.

**Comment by tomaz82** [comment]
Implemented by https://github.com/RetroPie/EmulationStation/pull/774

**Pull request closed without merging**
