### PR TITLE
Update artwork & add visual help to make button configuration easier to understand

### PR DESCRIPTION
**Pull request by hzulla**
(Note: Graphics changes, new graphics shown later down in the discussion.)

I assume that a common mistake while configuring a gamepad is mixing up the controller's [button positions](https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration), e.g. because the XBox gamepad uses a different ABXY-button layout than the one expected by Retropie.

I fell into that trap multiple times myself. My first Retropie setup had the buttons mixed up because I didn't google the proper layout for my unlabeled SNES-style controller. One year later, a new fresh Retropie install and I did the very same mistake *again* when using an XBox controller with different button labels.

This patch adds four new images of the buttons that quickly explain the button layout expected by Retropie. Also, the button names during button config have the [button compass directions](https://www.kernel.org/doc/Documentation/input/gamepad.txt) added.

### CODE REVIEW

**Comment by dankcushions** [comment]
Not looked at the code, but I like the change! The retropad X/Y/A/B catches a lot of people out.

I kind of feel like we could almost get rid of the letters entirely during the controller configuration.  The problem is with emulationstation needing a label for the buttons in the help text - maybe there's a way of somehow loading up xbox/psx specific labels, depending on the udex device name, and then retropad X/Y/A/B labels as a fallback, but that's a whole other change!

**Comment by hzulla** [comment]
[I've been told in the past](https://github.com/RetroPie/RetroPie-Setup/issues/2325) that Retropie doesn't want to come with default configurations or assume behaviour of the controller based on its udev/usb name. That's the reason for this little change here.

Btw, there's no code change in here, just added graphics and changed labels.

**Comment by hzulla** [comment]
(btw, is there a developer who is in charge of artwork or is it fine if I try to do something myself? I'm not a designer and may need some help on that front later.)

**Comment by pjft** [comment]
Thanks for doing this!

I'm not sure if there's any developer here that is in charge of artwork, but I'm sure in the forums there'll be plenty of people who may be available to help - that's what I did for the collections.

**Comment by pjft** [comment]
Of course, it's also fine if you do it yourself!

**Comment by Koerty** [comment]
I always thought the ABXY-layout was based on the Xbox controller not on the SNES controller. Usually the "confirm" button is located on the south, right under the thumb, at least in Europe and America, not talking about the Japanese. This is very misleading.

**Comment by hzulla** [comment]
@Koerty documentation says otherwise: https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration

**Comment by hzulla** [comment]
But you're right on the other hand that it's an odd choice. I'll leave this to the maintainers of the project to decide, as your original conclusion does have its merits...

**Comment by hzulla** [comment]
This is fascinating: http://gangles.ca/2008/09/16/a-brief-history-of-a-b/

**Comment by hzulla** [comment]
The graphics files for this merge request have been updated. Here is a new screenshot.

compass

**Comment by hzulla** [comment]
Some of the original svg files had elements that were partly outside of the viewport of the svg file. See here, the upper and lower lin of the d-pad outline were smudged because of that.

old-icons  new_icons

There are also new graphics for the trigger buttons.

**Pull request closed without merging**
