### PR TITLE
Log everything CEC does

### PR DESCRIPTION
**Pull request by tomaz82**
Erm, yeah, title says it all.

### CODE REVIEW

**Comment by pjft** [comment]
Just for the record, if CEC doesn't register when called from the shell/SSH, then It'll be hard to log things via Log Debug as that requires the --debug option to be set, I believe. 

Also, is the goal for this to make it to the main release build or just to stay in the dev build for testing?

If the former, I question that for the long run. If the latter, we might use another Log level to make it more easily accessible. 

Best.

**Comment by tomaz82** [comment]
The logging is for debug purposes, that's why I choose debuglog so it won't show in release build. But I'm open to discussions

**Comment by psyke83** [comment]
For your own use, you can just add "--debug 2>/tmp/es.log" to your autostart.sh. Just keep in mind that it'll  probably also log the control codes to clear the screen etc, so read with "strings" ;)

**Comment by tomaz82** [comment]
To clarify, cec doesn't work when you launch es from ssh, it works if launched from bash on the pi ( I have a keyboard connected to my pi )

**Comment by psyke83** [comment]
Yep, my suggestion was to help w/testing. Killing the parent shell after killing ES, via SSH, will trigger ES to reload correctly (with CEC working).

**Comment by tomaz82** [comment]
This PR should be fully working now, fixed ES crashing when launching Kodi, it shuts off CEC in ES when anything is launched and then starts it back up once returning back to ES.

**Comment by psyke83** [comment]
First of all - great work!

The patch solves the issue with ES -> Kodi crashing, and Kodi's CEC plugin indeed works fine. However:
* When I configure the CEC input, the CEC settings are only written to es_temporaryinput.cfg, and not all buttons that I pressed during input are recorded to the configuration file. Once ES is restarted, the remote will not work, as the configuration in es_temporaryinput.cfg seems not not to be read. (WORKAROUND: I manually copied the CEC inputConfig into es_input.cfg, and it seems to work OK with the subset of buttons that were successfully written.)
* Sometimes, returning from Kodi causes ES's CEC to stop working - however, after about 30seconds to a minute, CEC inputs will start registering in ES again. Other times, CEC will work almost immediately after returning from Kodi. Odd, and may not be the fault of your patch.

I will do more testing and let you know - thanks.

**Comment by tomaz82** [comment]
Thanks for testing this, I will also run more tests later today based on your findings. Thanks!

**Comment by tomaz82** [comment]
@psyke83 

https://github.com/RetroPie/RetroPie-Setup/pull/2206

That fixes the saving of the input to es_input.cfg, I have not been able to reproduce the buttons not working problem, neither the returning to ES after Kodi 1 minute delay you mentioned, will run more tests tho.

**Comment by tomaz82** [comment]
As far as I know this should be safe to merge, unless anyone objects?

**Comment by zigurana** [comment]
I have no objections. I saw you changed some logging levels from 'info' to 'debug' , but shouldn't they be 'error' level logging?

**Comment by tomaz82** [comment]
@zigurana Correct, and fixed :)

**Pull request merged**
