### PR TITLE
Get rid of Matrix3x3f, Matrix4x4f, Rotation3x3f and Scale3x3f

### PR DESCRIPTION
**Pull request by tomaz82**
Everything is now handled by Transform4x4f which now does it way more optimized than previous version.

Replaced Scale3x3f and Rotation3x3f with a scale and rotate function directly on the Transform4x4f, this allowed for refactoring away the entire matrix multiplication and produce way faster code.

Also moved the invert function from Matrix4x4f into Transform4x4f. Due to how Transform4x4f works ( and the fact ES is 2D ) 8 out of the 16 variables in the 4x4 matrix is always 0, and 2 are always 1, that leaves only 6 variables that will actually contain values. So I cleaned away all the multiplications by 0 or 1, like this for the heart of doing a matrix invert. This reduced the mul, add and sub calls from 244 down to 12.

```
// Before
tm[ 0] =  ((om[ 5] * (om[10] * om[15] - om[11] * om[14])) - (om[ 9] * (om[ 6] * om[15] - om[ 7] * om[14])) + (om[13] * (om[ 6] * om[11] - om[ 7] * om[10])));
tm[ 1] = -((om[ 1] * (om[10] * om[15] - om[11] * om[14])) - (om[ 9] * (om[ 2] * om[15] - om[ 3] * om[14])) + (om[13] * (om[ 2] * om[11] - om[ 3] * om[10])));
tm[ 2] =  ((om[ 1] * (om[ 6] * om[15] - om[ 7] * om[14])) - (om[ 5] * (om[ 2] * om[15] - om[ 3] * om[14])) + (om[13] * (om[ 2] * om[ 7] - om[ 3] * om[ 6])));
tm[ 3] = -((om[ 1] * (om[ 6] * om[11] - om[ 7] * om[10])) - (om[ 5] * (om[ 2] * om[11] - om[ 3] * om[10])) + (om[ 9] * (om[ 2] * om[ 7] - om[ 3] * om[ 6])));
tm[ 4] = -((om[ 4] * (om[10] * om[15] - om[11] * om[14])) - (om[ 8] * (om[ 6] * om[15] - om[ 7] * om[14])) + (om[12] * (om[ 6] * om[11] - om[ 7] * om[10])));
tm[ 5] =  ((om[ 0] * (om[10] * om[15] - om[11] * om[14])) - (om[ 8] * (om[ 2] * om[15] - om[ 3] * om[14])) + (om[12] * (om[ 2] * om[11] - om[ 3] * om[10])));
tm[ 6] = -((om[ 0] * (om[ 6] * om[15] - om[ 7] * om[14])) - (om[ 4] * (om[ 2] * om[15] - om[ 3] * om[14])) + (om[12] * (om[ 2] * om[ 7] - om[ 3] * om[ 6])));
tm[ 7] =  ((om[ 0] * (om[ 6] * om[11] - om[ 7] * om[10])) - (om[ 4] * (om[ 2] * om[11] - om[ 3] * om[10])) + (om[ 8] * (om[ 2] * om[ 7] - om[ 3] * om[ 6])));
tm[ 8] =  ((om[ 4] * (om[ 9] * om[15] - om[11] * om[13])) - (om[ 8] * (om[ 5] * om[15] - om[ 7] * om[13])) + (om[12] * (om[ 5] * om[11] - om[ 7] * om[ 9])));
tm[ 9] = -((om[ 0] * (om[ 9] * om[15] - om[11] * om[13])) - (om[ 8] * (om[ 1] * om[15] - om[ 3] * om[13])) + (om[12] * (om[ 1] * om[11] - om[ 3] * om[ 9])));
tm[10] =  ((om[ 0] * (om[ 5] * om[15] - om[ 7] * om[13])) - (om[ 4] * (om[ 1] * om[15] - om[ 3] * om[13])) + (om[12] * (om[ 1] * om[ 7] - om[ 3] * om[ 5])));
tm[11] = -((om[ 0] * (om[ 5] * om[11] - om[ 7] * om[ 9])) - (om[ 4] * (om[ 1] * om[11] - om[ 3] * om[ 9])) + (om[ 8] * (om[ 1] * om[ 7] - om[ 3] * om[ 5])));
tm[12] = -((om[ 4] * (om[ 9] * om[14] - om[10] * om[13])) - (om[ 8] * (om[ 5] * om[14] - om[ 6] * om[13])) + (om[12] * (om[ 5] * om[10] - om[ 6] * om[ 9])));
tm[13] =  ((om[ 0] * (om[ 9] * om[14] - om[10] * om[13])) - (om[ 8] * (om[ 1] * om[14] - om[ 2] * om[13])) + (om[12] * (om[ 1] * om[10] - om[ 2] * om[ 9])));
tm[14] = -((om[ 0] * (om[ 5] * om[14] - om[ 6] * om[13])) - (om[ 4] * (om[ 1] * om[14] - om[ 2] * om[13])) + (om[12] * (om[ 1] * om[ 6] - om[ 2] * om[ 5])));
tm[15] =  ((om[ 0] * (om[ 5] * om[10] - om[ 6] * om[ 9])) - (om[ 4] * (om[ 1] * om[10] - om[ 2] * om[ 9])) + (om[ 8] * (om[ 1] * om[ 6] - om[ 2] * om[ 5])));





// Replacing with 0's
tm[ 0] =  ((om[ 5] * (     1 *      1 -      0 *      0)) - (     0 * (     0 *      1 -      0 *      0)) + (om[13] * (     0 *      0 -      0 *      1)));
tm[ 1] = -((om[ 1] * (     1 *      1 -      0 *      0)) - (     0 * (     0 *      1 -      0 *      0)) + (om[13] * (     0 *      0 -      0 *      1)));
tm[ 2] =  ((om[ 1] * (     0 *      1 -      0 *      0)) - (om[ 5] * (     0 *      1 -      0 *      0)) + (om[13] * (     0 *      0 -      0 *      0)));
tm[ 3] = -((om[ 1] * (     0 *      0 -      0 *      1)) - (om[ 5] * (     0 *      0 -      0 *      1)) + (     0 * (     0 *      0 -      0 *      0)));
tm[ 4] = -((om[ 4] * (     1 *      1 -      0 *      0)) - (     0 * (     0 *      1 -      0 *      0)) + (om[12] * (     0 *      0 -      0 *      1)));
tm[ 5] =  ((om[ 0] * (     1 *      1 -      0 *      0)) - (     0 * (     0 *      1 -      0 *      0)) + (om[12] * (     0 *      0 -      0 *      1)));
tm[ 6] = -((om[ 0] * (     0 *      1 -      0 *      0)) - (om[ 4] * (     0 *      1 -      0 *      0)) + (om[12] * (     0 *      0 -      0 *      0)));
tm[ 7] =  ((om[ 0] * (     0 *      0 -      0 *      1)) - (om[ 4] * (     0 *      0 -      0 *      1)) + (     0 * (     0 *      0 -      0 *      0)));
tm[ 8] =  ((om[ 4] * (     0 *      1 -      0 * om[13])) - (     0 * (om[ 5] *      1 -      0 * om[13])) + (om[12] * (om[ 5] *      0 -      0 *      0)));
tm[ 9] = -((om[ 0] * (     0 *      1 -      0 * om[13])) - (     0 * (om[ 1] *      1 -      0 * om[13])) + (om[12] * (om[ 1] *      0 -      0 *      0)));
tm[10] =  ((om[ 0] * (om[ 5] *      1 -      0 * om[13])) - (om[ 4] * (om[ 1] *      1 -      0 * om[13])) + (om[12] * (om[ 1] *      0 -      0 * om[ 5])));
tm[11] = -((om[ 0] * (om[ 5] *      0 -      0 *      0)) - (om[ 4] * (om[ 1] *      0 -      0 *      0)) + (     0 * (om[ 1] *      0 -      0 * om[ 5])));
tm[12] = -((om[ 4] * (     0 *      0 -      1 * om[13])) - (     0 * (om[ 5] *      0 -      0 * om[13])) + (om[12] * (om[ 5] *      1 -      0 *      0)));
tm[13] =  ((om[ 0] * (     0 *      0 -      1 * om[13])) - (     0 * (om[ 1] *      0 -      0 * om[13])) + (om[12] * (om[ 1] *      1 -      0 *      0)));
tm[14] = -((om[ 0] * (om[ 5] *      0 -      0 * om[13])) - (om[ 4] * (om[ 1] *      0 -      0 * om[13])) + (om[12] * (om[ 1] *      0 -      0 * om[ 5])));
tm[15] =  ((om[ 0] * (om[ 5] *      1 -      0 *      0)) - (om[ 4] * (om[ 1] *      1 -      0 *      0)) + (     0 * (om[ 1] *      0 -      0 * om[ 5])));





// After
tm[ 0] =  om[ 5];
tm[ 1] = -om[ 1];
tm[ 2] =  0;
tm[ 3] =  0;
tm[ 4] = -om[ 4];
tm[ 5] =  om[ 0];
tm[ 6] =  0;
tm[ 7] =  0;
tm[ 8] =  0;
tm[ 9] =  0;
tm[10] =  ((om[ 0] *  om[ 5]) - (om[ 4] * om[ 1]));
tm[11] =  0;
tm[12] = -((om[ 4] * -om[13]) + (om[12] * om[ 5]));
tm[13] =  ((om[ 0] * -om[13]) + (om[12] * om[ 1]));
tm[14] =  0;
tm[15] =  ((om[ 0] *  om[ 5]) - (om[ 4] * om[ 1]) );
```

### CODE REVIEW

**Comment by pjft** [comment]
Thanks. I'm curious: any meaningful impact on performance - be it CPU or FPS on the pi? 

Either way, thank you for chasing these!

**Comment by tomaz82** [comment]
This particular PR was sadly only very very minor FPS difference. But my philosophy is that every little detail counts :)

**Comment by jrassa** [comment]
I am concerned about the change to rotation and the removal of the ability to the specify the rotation axis.  I have done some experimenting with rotating about a different axis to allow for a 3d rotation.  This change will prevent this.

I am also concerned about the broader effect these changes may have.  Just because some aspect of functionality isn't being used today, doesn't mean it will never be used.  If you would have submitted this change 6 months ago, you likely would not have implemented rotation support at all as ES's ability to rotate components is a newer feature.  If that were the case, I'm not sure that I would have implemented component rotation without built in support from the matrix classes.

**Comment by tomaz82** [comment]
@jrassa
Implemented back rotate which takes an axis, and added rotateX, rotateY and rotateZ which is more optimized than doing for example rotate(angle, axisZ).

Also changed back scale and translate to work on x y and z for full 3D support.

Merging all this into Transform4x4f is still a huge improvement over the previous version that constructed 3x3 matrices and did full matrix concatenation.

**Comment by joolswills** [comment]
Re compile time. It's slow. Are you building parallel?

**Comment by psyke83** [comment]
Also OT, but might be helpful for @tomaz82 

Compile time can be excruciatingly slow if you're not using the best class SD card. In fact, I was sometimes seeing kernel warnings due to the mmc interface stalling on intensive compiles.

I would highly recommend manually enabling zram (I use these parameters, but increase the swap priority so that the SD swap is only used as fallback): https://gist.github.com/sultanqasim/79799883c6b81c710e36a38008dfa374

If you've got an attached USB drive, I'd think about assigning swap to a partition or swap file there, also with higher priority. I'd also recommend setting up ccache. The latter won't help with the first build, but if you're making small changes it can drastically speed up minor rebuilds.

**Comment by tomaz82** [comment]
Does anyone object against this being merged in it's current state?

**Comment by joolswills** [comment]
I'm going to merge. If there are issues they can be sorted later. We don't track this branch in RetroPie by default so I'm less concerned. @jrassa - let me know if you think there should be changes. My math(s) isn't good enough to review this.

**Comment by jrassa** [comment]
@joolswills it looks good to me

**Pull request merged**
