### PR TITLE
First pass at integrating sselph/scraper

### PR DESCRIPTION
**Pull request by sselph**

### CODE REVIEW

**Comment by HerbFargus** [comment]
Giving it a test now, any special actions needed or will it just function as the current built in scraper for ES?

**Comment by sselph** [comment]
Updated the issue but there is a helper app that needs to be running.

**Comment by HerbFargus** [comment]
well its much faster than the built in one thats for sure and more accurate as well. I just finished scraping a bunch of NES roms and it seemed to work fine. We'd probably have to figure out some logic to run/stop running the app with the scraper perhaps either in the setup script or somehow with emulationstation. I just called it over ssh but for people who aren't on ssh it complicates it a bit

**Comment by sselph** [comment]
yeah starting the helper and how to keep it updated are problems that'd need solving.

**Comment by sselph** [comment]
My next experiment will be to see if I can just compile my code to a library that could be imported by ES so the extra binary thing goes away.

**Comment by HerbFargus** [comment]
That's a good idea. @joolswills has also suggested the possibility of running a web service of sorts. The more automated the better

**Comment by sselph** [comment]
How do you mean? You mean running the code I have on a web server on the internet? Or making a web service a user interacts with?

Running my code external to the system could only partially work. The hashing isn't straight forward so there needs to be code locally to do that. Then the hash could be sent to a service that sent back a url or the actual data.

I have experimented with the web service someone interacts with. It was pretty neat but I never finished it and lost interest.

**Comment by HerbFargus** [comment]
I think he was saying running the code on the server but yeah if it's possible to integrate into es somehow with a library it may make it more portable than having to maintain an extra service

**Comment by sselph** [comment]
I played around with this last night and I was able to get my code to compile into a shared library and was able to write a trivial C program that imported it and called it to scrape a file.

Now comes the hard part, how to make this link into EmulationStation. Time to learn cmake. I want to make this an "optional" library so that if someone doesn't have the library installed and doesn't have the means to build it, it will still compile and my scraper just won't function.

**Comment by sselph** [comment]
Closing this and will open a new one once I make time to create a c library.

**Pull request closed without merging**
