### PR TITLE
Update platform.cpp add video at poweroff and restart system

### PR DESCRIPTION
**Pull request by Kactius**
Thanks to julenvitoria and bitstuffing
Add code to play video when select poweroff system or restart system with omxplayer, /opt/retropie/configs/all/emulationstation/video/restart.mp4
/opt/retropie/configs/all/emulationstation/video/restart.mp4
It is necessary to create the folder and corresponding video

### CODE REVIEW

**Comment by pjft** [comment]
Thanks for sending this over and contributing to the project.

Unfortunately, there are a few reasons why this isn't likely to be accepted for the moment at least.

First, it's very RPi specific - meaning, the functionality for other systems isn't implemented.
Second, it's OMX Player dependent, meaning that on the Pi4 this will just fail.
Third, isn't this something that can be done with the scripting features that @jrassa implemented a while back?

See here: https://github.com/jrassa/EmulationStation/wiki/Scripting

I believe that it achieves the same without having to hardcode it in EmulationStation.

If you can elaborate why you feel strongly that the functionality you're implementing should be inside ES rather than supported by the existing alternatives, do let me know, but I'd be very reluctant to add such a specific hardcoded behavior to ES.

Thanks.

**Comment by Kactius** [comment]
Thanks for your fast answer.
The first thing well thinking, if it is true it is focused only to raspberry.
The second, correct and more seeing the latest kernel changes in raspbian, I'm afraid there will be changes in many related things
Third: Thanks for the information, I did not see this before, I ate it, without being hungry, I will try it, they have to work safely.

**Comment by julenvitoria** [comment]
Interesting... Is the scripting features that @jrassa implemented in the master branch? I don’t know but it very interesting

**Comment by Kactius** [comment]
Info https://retropie.org.uk/docs/EmulationStation/#scripting The final comments
It seems a bit bad faith, to consider it experimental and give the impression of wanting to stop the development by recommending other frontend

**Comment by pjft** [comment]
@julenvitoria they are in the master branch indeed. You'll see fireevent("quit") and fireevent("shutdown") are triggered from GuiMenu.c . Not a problem - by all means - and let us know if it works. An alternative approach would be just to change autostart.sh or emulationstation.sh to call that video in your setup, without having to hardcode it inside ES.

@Kactius Not sure I get where you're coming from, but let me clarify what it's meant to say. That small paragraph in the end is conveying that because these days there is no active new feature development in EmulationStation - which is accurate, as most commits in the last year were mostly around RPi4 support and driver compatibility? - others may want to be aware that there are other frontends that may have more active feature development.

Nobody wants to stop ES development, but there's also nothing major in the roadmap these days. If that doesn't clarify, or if you feel that it could be worded differently to convey what I mentioned, we welcome the change there - thanks!

**Comment by Kactius** [comment]
It working, very thanks.

**Pull request closed without merging**
