### PR TITLE
Fix NES and SNES scraper that broke during boost cleanup

### PR DESCRIPTION
**Pull request by tomaz82**
Should fix https://github.com/RetroPie/EmulationStation/issues/312

### CODE REVIEW

**Comment by hex007** [comment]
@joolswills this requires a sub-version bump in my opinion.

**Comment by joolswills** [comment]
@hex007 did you check commit history before posting ? :)

**Comment by hex007** [comment]
My bad

**Comment by joolswills** [comment]
I've also merged the latest master changes into the stable branch and am currently rebuilding binaries.

**Comment by hex007** [comment]
Ok, I will update all my systems in an hour to include this.

**Pull request merged**
