### PR TITLE
Implemented favourites system

### PR DESCRIPTION
**Pull request by sokie**
Now I know there are already 2 ( or 3? ) pull requests regarding favourites system, but I would like to discuss why I think this fits.
the other pull requests either changed unrelated code, or they implemented the favourites only filter which in my opinion wasn't optimal. Since this is in the metadata, once we have a proper filtering implementation,  this will just become another field there.
Also since the favourite will be seen in the game list, theme support is not really necessary.

### CODE REVIEW

**Comment by pjft** [comment]
Hi @sokie , and thanks for the PR.

Haven't tested yet, but a question to understand the scope: so this just adds it to the metadata, and shows a star in the gamelist - but other than that does not use filters in any way, is that correct?

**Comment by sokie** [comment]
Correct.
Also I built and tested it on debian, couldn't yet push it to my pi. There shouldn't be any issues tough

**Comment by zigurana** [comment]
Hey @sokie,
This seems directly lifted from kaptainka's implementation ([his PR to Aloshi's repo](https://github.com/Aloshi/EmulationStation/pull/393)). 
Is there a reason you don't refer to his original work? 
Not to say it's not a good approach fir our system, but it needs to be integrated with thr current filter implementation to be useful.

**Comment by sokie** [comment]
@zigurana yes it's mostly based on more PRs actually.
I was thinking about doing the filtering on a separate PR. If you think it's not out of scope I can add sort By and filtering to this one.

**Comment by zigurana** [comment]
I see. Still,  it is good practice to acknowledge the contributions of others.
My main concern with this PR is that it does nothing to fix the utter mess that is the current mechanism for populating the metadata-driven theme elements (in detailedGameListView). Quite the opposite is true, as it replicates part of this mess, for the special case when themes allow favorite. This same mess is also the reason why all (detailed) themed need to include all possible Metadata labels and values, in order to be shown successfully, even if they are effectively rendered off-screen.  
This is not all your fault, nor should it be within the scope of a PR that introduces favorites. What we do need however, is a good idea how to move to a better architecture. 
I was thinking that the fix for this could be some type of factory pattern, and implementing favorites could be a suitable test-case for it.

**Comment by sokie** [comment]
I think a factory for theme elements could work, but in that case the xml theme config will be the sole responsible for rendering stuff ( might be a problem when there are no themes loaded ).
I don't think i can take on that task for now tough.
I did implement filtering and sorting tough, if you think it's a good idea i can push that here too @zigurana .

**Comment by pjft** [comment]
Filtering and sorting should already be in place in the current build, and
there's an open PR for further sorting attributes.

If there are improvements to be done, I'd rather build upon them rather
than reinventing the wheel (in a good sense).

**Comment by sokie** [comment]
@pjft what i mean is add the new "favourite" element to the current filtering and sorting system :)

**Comment by sokie** [comment]
I think the option to filter by favourite makes sense, so I've added it to the PR.
I don't know about sorting tough ( could make sense to have favourites on top ).

**Comment by pjft** [comment]
Oh, got it. I think that - after the architecture for the current PR is
defined, I think that'd be a good addition, perhaps as a separate PR.

**Comment by pjft** [comment]
Sorry, we were writing at the same time. Leave it in then for now at least. Thanks. 

One consideration: there were some talks in the forum about using a character for signaling favorites, which is the approach you took here. I'd advise going there and discussing the options. 

https://retropie.org.uk/forum/post/76488

Thanks!

**Comment by sokie** [comment]
Wow, @zigurana pretty much already did all the work that I've just done, awkward :)
I didn't see any PR for this so that's why I just went ahead and implemented it..

**Comment by pjft** [comment]
Well, the more interested people the merrier. He had done similar things on
his kids-friendly build last year and was now in the process of bringing
them over. It was good timing!

Maybe you two could join forces if/where applicable, especially if there
are bigger architectural changes in the pipeline? Or just assess both
approaches and see what's good about both and use that?

I'm still always supportive of an agile, release small but often, approach
otherwise we just get into these mammoth changes that die in the process.

**Comment by sokie** [comment]
Yeah sure I can lend a hand where needed!
I like his change because of the switch component, in the discussion people were talking about the possibility of theming the icon for favourites, that can be an improvement for this.

**Comment by pjft** [comment]
Definitely join there and help the best decision being made :)

Looking forward to seeing the outcome of these developments. Happy Sunday!

**Comment by zigurana** [comment]
@sokie : yeah, sorry for coming on to this a bit aggressive, I had just assumed that you had seen the discussion at the forum, so I was surprised by the PR.
I had not yet submitted a PR for my changes, as I was not happy with the theming and other aspects mentioned earlier. @pjft was correct, as he is so often, that I got bogged down in a big redesign while trying to fix it. 
So please, join us on the forum to sketch out a better design for this, I am sure we csn come up with something better.

**Comment by sokie** [comment]
@zigurana yeah sorry too, i came into this mostly as a user.. I've installed my retropie 1 week ago and using it i thought a favourite system would be helpful, came to git and saw the other PRs on the other forks so I decided to implement them properly here ( including the new video view ).
I didn't know dev discussion were being held on the forum.

**Comment by sokie** [comment]
@zigurana @pjft so, I know this is out of scope of the current PR, but since there are a lot of cool ideas on the forum ( including the themeing mega discussion ).
I think it would be a good idea to create some issues here with the prefered ideas, this way people can pick them up and work on them. I could help too.

**Comment by pjft** [comment]
I think that after the best/optimal/most implementable approach is decided there, then working on it is definitely the way to go :)

And for that reason, I'm supportive of breaking things down in smaller pieces, otherwise we'll keep stalling some things because of other details (in this case, favorites metadata being stalled because of whether it should be a star, an icon, font, colors, blinking or something :) ).

Thanks!

**Comment by sokie** [comment]
@pjft yes I agree, we can always implement something, then immediately create an issue for the missing parts so we have a reminder to what to do.
( same thing can be said here )

**Comment by sokie** [comment]
@joolswills hi, why was this closed? are we mergin @zigurana branch?

**Comment by joolswills** [comment]
I thought from the discussion it was going to be implemented differently ?

**Comment by joolswills** [comment]
BTW, feel free to do the whitepace fixes as a separate PR and I will merge. thanks.

**Comment by sokie** [comment]
@zigurana @pjft from https://retropie.org.uk/forum/topic/10213/favorites-for-emulationstation/115
are we proceeding with initial implementation and hardcoded star or shall I implement icon support from file?

**Comment by sokie** [comment]
@joolswills the whitespace fixes were my fault on the preceding commit, due to xcode being an ass :)

**Comment by zigurana** [comment]
@sokie , if you want to make friends, introduce a new theme element (string), that users can set to select an  favorite character (or leave it out). Otherwise, I would not introduce it now.

Re: adding the selected-image icon, I can re-introduce that in an additional PR later.

**Comment by sokie** [comment]
@zigurana I can do that :)

**Comment by joolswills** [comment]
There are some whitespace issues before your changes from this pr also. I may fix them but you would need to rebase your changes then.

**Comment by sokie** [comment]
@joolswills oh I see. In that case, i can fix them, what are the classes that have problem? ( I already fixed some issues inside FileFilterIndex.cpp which were from before my changes )

**Comment by jrassa** [comment]
A couple quick notes on this.
* I think using a boolean type vs. a string to store the favorite (as is @zigurana doing on his branch is a better approach).
* For presentation of the favorite status as metadata, I think it would be preferable to display as a themable image (with a default image including similar to how rating is done) vs. the text "yes" or "no".

Additionally, I am not a fan of the conditionally including the favorite metadata element on the gamelists based on if the theme "supports" favorites.  There appear to be a bunch of flaws in the implementation (based on reviewing the code, I have not yet tried to run it).  These mostly aren't your fault as they exist in the [original pull request](https://github.com/Aloshi/EmulationStation/pull/393/) that this is based on.
* It doesn't handle switching between themes well.
  * If you start with a theme that supports favorites and switch to one that does not, the favorites metadata element will still be displayed as it was themed under the previous theme.
  * If you start with a theme that does not support favorites and switch to one that does, the favorites metadata element will not be displayed.
* The logic to determine if a theme "supports" favorites is problematic.  It checks if the format version in the theme is >= to `CURRENT_THEME_FORMAT_VERSION`.  This presents 2 problems:
  * If/when `CURRENT_THEME_FORMAT_VERSION` is incremented in the future, any existing themes that do not update their theme format version will no long be considered to "support" variables, even if they do.
  * As it is, you did not increment `CURRENT_THEME_FORMAT_VERSION` so any themes that have a version of 4, will be considered to "support" variables even though they may not.  In the original pull request, the version was incremented from 3 to 4.

**Comment by sokie** [comment]
@jrassa I actually like @zigurana checkbox implementation too.
- It doesn't handle switching between themes well.
    Theme changes should pose no problems.
- The logic to determine if a theme "supports" favorites is problematic
    I agree, everyone implemented it that way. I think the version should be hardcode as the current one +1 ( and increase the current version ).

**Comment by zigurana** [comment]
@jrassa @sokie: Hi, quickly, because I'm actually at work, more time tonight:

* The current current_theme_format_version is a shambles, and should be improved. The getHasFavoritesInTheme() function is a distraction and completely useless currently. The only thing we **must** do, is not break existing functionalities (older themes). Doing a hardcoded required theme level, would require all themes to be updated, that will not end well.
Maybe the supported feature strategy can help us out for now?
Eventually, the theming redesign I'm planning should alleviate this.
* The boolean types are there for the taking, @sokie you can grab them anyway you like.

**Comment by joolswills** [comment]
Whitespace has been fixed in another PR so you will need to rebase this sorry.

**Comment by pjft** [comment]
Hi @sokie .

Was chatting about this earlier, and rather than keeping this open here because of the lack of definition on the presentation side of things (i.e. the gamelist view impact), would you be open/interested in narrowing down the scope of this PR for the time being so it can be merged?

Specifically, the parts that we know won't be changed in the future are:
- Adding favorites to the metadata and to be shown in the metadata editor (as a boolean, though, as @jrassa suggested)
- The filtering support sounds fine as well.
- The input to toggle the favorites status is optional, I'll leave it to your criteria. It is definitely useful, but without anything on the presentation side of things (i.e. no icon or anything) for the moment, I wonder if it's relevant.

Let me know if you'd be keen on scoping this down for the time being so it can be incorporated, as there are a few other changes that rely on favorites - and adding the metadata and filter is already a good change for the time being.

Thanks, and let us know how we can help!

**Comment by sokie** [comment]
Hi @pjft ,
so what you say is removing the changes to all the game list views ( as in the star icon and the logic ) and just keep metadata and filtering on it?
 In that case yeah, the button to toggle favorite is useless since you wouldn't even know if you set it or not.
Also, sure no problem. I can commit tonight to the PR.
Cheers

**Comment by pjft** [comment]
Hi!

Well, yes, I suppose removing the things that are up for discussion still
and thus keeping this from being actually merged, and just keep the things
that are not going to be debated over.

From what I could tell, the main discussion was around the presentation
side of things, that with the Theme refactoring and such, but the
foundational work (metadata, metadata editor, and the filtering) seems to
be fairly standard and required, regardless of whatever comes in the future.

Since you put quite a bit of work into this, it'd be good to make sure that
it gets incorporated rather than stuck in "design discussion" limbo :) The
presentation part can be submitted at a different stage, but it won't keep
this from being incorporated.

From looking at the code, it's actually just splitting the changes you made
to MetaData.cpp (making it a boolean rather than a string), and
FileFilterIndex.* from the rest. I don't suggest you delete them (you may
want to create a new branch from this current state, just so you keep the
changes around for future reference), but for this particular PR I'd keep
just those 3 (I think I'm not missing anything else that'd be critical for
the reduction in scope, but I might have overlooked something).

Let me know if this makes sense, and thank you for working on this!

Also, as @joolswills said, I believe this might need to be rebased as the
code has changed a bit since.


- Paulo Tavares

**Comment by sokie** [comment]
@pjft yes this will get rebased, saw the conflicts.
I will make the changes then!

**Comment by pjft** [comment]
@sokie Hi!

A very awkward, but relevant request if possible.

For compatibility's sake with a lot of existing gamelists from people on the ES-Kids branch, would it be possible to rename the metadata to 

`{"favorite",	MD_BOOL,				"false",			false,		"favorite",				"enter favorite off/on"}`

rather than "favourite" (british spelling)?

Otherwise the existing preferences from everybody on the Kids branch that has favorites support will not be valid.

Sorry for the nitpick.

**Comment by sokie** [comment]
@pjft ahahahah, sure!

**Comment by Darknior** [comment]
@pjft is real it is the good solution.
For my part i love the Favorite and Kid options, i don't understand why nobody merge the two projects ?
It is easier than reinvent the wheel every time and fastest.

**Comment by pjft** [comment]
Baby steps. There's a non-negligible amount of time involved in it, by the
people who developed it. We'll get there, though.

@sokiee thanks! :)

**Comment by Darknior** [comment]
I know people take a non négligeable amount of time to dev it, and it is the strong of internet and open source project to work together ! More coders dev and more stronger is the project.
Here we have 3 projects, Retropie, Retropie Kids, Recallbox and some others ... many options same in the 3 projects, many options left ... so bad :(

**Comment by zigurana** [comment]
@Darknior ,
You seem to be assuming that we are *not* working together and trying to deliver everything into the RetroPie main branch, this is not the case.
Your goals are not different from our goals, these are **not** separate projects. (Apart from RecalBox maybe, but that split has happened a long time ago, even during the time Aloshi himself was still working on ES (2015?))

The initial version of my Kidmodes ES was preliminary at best. It was a messy implementation, and buggy as well. It had to wait for the implementation of other infrastructural enhancements, such as filtering (by @pjft) to become a feasible addition to RetroPie proper.

The point I am trying to make is that yes, we could just quickly merge everything, but in the long run it's better for the code-base (and thus the project) to do it right the first time.

So, be patient, If you want to help speed things up, you can contribute by testing out new builds and delivering feedback.

**Comment by pjft** [comment]
Hi @sokie :)

Apologies for bothering.

I'm about to push a PR that includes the Favorites, as it's needed for the changes I'm putting together.

If you do decide to make this one happen, I'm more than happy to update my PR to remove the favorites functionality, no bother. 

I implemented it very much based on @zigurana 's work - alas, there was no individual commit I could merge here for that, so it was unfortunately a bit of reusing the code here, though I'd love to be able to attribute it. What's the best way to do so?

Thanks.

**Comment by sokie** [comment]
Hi,
No issues for me, you can merge that and close this.
I had some personal issue and couldn't work on this.

**Comment by pjft** [comment]
Sorry to hear about that. Hope all is well.

It'll still be a while until it's actually merged, so we can close this
if/when it effectively gets merged.

No big deal. :)

**Comment by zigurana** [comment]
@pjft, don't worry about attributing it via some convoluted method. I'd be happy just to see the code land. The original approach was implemented by @kaptainka, so I can't claim firsts in any case!

**Comment by hex007** [comment]
@sokie take care, hope everything is going good now

@joolswills This PR can be closed as discussed above

**Comment by joolswills** [comment]
Cheers

**Pull request closed without merging**
