### PR TITLE
#124: Adding sorting options for the number of players, release date,…

### PR DESCRIPTION
**Pull request by MotaDan**
… genre, developer and publisher.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks. Happy for any feedback/testing from others.

**Comment by pjft** [comment]
Thanks for the PR!

Wasn't able to test on a Pi yet, but a few notes and a question from reading the code:
- Notes: Since PR #109 that folders also have more metadata - certainly players, genre, developers, publisher and release date, so that comparison might not be accurate. It still might be worth to have a check against unfilled values, in case the getter-methods don't handle exceptions properly, but other than that you might be able to remove the comparison for metadata type.
- Question: any reason to implement a hands on old-school string comparison logic rather than using [string::compare](http://www.cplusplus.com/reference/string/string/compare/)? Just curious. If there's a key reason to keep this logic, we might want to refactor it to a separate function rather than having the same code in 3 functions. Just a thought. :)

Thanks!

**Comment by MotaDan** [comment]
Is your suggestion to dump these file1->metadata.getType() == GAME_METADATA checks, because folders now have meta data and they are no longer necessary? I didn't dig deep into the code, but is game_metadata the only kind of meta data and is there no longer a way to have no meta data?

No there's no reason for those string compares to be that way. I can only manage copy and pasting when it's late. I'll swap those out.

**Comment by pjft** [comment]
Thanks - and please, don't get me wrong. That looked like a very proper string compare implementation in C, so I was wondering if the reason for that was that we couldn't use C++'s string::compare there because of any data type differences or such. :)

There are two types of metadata - folder metadata, and game metadata, but both now have these same attributes you're sorting for.

Folder metadata only does not have last played, and times played, because, well, we don't launch folders. But all other attributes exist, so in that sense, for the purpose of these comparisons, you don't need to restrict it to games only - that was what I meant.

I'll test it out later today, hopefully. Thanks!

Side note: by the way, I seem to always struggle with downloading a zip and compiling it these days because of pugixml becoming a separate module. CMake terminates with the following warning:

```
CMake Error at external/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /home/pi/work/ES-Dan/EmulationStation-sort_meta/external/pugixml

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

It's not related to this particular branch - happened the same with Zigurana's random game one. Anything we should change in the CMake configuration, or maybe there's something I'm missing? I'm not the most knowledgeable on that aspect, so just checking.

Thanks!

**Comment by pjft** [comment]
All looks good, tested all filters and at first glance all looks to be well.

The performance of sorting by release date is worse than all the others. I suspect it's because of the metadata->getTime getter. Not related to this.

Thanks!

**Comment by zigurana** [comment]
@pjft : the cmake thing is because of a change in the repository configuration. Pugixml is now a submodule, which you need to explicitly initialize. 
See: https://retropie.org.uk/forum/topic/5202/step-by-step-how-to-build-emulationstation-on-windows/56
It's a cleaner way to include depending repositories, but something that took me a while to figure out.

**Comment by MotaDan** [comment]
@pjft ok I understand now, yea those compares don't need to be checking for game metadata first. I'll pull that out. 

I'll look in getTime to make sure there is nothing egregious in there. How does it compare to sorting by last played, the other compare with time? That probably isn't a perfect foil unless you've opened every game and they all have last played data.

**Comment by pjft** [comment]
Yeah. It shouldn't have anything to do with your work here - the
implementation is by the book. It's likely the string-to-date-format
function that's slightly less performant than the other getters.

You're also probably right: since not all games have been played, maybe not
all have last played data so that feels faster? Unsure.

Anyway, looks good to me from my end. Thanks for the addition!

**Comment by pjft** [comment]
Well, you obviously did not touch the last played sorting because it existed beforehand, but in the results it seems like "0" (i.e. the default empty value) is parsed as higher than the ones that have a value set, which makes the sorting look weird at least vs what I expected.

Anyway, it's equally slow, and not related to this code.

**Comment by MotaDan** [comment]
I removed the game meta data checks, so folders should be treated equally now. 
I did check the getTime function and it's using a boost string to ptime function, nothing to be done there. 
I think "0" being the largest value for last played makes sense. If you never played a game the last time you played it is infinitely away.

**Comment by pjft** [comment]
Thanks. I'll check the new changes later then.

Yeah, no particular opinion or concern about the empty date value being higher - I'm just used to the null value being January 1st 1970, the UNIX zero timestamp, so I found it weird. 

Thanks.

**Comment by zigurana** [comment]
@MotaDan 👍  good work!
I was looking at this, and maybe this is a good time to fix another irk I had when working with the sort types, that is, folders are placed somewhere in the list, rather than on top.
I would expect folders always to be on top, or at least for the filename-ascending sort type.
This could be achieved with: 
```
//returns if file1 should come before file2
bool compareFileName(const FileData* file1, const FileData* file2)
{
	// if one of the two is a folder, return the folder first
	if ((file1->getType() == FOLDER) && (file2->getType() == GAME))
		return true;

	if ((file1->getType() == GAME) && (file2->getType() == FOLDER))
		return false;

... rest of the function
```

**Comment by pjft** [comment]
@zigurana ...should folders be on top, though?

I don't have a personal preference, given that I only have a 1-level-deep folder structure, but would people store multi-disc games in folders, and expect them to see on top? Is there a use case that we'd be breaking by changing that behavior?

For the sake of organization, I'd perhaps recommend accepting and closing this PR at its current scope (once more people test) and then maybe we can submit a separate one for other changes. Thoughts? 

I'd like as well to submit something to have the sorting order be kept at least during the same session - otherwise every time I open the menu and close it, it reverts to alphabetical.

**Comment by MotaDan** [comment]
I don't use folders, so I can't speak to any use cases on their sorting. But I would rather that was a separate issue and this PR maintain it's current scope of simply adding more sort options.

**Comment by joolswills** [comment]
Yep. Can do that in a separate PR. It sounds like it should be a configurable option too.

**Comment by joolswills** [comment]
Please can you squash the commit and I will merge (if everyone is happy).

**Comment by pjft** [comment]
It should be good from my last test, but I'll try to get some time tonight to give it a final shot with the latest changes, and confirm all is still good.
Thanks!

**Comment by pjft** [comment]
Hi.

Apologies, I seem to have missed something fairly obvious in the string::compare recommendation. We need to do that with both strings in upper (or lower) case, otherwise it'll not work as intended.

So, for the name, I suspect it should be something like

`toupper(file1->getName()).compare(toupper(file2->getName()))`

Assuming that toupper() is the std::string toupper, and not something else from boost. If not, boost might also have its own string compare.

I just noticed because for some reason SWOS was showing before Sensible World of Soccer in the list now, where before it wasn't. Sorry for the nitpick and for missing that.

Other than that, tested all combinations of filters, all looks good.

I'm happy to do a final test when it's all done.

**Comment by MotaDan** [comment]
Nice catch. I should be able to just use toupper and have everything be fine.

**Comment by MotaDan** [comment]
I added to upper to game, genre and publisher.

**Comment by joolswills** [comment]
Thanks. Is this ready to go now ? If so, please can you squash the commits and I will merge.

**Comment by pjft** [comment]
I'm happy to test it one last time tonight if there are no further takers,
and report back.

**Comment by pjft** [comment]
So, this doesn't compile at the moment on the Pi (at least not on mine). It complains about an overload to toupper. If you replace "std::toupper" by "::toupper" it will compile.

http://stackoverflow.com/questions/7131858/stdtransform-and-toupper-no-matching-function

Other than that, compiled well, tested, looks good to me.

Thanks!

**Comment by joolswills** [comment]
Please can you fix the issue as mentioned by @pjft, squash the commits and I will merge. thanks.

**Comment by MotaDan** [comment]
I'm pretty sure I messed up the squash and am not sure what I have done. Any help on getting this back on track would be appreciated. I was following [this](https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/). A while back I tried to squash the commits when I thought I was done, then commited more changes. I thought I fixed the last issue, squashed again, realized I missed something, thought I aborted the squash, fixed my changes,  commited and pushed. Now the merge I thought I got rid of is showing up and I'm afraid to keep messing with it. I've attached a diff for my changes. I'm considering just creating a new branch with it. Thanks.
[sort_meta.txt](https://github.com/RetroPie/EmulationStation/files/1012728/sort_meta.txt)

**Comment by joolswills** [comment]
I'll try and sort it - but I need a couple of days as a little busy. Cheers

**Comment by pjft** [comment]
Daniel: as someone who's constantly struggling with git I'm happy to try to
help as well. Know that nothing of what I'm saying is likely to be the
right or best way to do things.

My very scrappy approach to doing this is usually:
- Create a new branch with my changes (kind of like a save state), perhaps
even squashed; Push it to git, just to confirm it's safe (for instance,
my-feature-for-rebasing).
- Then, on the original feature branch (my-feature), I'll do "git reset
RetroPie/master" and it'll force reset it to the latest code in RetroPie
(overwriting your changes, mind you!)
- Then, I'll git cherry-pick <my commit hash from the other branch> and
solve any conflicts. Repeat if more than one commit.

So, if this sounds reasonable to you, maybe you would be able to revert
your repository back to where you were via git reflog (I did it in the
past, though I don't know enough about it to detail) and then do these
steps instead.

Of course, I'll just wait for someone to call me out and say that this is
clearly not how you're supposed to do things on GitHub. :)

Have a great weekend.

**Comment by joolswills** [comment]
Instead of resettting and cherry picking - if you want to squash your commits, on your branch just do (feel free to make another branch if you are worried about losing something), `git rebase -i HEAD~2` if you wanted to squash the last two commits for example. (then edit / change to pick / squash / edit as needed to split/join

to rebase some commits on top of master you can do `git rebase origin/master` then resolve any conflicts

assuming `origin` is the upstream repository.

**Comment by joolswills** [comment]
I manually applied this as a single commit.

**Pull request closed without merging**
