### PR TITLE
- removed constant iterators to allow compiling

### PR DESCRIPTION
**Pull request by sboehringer**
+ constant iterators should not work with any compiler as they violate the change semantics where they are used

### CODE REVIEW

**Comment by tomaz82** [comment]
Please explain that reasoning

**Comment by sboehringer** [comment]
The code does not compile with gcc >= 4.8.5 on opensuse. The reason is incorrect code, as constant iterators are used by changes are made on the iterated container which is disallowed. If the code compiles on a platform, it means that the compiler and/or standard library does not follow the c++ standard. If have checked the upstream code and it does not use constant iterators.

**Comment by tomaz82** [comment]
Interesting, I will investigate, it compiles just fine with gcc 5.4.0 on Ubuntu 16.04, Visual Studio 2015 and 2017, and whatever gcc the raspberry pi ships with.

**Comment by joolswills** [comment]
Compiles fine on my gcc 7.2.0 on Ubuntu.

**Comment by joolswills** [comment]
(It also builds on gcc 4.9 on Raspbian Jessie, and gcc 6.0 on Raspbian Stretch on the RPI)

Would be more useful to see the error you get.

**Comment by joolswills** [comment]
Also - if you want to contribute PRs to the project and be taken seriously, do not put things like `must have been added by some c++ hobbyist` in your commit messages.

**Comment by sboehringer** [comment]
My apologies for the commit message. The reason must then be differences in the flags turned on to build the compiler. That being said, I still believe the current code is not correct. See e.g.
http://www.cplusplus.com/reference/vector/vector/cbegin/
It is not allowed to call methods like erase/remove on constant iterators.

**Comment by jrassa** [comment]
I think you are reading it wrong.  When it states:
> but it cannot be used to modify the contents it points to

it is referring to the singular element of the vector that the iterator is currently pointing to, not the vector as a whole that the iterator is iterating over.

Above you stated:
> The code does not compile with gcc >= 4.8.5 on opensuse.

I assume what you really meant was that it did not compile with gcc==4.8.5.  As others have pointed out it is compiling properly with gcc >= 4.9.  A quick google search of `gcc erase const_iterator` yields multiple results indicating that gcc didn't properly implement support for const_iterator on erase until 4.9.

**Comment by jrassa** [comment]
Closing this.  If you want to contribute anything in the future, please target the master branch.  That is where main development occurs.

**Pull request closed without merging**
