### PR TITLE
Res2h Update

### PR DESCRIPTION
**Pull request by Koerty**
The ressources were regenerated using lastest version of Res2h (last commit : 6 Febrary 2017 added 32/64 bits archive support)

@jrassa @zigurana as request, I separated this from my GridView pull request for better readability

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks. This is ready to be merged right now ?

**Comment by zigurana** [comment]
I haven't tested this on a Pi, but it looks good to me.
Thanks for this contribution, I know it seems like an unimportant
administrative action, but it makes a difference in distinguishing the
commits that carry features from those that 'only' improve the code quality
(such as this one).

Looking forward to your next PR!

**Comment by Koerty** [comment]
No problem I can perfectly understand that, feel free to give advices or comments if you see anything else that bother you ;)

**Comment by pjft** [comment]
Thanks for putting this together!

**Pull request merged**
