### PR TITLE
Fix misplaced cursor on LB/LR paging on specific conditions

### LINKED ISSUE #798: When I sort the game list, the highlighted game doesn't appear between the new relocated games I got after the sorting action.
Hello.
When I sort the game list (by name, publisher, system, etc...) I got (sometimes) a result where I can't see the highlighted game I had selected prior to the sort action. Looks like the list position go to a random position and the highlighted game is lost.
This happens depending on the game I select... I don't know why.
Of course, this issue happens when I have more titles than the maximun number of titles can be shown on screen.
This didn't happen in version 2.10.2.

### PR DESCRIPTION
**Pull request by Gemba**
As tabled in the forum
https://retropie.org.uk/forum/topic/33200/full-page-scrolling-misplaces-cursor-at-some-conditions

Also fixes #798

### CODE REVIEW

**Comment by Gemba** [comment]
Corrected position of visible list area after launch of game from screensaver.

**Comment by pjft** [comment]
Apologies, yet another PR that arrived during my summer break and that completely flew under the radar.

@cmitu you end up looking into this specific topic, just to check?

**Comment by cmitu** [comment]
@pjft I think I have briefly looked at this, but to be honest I don't remember what was the result.

**Comment by Gemba** [comment]
As a refresher, also to myself, this PR addresses the testcases (see also test list in referenced forum, http://ix.io/48K3) which fail (marked N). With the PR all testcases should pass. I did test the full list and it also did not create any regression. 

I can elaborate on the testcase list if it is too brief or puzzles you.

**Comment by pjft** [comment]
Thanks. I appreciate the detail of the tests and checking for regressions there. This is a moderately opaque area of the code and I don't know enough about it to make any relevant observations here, so if the tests are ok that's all that matters.

Question: did you confirm if/how this behaves when we have an empty collection and with filters? Just to confirm that nothing breaks there.

If all is good, I'll be happy to squash it.

Thanks.

**Comment by Gemba** [comment]
Good point. To be safe, I tested the filter settings: 
1. When a list is reduced and contains at least one entry, the cursor will be reset to initial position, the same as when navigating into a system after ES boot. Navigation is as expected.
2. When the applied filter(s) result in an empty list the Text "No Entries Found" is displayed and no cursor move is possible. As expected.
3. When the filter(s) are removed the cursor position is as expected as in 1.

Did I miss a filter scenario to test?

**Comment by pjft** [comment]
I think you covered it all then. Thank you!

**Pull request merged**
