### PR TITLE
Update --help text

### PR DESCRIPTION
**Pull request by NeilRickards**
Add to help screen the extra parameters from https://github.com/RetroPie/EmulationStation/pull/324 and https://github.com/RetroPie/EmulationStation/pull/348.
Also replace tabs with spaces for more consistent display, normalize capitalization of first letters, and MB is the correct abbreviation for MegaBytes.

### CODE REVIEW

**Comment by tomaz82** [comment]
You got the screensize comment wrong, resolution is usually the size of your monitor, screensize would most likely be smaller than that.

I can agree that the naming is a bit confusing. screensize/offset/rotate should probably be called canvas and not screen.

**Comment by NeilRickards** [comment]
> You got the screensize comment wrong, resolution is usually the size of your monitor, screensize would most likely be smaller than that.

Ah sorry.  I've updated the text - see if it's any better.
The new Raspberry Pi 4 doesn't support a global display_rotate, so I've had to set it in cmdline.txt, emulationstation and retroarch independently.  I found out about these settings from forum posts.
It might be nice if resolution was flipped automatically for --screenrotation=1 or 3, but setting screensize works nicely.

**Comment by Gemba** [comment]
Maybe it is useful to highlight in the help text which CLI parameters of ES not only override parameters but also will be persisted in the settings file even if the user does not expect it. Or instead of highlighting remove them from the command line and help since there are GUI menu entries.
These are:
`--draw-framerate, DrawFramerate`
`--force-disable-filters, ForceDisableFilters`
`--max-vram, MaxVRAM`
`--gamelist-only, ParseGamelistOnly`
`--show-hidden-files, ShowHiddenFiles`

And then there is the invisible (undocumented?) setting `SplashScreenProgress` which defaults to `true` and only can be changed via manual editing ot the settings file.

**Comment by pjft** [comment]
@tomaz82 are you comfortable with the descriptions for the options?

**Comment by tomaz82** [comment]
> @tomaz82 are you comfortable with the descriptions for the options?

Yeah it looks fine to me

**Comment by pjft** [comment]
Thanks @NeilRickards for sending this over. Apologies for the delay in getting to this.

**Comment by pjft** [comment]
@Gemba happy to take those as well in a separate PR at some point. Just wanted to finish this for now, and not have scope creep cause more delays.

**Comment by Gemba** [comment]
@pjft yes sure go ahead. I will table my suggestion in the forum to find the best fit.

**Pull request merged**
