### PR TITLE
Enables Launch and Next also in Slideshow Screensaver

### PR DESCRIPTION
**Pull request by Gemba**
This is the third PR for the proposed change no. 4 of https://retropie.org.uk/forum/topic/26725/es-screensaver-ux-puzzles-and-suggestions

This first commit is the actual change the second commit are minor code style fixes.

### CODE REVIEW

**Comment by pjft** [comment]
From reading the code, it seems to be a good refactoring of the same to adapt the logic from video screensaver controls to the image one. I don't have the chance to test this at the moment, apologies - maybe in the weekend I'll have access to the Pi.

Nonetheless, in the meantime, if you want to share this over the forums maybe others will want to test it.

Also, could you squash the commits before I merge them?

Thanks.

**Comment by Gemba** [comment]
I rebased the PR to the latest master (c15b386) to resolve the conflict and squashed into one commit.

**Comment by pjft** [comment]
Does anyone have any comments or concerns with this PR?

**Comment by pjft** [comment]
Thanks for putting it together.

**Comment by Gemba** [comment]
Thanks for reviewing and considering it useful for the trunk.

**Pull request merged**
