### PR TITLE
cmake: minor correction to support Ubuntu 20.04

### LINKED ISSUE #643: Error compiling EmulationStation cmake 2.8
Is not possible compile EmulationStation on CentOS 7.
The problem is CMake/Packages/FindRapidJSON.cmake is codifiedd on UTF8.
All others cmake files are ASCII.
Correcting this works ok

https://retropie.org.uk/forum/topic/25215/error-compiling-emulationstation

### PR DESCRIPTION
**Pull request by cmitu**
Looks like `libsdl2-dev` on Ubuntu 20.04 (and Debian testing at the moment) have relocated the headers to `/usr/include/<platform-triplet>` <sup>1</sup>, so detection for `SDL.h` fails currently.
Augment `PATH_SUFFIXES` to search in `/usr/include/<triplet>` (thanks @hhromic). 
We should probably revise the `FindSDL2.cmake` package with a more modern version.

Minor - remove BOM from `FindRapidJSON.cmake` (fixes #643) to fix an bug in old CMake versions.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909740

### CODE REVIEW

**Comment by joolswills** [comment]
Is this complete ? Wanted to check as there looks like some line ending or whitespace change? Thanks for this - Didn't expect this so soon after I tried to offload the work :-)

**Comment by joolswills** [comment]
Ah sorry - the other change is the one you referenced with BOM - I wasn't sure what that mean't

**Comment by joolswills** [comment]
Will test and merge - sorry for spam.

**Comment by joolswills** [comment]
Thanks!

**Comment by hhromic** [comment]
> Augment PATH_SUFFIXES to search in /usr/include/<triplet>

Just wanted to clarify that the solution is not described correctly and can be misleading.

Adding `SDL2` to `PATH_SUFFIXES` does NOT make CMake to search in `/usr/include/<triplet>`. CMake is indeed [already searching there](https://cmake.org/cmake/help/latest/command/find_path.html).

What the solution in this PR does is to add `SDL2` as an additional *possible* suffix to use when searching in all the configured paths, including `/usr/include/<triplet>`, by CMake. Part of the list of paths to search is given by the `PATH` keyword, currently set from `SDL2_SEARCH_PATHS`:
```
~/Library/Frameworks
/Library/Frameworks
/usr/local  <-- this and ...
/usr   <- this is why the current version of FindSDL2 works in standard systems
/sw # Fink
/opt/local # DarwinPorts
/opt/csw # Blastwave
/opt
```
Then, what CMake does with the suffixes is to search like this (before this PR):
```
/Library/Frameworks + /include/SDL2
/Library/Frameworks + /include
/usr/local + /include/SDL2   <-- we might find SDL2 here
/usr/local + /include
/usr + /include/SDL2   <-- here we find SDL2 in most standard systems
/usr + /include
/usr/include/<triplet> + /include/SDL2   <- won't find SDL2 there
/usr/include/<triplet> + /include   <- won't find SDL2 there
(... and all the other paths in CMake, besides the ones in PATH ...)
```
This is the reason why SDL2 couldn't be found in the <triplets> case. Now, with the change in this PR, the path *suffix* `SDL2` is also considered for the *same search paths*:
```
/Library/Frameworks + /SDL2   <-- new suffix
/Library/Frameworks + /include/SDL2
/Library/Frameworks + /include
/usr/local + /SDL2   <-- new suffix
/usr/local + /include/SDL2   <-- we might find SDL2 here
/usr/local + /include
/usr + /SDL2
/usr + /include/SDL2   <-- here we find SDL2 in most standard systems
/usr + /include
/usr/include/<triplet> + /SDL2   <- now we can find SDL2 here !
/usr/include/<triplet> + /include/SDL2
/usr/include/<triplet> + /include
```
As you can notice, most paths to search are obviously wrong but still the right ones are there so "it works". This is the reason why I recommend to use a modern, better programmed, `FindSDL2.cmake` module.

Sorry to be pedantic but I feel this needs to be understood correctly to know how CMake really works. I hope this is clearer now. Cheers!

**Comment by joolswills** [comment]
Appreciated. Thanks.

**Comment by joolswills** [comment]
I also agree - and the FindSDL2 code is based on even older FindSDL code. It should imho be using sdl2-config / pkg-config or something rather than just trying lots of paths etc.

**Comment by joolswills** [comment]
PRs welcome ;-)

**Comment by hhromic** [comment]
> It should imho be using sdl2-config / pkg-config or something rather than just trying lots of paths etc.

The modern way for CMake is to use *config modules* which are similar to the concept of sdl2-config/pkg-config. Dependencies are responsible for providing these CMake config modules. In fact SDL2 does provide one since ~2017 so is not guaranteed to be provided for older versions. On the other hand pkg-config files provided by dependencies are known to sometimes be wrong therefore CMake doesn't recommend using them (even though SDL2's pkg-config files are correct most of the time).

The modernised `FindSDL2.cmake` module I suggested before from [this repository](https://gitlab.com/aminosbh/sdl2-cmake-modules/) has been made with a lot of these things in consideration so I think we should adopt it. Worth to mention that the solution on this PR was found by testing with this modernised version.

It does not use sdl2-config, pkg-config nor a config module but relies on CMake itself to do search (which is pretty smart actually) for maximum compatibility across different platforms. It also makes sure to use compiler flags in the correct order and to use SDL2main when necessary.

> PRs welcome ;-)

Okay will do!

**Pull request merged**
