### PR TITLE
add black splash

### PR DESCRIPTION
**Pull request by HerbFargus**
fade still needs to be addressed. because its annoying.

### CODE REVIEW

**Comment by HerbFargus** [comment]
what its looking like is that it utilises the same fade function for the transitions for the rest of emulationstation so in order to address the white fade the fade opacity can be changed to a 1 here:

https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/views/ViewController.cpp#L30

but it does it for all transitions and breaks it, so its likely we'll have to create a fade function specific to just the splash loading. Other alternatives include removing the splash altogether with a command line argument or just dealing with a white fade before a black screen.

**Comment by HerbFargus** [comment]
@joolswills After almost a year finally thanks to @pjft I believe we can finally merge it. the following is what it will look like (on top) Thanks to Rookervik for his artwork as usual.

emulationstation

I've tested based on the latest merge and it seems to be functioning.

There may also be merit to a discussion on hardcoding in some "Don't pay money for free stuff especially to greedy dbags that steal our work" type language on the ES splash but I imagine that the recently added no splash flag integration more or less undermines the effectiveness of such a message and would be removed promptly on any bootleg image by anyone with half a brain. but I digress. 

There's also some former discussion on the matter on our old forum by the original ES UI designer (http://blog.petrockblock.com/forums/topic/modify-logo-and-menu-emulationstation/#post-23538) and here: https://github.com/Aloshi/EmulationStation/issues/203 but anyways.

thanks again to @pjft for his lovely work.

**Comment by pjft** [comment]
Oh this is wonderful, I need to look into this!

I was reading the code, though, and it's not clear to me: is the goal to
fully replace it, or to add it as an option?

**Comment by joolswills** [comment]
For now it's to just replace it with a black version.

**Comment by pjft** [comment]
Sounds good.


- Paulo Tavares

**Comment by HerbFargus** [comment]
Thanks :D

**Pull request merged**
