### PR TITLE
Go-to Random Game feature

### PR DESCRIPTION
**Pull request by zigurana**
Hi!
This is a PR to enable users to jump to a random game with the push of a button (currently: x). The idea is to get people to play games they would otherwise not consider playing, especially when they have a large collections of games to choose from.
The changes are relatively small, and tested on a test-collection with sub-folders.
I am unsure if recounting all the games every time this is called will take prohibitively long or not, so I would like to get some feedback on that, if possible. I've tried it with a setup with 20K (dummy) files for a system, and that had no discernable effect on performance. Note that this was on a windows machine, but I suspect it will not matter, as ES gets the info from it's internal data-structures (in RAM) anyways.

Let me know what you think!

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks - if anyone has time to help me with testing would appreciate it cheers.

**Comment by zigurana** [comment]
Updated as per the feedback from the ever helpful @pjft, 
* fixed integer overflow
* now also allows going to random game from SystemView

**Comment by pjft** [comment]
Looks good to me. Tested, no concerns from my end.

**Comment by joolswills** [comment]
Thanks all.

**Pull request merged**
