### PR TITLE
 Add shoulder button paging

### PR DESCRIPTION
**Pull request by csonsino**
This change adds a menu option to enable page up/page down scrolling using the left shoulder/right shoulder buttons.

The `leftshoulder` and `rightshoulder` buttons are automatically mapped during the initial input configuration wizard, but they are not used in the emulationstation interface.  Conversely, the `pageup` and `pagedown` buttons are not automatically mapped, but they provide useful functionality in the emulationstation (game list) interface.

Instead of this change, the same effect could be easily accomplished by manually editing `es_input.cfg`, adding rows for `pageup` and `pagedown,` but in the spirit of not having to edit config files for nice functionality, this adds the option to the menu.  Although I should also note that I'm not convinced that this behavior actually needs a configurable menu item- as far as I'm concerned using `leftshoulder` and `rightshoulder` as `pageup` and `pagedown` should be the default behavior.

### CODE REVIEW

**Comment by pjft** [comment]
I'm fine with it being a default behavior rather than an option.

**Comment by csonsino** [comment]
Using it as the default behavior makes the change much simpler.

**Comment by hex007** [comment]
Doesnt this already work by default. L1 and R1 are mapped to PGup and PGdn??

**Comment by csonsino** [comment]
L1 and R1 aren't mapped to PGup and PGdn for me.  When I go through the initial controller setup, I don't end up with that mapping for either my joystick (custom I2C bus based) or my keyboard.  Would that mapping show up in `~/.emulationstation/es_input.cfg` or some other place?

**Comment by hex007** [comment]
Are you running it on Raspberry pi or Linux PC?

**Comment by pjft** [comment]
Hex is of course correct. My bad.

I read this over email and my main point was for not to add a new option.

I thought you were referring to R2/L2 and that it would be a bigger leap.

R1 and L1 should indeed already be mapped to the current page up/down
functions.

**Comment by hex007** [comment]
@pjft unfortunately L1 R1 do not work as expected on Linux but work on raspberry pi. Seems strange. Can you test it and confer.

**Comment by pjft** [comment]
I confirm they work on the Pi, can't promise it does work on all types of
controllers though I'm not sure why it wouldn't. I've used a PS3, PS4,
generic USB and keyboard controllers, all working when pressing R1/L1.

If they don't work on Linux, then it's certainly a bug. If they're not
working on the Pi for a specific controller type, would you (@csonsino)
post about it on the forums first as the may be more people with experience
with it?

**Comment by csonsino** [comment]
I'm running on a Pi- started with Raspian Jesse Lite and installed RetroPie-Setup.  In all libretro based games, all of my buttons work correctly (including L1/R1, which are labeled Left Shoulder/Right Shoulder during the guided contoller setup- correct?).  But in the EmulationStation interface, none of the buttons function as Page Up/Page Down to jump several games in the game lists.

The controller is custom built using an IO Pi Plus (Pi port expander) that runs on the I2C bus, so it's unlikely that other people would have a similar setup.  But like I said- the buttons all function correctly in games so I don't think that there is a problem with the controller.

If this functionality works out of the box for everyone else on the planet, I'm happy to abandon this change and just manually edit my es_input.cfg file, mapping Page Up/Down to my shoulder buttons.  But I couldn't (and still can't) find any place in the code that would actually map the L1/R1 (L Shoulder/R Shoulder) buttons to Page Up/Down.

**Comment by HerbFargus** [comment]
just for the record I've never gotten the shoulder buttons to work to scroll even though they said they were supposed to

**Comment by joolswills** [comment]
Page up and down mapping relies on RetroPie input configuration for the config file generation.

**Comment by csonsino** [comment]
Found it, thanks.

**Comment by joolswills** [comment]
basically, the input configuration makes es_temporaryinput.cfg which is then used to make the es_input.cfg - which has pageup/pagedown instead of leftshoulder/rightshoulder.

Probably should be changed to use left/right shoulder instead but have to be careful if mixing different versions of es / retropie-setup. I'm ok though with this changeset as a workaround, for those using ES but without the input config generation stuff. Although in that case we should probably make it so it doesn't ask you to define all the buttons. Basically this is still the RetroPie fork of ES, and is designed to be used with RetroPie.

**Pull request closed without merging**
