### PR TITLE
Changed pageup/pagedown to leftshoulder/rightshoulder for consistency…

### PR DESCRIPTION
**Pull request by HeuristicPerson**
The main reason behind this change is to fix a bug with controls configuration where ES was saving the controls as:

```
...
<input name="leftshoulder" type="button" id="4" value="1" />
<input name="rightshoulder" type="button" id="4" value="1" />
...
```

While the program needed:

```
...
<input name="pageup" type="button" id="4" value="1" />
<input name="pagedown" type="button" id="4" value="1" />
...
```

Since all the internal names refer to the pad controls, it makes sense for consistency reasons to rename all the existing references to `pageup`/`pagedown` in the code to `leftshoulder`/`rightshoulder`.

### CODE REVIEW

**Comment by pjft** [comment]
Thanks for putting this together. I haven't had the chance to test it, but last I saw there was an ongoing thread in https://retropie.org.uk/forum/topic/22191/l-r-shoulder-buttons-not-working-to-jump-letters/24 .

I take it it's still being tested and developed?

Thanks.

**Comment by PixelGordo** [comment]
Hi, pjft.

I alreay expresed my opinion in that thread: no matter what are the external effects of this patch, it seems correct to me to be consistent and call the input just in one way inside ES code. With those modifications I can configure and use the PS3 controllers with no problem.

I haven't had the time to take a look at the script @mitu mentions but if it stops working for other controllers, I'd say that the problem is in the script, not in ES.

Regards

**Comment by Koerty** [comment]
You can remove the comments I left in GridGameListView.cpp, they doesn't make sense anymore after this changes.

**Comment by PixelGordo** [comment]
Updated, @Koerty

**Comment by 5schatten** [comment]
this needs a rebase

**Comment by joolswills** [comment]
Closing as has been superseded with another patch. Thanks.

**Pull request closed without merging**
