### PR TITLE
Replace Eigen with "inhouse" vector and matrix math

### PR DESCRIPTION
**Pull request by tomaz82**
This patch removes Eigen as a dependency. Eigen itself is a quite large library with a lot of optimized math functions, which ES uses none at all. The few things it does use has no benefits of the optimizations that Eigen can do. These 5 classes replace the few pieces that ES actually use at a much smaller footprint and way simpler (and potentially faster) code. Where Eigen is a maze of templates and inheritance this is simple and straightforward.

As an added bonus this also drops the compile time by about 30%.

Sorry about this new PR, I really don't get along with git right now...

I added 4 more classes:
Matrix3x3
Scale3 to create a 3x3 scaling matrix
Rotation3x3 to create a 3x3 rotation matrix
Transform4x4 which is the one to replace the old Affine3 from Eigen

The reason for that is because what Affine3 did wasn't "correct" matrix4x4 math, so I kept the correct math in Matrix4x4 and did the more, imho, hackish way in Transform4x4, but this means everything behaves the way it should.

@jrassa I added the constructors to toss around v2, v3 and v4 between eachother, however the functions v3() and so on can only be called on a vector that's larger, due to it returning a reference. So v2 has none, v3 has v2() and v4 has v2() and v3(), I hope that's ok.

@jrassa @hex007 You were correct about Eigen taking radians so all that was fixed, this also removed the need for pi.

### CODE REVIEW

**Comment by tomaz82** [comment]
I also wanted to open a discussion regarding the usage of Comma-Initializers.
Where you now do things like
vec3 << float, float, float;
Is this really, needed? It would be more performant to call the regular set method:
vec3.set(float, float, float);

It's an easy change.

**Comment by pjft** [comment]
I've been following the other PR and now this one. Thank you very much for going through this. It is very much appreciated. 

In regards to the initializer, I'm personally all up for changing it to the set version. It's similarly readable.

Thanks.

**Comment by tomaz82** [comment]
@pjft Thanks, yeah  I agree about the initializers.
Again, sorry for the new PR, been using SVN and Mercurial for the past 15+ years, just starting to learn git now and this new PR could have been avoided had I know about force push...

**Comment by zigurana** [comment]
I like the `set(float, float, float) ` better, I personally had not seen the` << ` before in other uses than to write a string to a logfile, so getting rid of it does not hurt me, at all.

Thanks!

**Comment by tomaz82** [comment]
Oh, I almost forgot, a second thing to discuss, having the members of the vector and matrix classes be public, avoiding having to do vec3.x() and just do vec3.x, this breaks the rule to have getters for everything, like x(), y() and so on, but you generally break that rule when you deal with vector and matrix math due to the slight increase in performance.

Thoughts on that?

Example:
cameraOut.translate(Vector3f((sw / 2) - centerPoint.x(), (sh / 2) - centerPoint.y(), 0));

would become:
cameraOut.translate(Vector3f((sw / 2) - centerPoint.x, (sh / 2) - centerPoint.y, 0));

**Comment by pjft** [comment]
I don't have a strong opinion on the second question. I imagine the idea of not being then public is to avoid people setting them directly?

As for the << syntax for logs, I think that's not going to change though, or did will that change as well? This was only for initializing, whereas for the logs I think it's the proper syntax as It mimics the cout ostream syntax.

**Comment by tomaz82** [comment]
@pjft The question about the <code><<</code> was purely when dealing with vectors.

**Comment by jrassa** [comment]
> @jrassa I added the constructors to toss around v2, v3 and v4 between eachother, however the functions v3() and so on can only be called on a vector that's larger, due to it returning a reference. So v2 has none, v3 has v2() and v4 has v2() and v3(), I hope that's ok.

Sounds good.

> I also wanted to open a discussion regarding the usage of Comma-Initializers.
> Where you now do things like
> vec3 << float, float, float;
> Is this really, needed? It would be more performant to call the regular set method:
> vec3.set(float, float, float);

I am fine with changing it.

> Oh, I almost forgot, a second thing to discuss, having the members of the vector and matrix classes be public, avoiding having to do vec3.x() and just do vec3.x, this breaks the rule to have getters for everything, like x(), y() and so on, but you generally break that rule when you deal with vector and matrix math due to the slight increase in performance.

I don't think the performance of the vector/matrix math is a concern and I would recommend leaving it as is.

**Comment by jrassa** [comment]
I checked out the branch.  I had to make a bunch of changes to get it to compile under Ubuntu.  Once I got it working, I did some timing comparisons and on my Ubuntu dev box the build was around 13% faster.  I did some quick testing and everything appeared to render fine.  I would still like to give it a more thorough testing.

The changes I had to make can be found in this branch.
https://github.com/jrassa/EmulationStation/tree/eigen

That all being said, I am curious what was the motivation behind making this change?  I am generally supportive of it, but I also recognize that it adds more code that will need to be maintained over time.

**Comment by tomaz82** [comment]
The motivation was that I saw a dependency that was not necessary. Eigen is a very nice product for what it does, which is advanced matrix manipulation. ES used only a very small fraction of what Eigen can do and I knew that I could easely replace that small fraction with inhouse code, thus eliminating a quote big dependency.

Will look at your fixes and am setting up an Ubuntu dev box right now for future tests.

**Comment by tomaz82** [comment]
Have a Ubuntu dev box setup now so will compile all changes on that as well to avoid those errors in the future. Will remove the Comma-initializer later on today.

**Comment by tomaz82** [comment]
I think I have adressed everything that has been discussed. One final thing I wanted to look into would be the need for double support on the vectors and matrices. I have a strong feeling those aren't needed, which in turn means that the transform and matrix classes doesn't even need to be templates.
And for vectors, I guess it's only Vector2 that uses i in some places, v3 and v4 might be fine with being float only? If so then it would be better to just duplicate vector2 into 2 classes, 2i and 2f and get rid of all the templates all together.

Thoughts?

**Comment by tomaz82** [comment]
A couple of benchmarks:

Parsed include lines: ( rough estimate using Header Hero )
Eigen:   51 000 000
Tomaz: 37 000 000 ( 27.4% less )

Compile time: ( 64bit release MSVC 2015 )
Eigen:   101s
Tomaz: 68s ( 32.7% faster )

Frametime ( using nes-mini theme with a video playing )
Eigen:   30ms
Tomaz: 22ms ( 26.7% less)

Now these are numbers on my computer, so it may very well differ on others or on a Raspberry Pi. But it should still make a difference, and well, better frametimes == less cpu usage when v-synced == less power usage :)

**Comment by zigurana** [comment]
Those are impressive numbers!
To clarify : these are comparing the total number with eigen vs with your new implementation, so the total nr of included lines and total build time, not just for the eigen/tomaz submodule?

**Comment by tomaz82** [comment]
Yes, compiling entire EmulationStation fresh for both

**Comment by zigurana** [comment]
Wow! Awesome!

**Comment by tomaz82** [comment]
Just rebased this PR against latest master

**Comment by tomaz82** [comment]
Yes it is

**Comment by joolswills** [comment]
Sorry this will need a rebase due to other recently merged PRs.

**Comment by tomaz82** [comment]
On it already, give me 2 minutes

**Comment by tomaz82** [comment]
There, back on track

**Comment by joolswills** [comment]
Thanks. Is everyone else happy for me to merge this? - it will mean other PRs may need rebasing - @pjft @jrassa

**Comment by pjft** [comment]
The PR I'm putting together is very small, so it's easy for me to rebase. Thanks for the heads up.

@zigurana - you have a few big ones in process, namely the Kids mode and the Collections refactoring. Any thoughts or concerns?

**Comment by zigurana** [comment]
No, please go ahead and merge. 

I will squash and rebase the kids mode one, that should be about finished now. The Collections refactoring one will need a bit more work.

**Comment by joolswills** [comment]
Merged - thanks all.

**Pull request merged**
