### PR TITLE
[EXPERIMENTAL] Localization

### PR DESCRIPTION
**Pull request by Koerty**
**This pull request is not supposed to be reviewed or merged (at least not in it current state), I made it so you can easily check the code changes and discuss about localization.**

So, while waiting for the GridView last verifications and first feedbacks from users, I started working on localization thanks to the library boost::locale

Here is a short resume on how it work for those who are interested :
 - The common way is to create a macro simply named "_" which will be used on every string needed to be translated, this macro call the boost::locale::gettext function
 - A call to the [gettext](https://www.gnu.org/software/gettext/) command in a terminal analyze the cpp files and extract the string to translates and create a .pot file (it describe which string we need to translate)
 - A call to the msginit command in a terminal create a .po file from the .pot file (this is where we will put our translations )
 - A call to the msgfmt command in a terminal create a .mo file, a "compiled" version of the .po file, which will be included with the binary

The problems I encountered so far :
 - There is many redundancies in string to traduce : this system know "back" and "back" are the same string, but "back" and "BACK" aren't, when most of the time we just capitalize it later, maybe we should capitalize everything or not I'm not sure about this
 - The menu is designed so the english translations can fit, some french translations for example are cut due to the string being too long to fit in the menu
 - Can someone check if the change on Util.cpp is correct ? The 2nd strToUpper function in particular, I'm not an expert in C++ so if you are experienced with this langage feel free to give me some feedback
 - Some lists like the one allowing the user to choose what gameview he want to use are broken. It's kinda hard to explain, for example the GridView is called "detailed" in english, "détaillé" in french, so it look up for a view called "détaillé" and can't find it. There is different ways to fix this, the cleaner one would be to separate all the names which are displayed in the UI from the names used internally, but this would be quite a big change since we have the same problem for screensavers style, for transition style, ....
- I'm not sure either about the changes on GuiFastSelect.h, does Japanese for example use latin alphabet or japanese alphabet for their roms name (or a mix of both ?). This can easily lead to issues.

I finish this PR by posting screenshots :

capture d ecran de 2017-08-15 02-03-46
capture d ecran de 2017-08-15 02-04-12
capture d ecran de 2017-08-15 02-04-40
capture d ecran de 2017-08-15 02-05-25

### CODE REVIEW

**Comment by Koerty** [comment]
Here come the tag army @jrassa @pjft @lilbud @joolswills @zigurana

Feel free to tell me if you don't want to be tagged anymore, I can understand that ;)

**Comment by hex007** [comment]
Is this taken from Recalbox? I have seen them support locale using _String. 

Do we have a need for changing/supporting locale? 

@Koerty Have you checked on the forums if there is a demand for this?

**Comment by Koerty** [comment]
@hex007 It's possible they also use "_" for localization, it's a convention so many developers and projects use that syntax.

I haven't checked the forums, but it look like an important feature to me and I saw @jrassa talking about it on @zigurana post on the forum or issue I don't remember, it sounded like the next big step after a more modular gameview.

Is that a problem that I push big changes like that ? Should I make a poll or open a topic on retropie's forum or anything like that ?

**Comment by jrassa** [comment]
@Koerty the general preference is for new features/changes to be posted to the forums first.  Posting to the forums will ensure that your ideas are seen be a wider audience.  Only a few people actively monitor things here on github.

**Comment by pjft** [comment]
Thanks for tagging. I don't mind being tagged, though I do subscribe to all
PRs by email any way, so even if not tagged I'll receive them :)

Thanks for putting this together.

I have indeed seen something like this in Recalbox.

While I personally won't use it, I think that if there's demand, it could
make sense to be pursued. I do have a few questions around the impact this
will have on the translations side of things as well as on new
developments.

While Recalbox is centrally managed and seems to have somewhat "stabler" ES
developments (I don't know if they have video yet, for instance, I think
they're still on 2.1.4 if memory doesn't fail me), they also have a
dedicated set of members who handle localization in the community. They
also only provide binaries, for the most part, I believe.

What would this mean for us and new developments? Would we need to
translate all new features in new languages before launching? Which
languages? Will this slow things down for new developments, potentially
with marginal gain?


These are some things to consider in the grand scheme of things. But
overall, as I said, if there's demand for it and a thought out structure
for it in the long run, it could be a welcome development.

**Comment by hex007** [comment]
@Koerty  jrassa summed it up perfectly

**Comment by Darknior** [comment]
WOAW you release my DREAM lol
It is one of the excellent feature Recallbox have, and i would like Retrpie get it too :)
I'm french like you, and with many friends we dream of this feature for us and our little children ...

@Koerty is real ... it can be a good idea to make a poll in the forum to other users that don't watch the Git know you will add this feature :)
And post the forum link here ;)

@pjft is real for the new developments ...
We will need to translate all new features in new languages. But maybe not before launching. I think a new feature can be launched in English like ever, and after we open a poll to ask for translate it on the forum. Like that it will not slow things down for new developments.

Which languages ? For my part i think it can be cool to have like on 95% games ...

Professor Layton 3 - and the Unwound Future (Europe) (En,Fr,De,Es,It)
ENGLISH, FRENCH, DEUTSCH, SPANISH, ITALIAN

Some games add : Nl,Sv,No,Da,Ne,Jp ... but i don't know if we have many users here who use these langages, and it will be harder to translate for so many countries.

@Koerty Caîtalize every thing in the menu is a good idea. But it will take more space and like you write, the menu is designed to english translations can fit, some french translations will be cut due to the string being too long to fit in the menu. And i d'ont know if you can change dynamically the menu size, but it will be a pain to code it on the new feature each time ...

**Comment by zigurana** [comment]
@Koerty 
Hi Koerty, I also get an email for all PRs, so no need to explicitly tag, unless you need my 'expertise' particularly. Anyways, it doesn't hurt me either, so no worries :-)

If you want to build this, no matter what, please go ahead and do it.

If you are doubting whether or not to build this, because you are not sure if users will like it, then go ask on the forums. Be aware though, that there are many types of users, and the resulting picture will not necessarily be very consistent. Also, asking: "Would you like item A1?" will result in answers like "Yes! I would like A2, as well as B, C and D, and a pony, can you do the pony first?"

If you are doubting whether to do this or not, because it might not be taken into the main branch because other developers might not like it, I would discuss it here. It's a bit more quiet, and I find the discussions more focused on implementation issues, usability etc. People with a strong opinions will find this discussion anyways.

**Comment by Koerty** [comment]
@pjft I don't think it will have any impact on developpement speed.

When you want to add a new entry to the menu for example, all you have to do this is put _( ) around the string which need to be translated, you would write the title of your new entry like this : _("My new entry name") instead of "My new entry name"

That's all you have to as a developper, here is how it goes next :
 - if the exact same string have already been translated, yours will be automatically translated
 - if no translation is available for this string, it will be show in english (like you wrote it actually) until a translation is added

The files for translation are :
 - a .pot file which list every string needed to be translated (+ some extra informations)
 - a .po file for every langage, this is where we put our tranductions
 - a .mo file for every langage, this is a binary version of the .po which will be distributed with emulationstation

I didn't take a look yet on how to do that because I don't know much about cmake, but I think we can automatically generate/update this files using cmake and make. There is also so tools like POeditor, POedit, which help translators to work with translate files, I also need to take a look.

**Comment by Koerty** [comment]
@jrassa @hex007 Ok I make a post on the forum.

@zigurana That's the problem, I don't want to make a pony ! I love to work on side projects because I can choose to work on (nearly) whatever I want whenever I want, this is the most funny part about side projects, and my only motivation is I'm having fun atm (+ helping the community, but that alone don't bring me enough motivation to keep working on it).

So if I'm forced to work on stuff I don't want to do, then for me there is no point in working on this side project anymore (at least at work they give me shit tons of $$$ for working on stuff I don't want to).

**Comment by Koerty** [comment]
Here we go : [](https://retropie.org.uk/forum/topic/12296/emulationstation-localization-translation)

**Comment by Koerty** [comment]
@pjft Btw isn't RecallBox's version of EmulationStation dead already ? Last time I checked they didn't push often on the repository, the lasts months being the worst as they haven't pushed anything for like a year.

**Comment by Koerty** [comment]
I'm closing this pull request. The code base changed so much since its creation that it now have 21 files in conflicts. Due to the nature of the code changes in this pull request, it would be easier to just restart everything from scratch than resolve all this conflicts.

**Comment by Darknior** [comment]
Ok. I really wish you will release it one day.
I translate ES in French with Webtropie, I don't know if you know this great project I help a lot... And it is so excellent to use 😀

**Comment by lilbud** [comment]
And another one gone, And another one gone , Another gridview bites the dust

**Comment by Koerty** [comment]
@lilbud I don't know what you are trying to achieve by trolling me on my pull requests, but if you have nothing interesting to say, then don't comment here anymore ty.

**Comment by lilbud** [comment]
@Koerty Sorry, I thought this was the gridview PR and thought it was dead again. Complete goof up on my part.

**Pull request closed without merging**
