### PR TITLE
Fix WSOD by loading textures on demand in a separate thread when a us…

### PR DESCRIPTION
**Pull request by fieldofcows**
…er configurable texture memory threshold is reached

Including fix for texture opacity that was an issue in the previous PR.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks - Will give it a quick test and merge - appreciate your work on this.

**Comment by HerbFargus** [comment]
Gave it a test with the tronkyfran theme. I have about 23 systems on it.

Issues:
- When changing to the theme it is a white screen. have to enter the detailed view and back out to render it proper or restart emulationstation (though I believe this was the case before the wsod fix rather than something the fix caused)
- At about the 13th system the wallpapers are just white. logos and everything load, but the background wallpaper stays white for systems 14-23

**Comment by fieldofcows** [comment]
I'm not sure what's going on there but I don't see any of those issues on my raspberry pi 3. I can switch themes without issue (although the theme only loads correctly when the GUI is closed) and I can use the tronkyfran theme with much more than 23 systems.

I'm building from my branch which is equivalent to the RetroPie master with the WSOD fix in place. I've tried building with and without the threading fix as well and it still behaves consistently.

I've also left it running for a long time and seen no freezes or segfaults.

Hmmm...

**Comment by HerbFargus** [comment]
When I get a moment I can try building it from a fresh image just to make sure any configurations I've made aren't conflicting for some reason, just to see if it is reproducible.

**Comment by fieldofcows** [comment]
If it helps I can give you my built executable to try alongside your configuration.

**Comment by HerbFargus** [comment]
Sure. Just as a reference, I built it on my pi using a module based on kids mode. It may have segfaulted due to the compilation bugs Jools had mentioned earlier, though im not sure if those were specific only to the pi2. Would have to look into it more.

**Comment by fieldofcows** [comment]
[emulationstation.zip](https://github.com/RetroPie/EmulationStation/files/739066/emulationstation.zip)

**Comment by HerbFargus** [comment]
Thanks, I'll give it a go once I get off work

**Comment by HerbFargus** [comment]
This is the module I used to install it:

http://pastebin.com/X8YySz8w

So I started again from a fresh image and now it seems to be working as it should. I haven't tested extensively, still need to run it with kodi and play with a few other settings (adding videos etc)

**Comment by joolswills** [comment]
Sorry for the delay - not had a chance to test yet (I'm sure it's fine). Will merge v.soon.

**Comment by HerbFargus** [comment]
I think the fluke in the case of my former test was that I had installed the pixel desktop environment. I'll have to reinstall it to see if it's reproducible but I don't see why that would cause any adverse effects...

**Comment by fieldofcows** [comment]
I've just given this another really good going over with 74 systems on the raspberry pi 3. I've tested it with the following themes:
- tronkyfan
- pixel
- oldroom
- zoid
- carbon

I rebooted a couple of times looking for problems on startup. I switched between themes multiple times. Went in and out of (simulated) games.

I also tried installing Pixel Desktop and running the same tests.

I saw no issues in any of my tests.

**Comment by joolswills** [comment]
Great job. Works really well.

**Comment by joolswills** [comment]
wrong button ;-)

**Pull request merged**
